### PR TITLE
docker: slim docker image to 154Mb

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by barakbd** [comment]
@flovilmart - will check soon.
You are using the lts version of Node in the Dockerfile. Is that ok? Are the unit tests always running against the lts version of Node?

**Comment by flovilmart** [comment]
The tests are running against node 10. We’ll update the CI setup to effectively run always against lts

**Comment by barakbd** [comment]
There is an issue with the image built using your Dockerfile, not sure what it is.
When I call GET on localhost:1337/parse/schemas it returns:
```
{
    "results": []
}
```

But when I call that API using image **parseplatform/parse-server:3.0.0** or the image built with **my Dockerfile**, I get:
```
{
    "results": [
        {
            "className": "_User",
            "fields": {
                "objectId": {
                    "type": "String"
                },
                "createdAt": {
                    "type": "Date"
                },
                "updatedAt": {
                    "type": "Date"
                },
                "ACL": {
                    "type": "ACL"
                },
                "username": {
                    "type": "String"
                },
                "password": {
                    "type": "String"
                },
                "email": {
                    "type": "String"
                },
                "emailVerified": {
                    "type": "Boolean"
                },
                "authData": {
                    "type": "Object"
                }
            },
            "classLevelPermissions": {
                "find": {
                    "*": true
                },
                "get": {
                    "*": true
                },
                "create": {
                    "*": true
                },
                "update": {
                    "*": true
                },
                "delete": {
                    "*": true
                },
                "addField": {
                    "*": true
                }
            }
        },
        {
            "className": "_Role",
            "fields": {
                "objectId": {
                    "type": "String"
                },
                "createdAt": {
                    "type": "Date"
                },
                "updatedAt": {
                    "type": "Date"
                },
                "ACL": {
                    "type": "ACL"
                },
                "name": {
                    "type": "String"
                },
                "users": {
                    "type": "Relation",
                    "targetClass": "_User"
                },
                "roles": {
                    "type": "Relation",
                    "targetClass": "_Role"
                }
            },
            "classLevelPermissions": {
                "find": {
                    "*": true
                },
                "get": {
                    "*": true
                },
                "create": {
                    "*": true
                },
                "update": {
                    "*": true
                },
                "delete": {
                    "*": true
                },
                "addField": {
                    "*": true
                }
            }
        }
    ]
}
```

**Comment by flovilmart** [comment]
How did you mount / run it?

**Comment by barakbd** [comment]
1. Pull branch **dev** from https://github.com/barakbd/parse-server-docker-compose.git 
2. line 8 in docker-compose.yml - replace the image name with the name and tag of the image you built locally
3. In the directory where the docker-compose.yml exists - run `docker-compose up`
4. Make an API call in Postman with masterKey and appId in the headers. You can get/set them in the .env file
5. To destroy the containers, run `docker-compose down`

**Comment by barakbd-bluevine** [comment]
If it works for you then go ahead and merge to master, and build a new image for Dockerhub.

**Comment by flovilmart** [comment]
@barakbd that's not the point, I am trying to avoid a regression if there is any. Did you try in another context like directly using the docker image?

**Comment by flovilmart** [comment]
@barakbd I also realized the `VOLUME` instruction with the single quotes was malformed 

> JSON formatting: The list is parsed as a JSON array. You must enclose words with double quotes (") rather than single quotes (').

https://docs.docker.com/engine/reference/builder/#volume

Perhaps this was your issue

**Comment by barakbd** [comment]
I tested again, still not working when running with a local mongodb docker.
When I run with the current parse-server docker image (**parseplatform/parse-server:3.0.0)** I see this output from the mongodb container, which I do not see with your image:
`mongo-3.6       | 2018-12-19T20:06:51.528+0000 I STORAGE  [conn1] createCollection: parse_db._User with generated UUID: 1087310c-9403-44c7-b662-bd133798d8c0
mongo-3.6       | 2018-12-19T20:06:51.542+0000 I INDEX    [conn1] build index on: parse_db._User properties: { v: 2, unique: true, key: { email: 1 }, name: "email_1", ns: "parse_db._User", background: true, sparse: true }
mongo-3.6       | 2018-12-19T20:06:51.548+0000 I INDEX    [conn3] build index on: parse_db._User properties: { v: 2, unique: true, key: { username: 1 }, name: "username_1", ns: "parse_db._User", background: true, sparse: true }
mongo-3.6       | 2018-12-19T20:06:51.548+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo-3.6       | 2018-12-19T20:06:51.548+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongo-3.6       | 2018-12-19T20:06:51.550+0000 I STORAGE  [conn2] createCollection: parse_db._Role with generated UUID: a66f7572-fcfa-4f53-b496-b7005a995626
mongo-3.6       | 2018-12-19T20:06:51.563+0000 I INDEX    [conn2] build index on: parse_db._Role properties: { v: 2, unique: true, key: { name: 1 },name: "name_1", ns: "parse_db._Role", background: true, sparse: true }
mongo-3.6       | 2018-12-19T20:06:51.563+0000 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs`

**Comment by flovilmart** [comment]
Well, that doesn’t help much. What do you mean by ‘not working’? Is the Schema still the same? Are there any logs? Is the master branch showing a proper behaviour?

**Comment by barakbd** [comment]
Have you tried running it with the docker compose setup in the repo I sent?
Any way you can push your new docker image somehwere that I can pull and test?

**Comment by barakbd** [comment]
I still get 
```
{
    "results": []
}
```

**Comment by flovilmart** [comment]
> way you can push your new docker image somehwere that I can pull and test?

I simply ran `docker build . -t my-image` if this doesn’t work for you then there is a problem. 

What are the logs from the container when started with —verbose=1

**Comment by flovilmart** [comment]
@barakbd I attempted to run your docker compose project and you can find the logs there:

https://gist.github.com/flovilmart/dfc72624d44201c6c37dabc1f640a7e9

This doesn't look good, as the DB gets killed and then restarted, at the time the server starts, the DB is not up. This doesn't look related to those changes.

**Comment by flovilmart** [comment]
If you look closely to the logs, we see:

```
 warn: Unable to ensure uniqueness for usernames:  message=failed to connect to server [mongo:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.18.0.2:27017], stack=MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.18.0.2:27017]
```

And on a following restart:

```
Unable to ensure uniqueness for user email addresses:  message=there are no users authenticated, stack=MongoError: there are no users authenticated
```

So there seems to be an issue with your docker compose setup:

1. the DB is not started / starting correctly
2. the authentication to the DB is invalid

**Comment by barakbd** [comment]
It looks like you are running master. checkout dev branch and then run docker-compose up.

**Comment by flovilmart** [comment]
Why don’t you try with the built image? Can you provide the logs when starting please?

**Comment by barakbd** [comment]
Which built image? 
Have you tried dev branch?

**Comment by flovilmart** [comment]
The image built from the repository. And no I haven’t tested the dev branch, have you? Can you provide the logs when starting up?

**Comment by flovilmart** [comment]
@barakbd I tested with your dev branch, and it is still failing when running `docker-compose up` https://gist.github.com/flovilmart/b73b8a2ad8a7f7f10722fda28bc1105c and I achieve the same result as you executing the `curl` command 

```
curl -H 'X-parse-master-key: masterKey' -H 'x-parse-application-id: appId' http://localhost:1337/parse/schemas
{"results":[]}%
```

However, if you `ctrl+c` and start a second time, you will notice that it is all good and running, so I suspect an issue in your docker compose setup which likely only occurs on first start.

**Comment by barakbd** [comment]
Your image is broken. 
Using docker compose, when parse server fails to connect to mongo, it should exit with code 7 ( this is what happens in the image tagged 3.0.0.) This is expected, if a script is run on the mongo docker image entrypoint to prepare the db (https://docs.docker.com/compose/startup-order/).

Previously this was handled with docker compose ```restart:always``` option, however, in the latest image, parse server does not exit, so docker doesn't detect a failure and does not restart.

I also tried setting re-connection options in the, however it does not seem to work. Here is a related issue.
https://stackoverflow.com/questions/16226472/mongoose-autoreconnect-option

You should verify that your Dockerfile is not missing any steps during the build process. As I mentioned previously, it seems to skip the prepare and posinstall scripts, since Dockerfile is building as root, and npm will not automatically call those scripts when user is root.

**Comment by ozbillwang** [comment]
@flovilmart @acinader @barakbd @barakbd-bluevine 

Seems this PR wasn't properly tested. I currently got this error (#5778) and discovered, after rollback the base image from `node:lts-alpine` to `node:10.16.0` (a similar Debian as `node:carbon`) , I can successfully `docker build` it.

Let me know how should I go with.

**Pull request merged**
