### PR TITLE
feat: Remove deprecation `DEPPS3`: Config option `enforcePrivateUsers` defaults to `true`

### LINKED ISSUE #8270: Remove deprecation `DEPPS3`: Config option `enforcePrivateUsers` defaults to `true`
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Deprecation to be removed in Parse Sever 6:
- `DEPPS3`: Config option enforcePrivateUsers defaults to true

### Feature / Enhancement Description

Remove deprecation, see [list](https://github.com/parse-community/parse-server/blob/alpha/DEPRECATIONS.md).

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

`enforcePrivateUsers` should default to true

Related issue: #8270
Closes: #8270

### Approach

Changes `enforcePrivateUsers`

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by dblythy** [comment]
This test is failing on Postgres:

```js
it('count users', async done => {
    const james = new Parse.User();
    james.set('username', 'james');
    james.set('password', 'mypass');
    await james.signUp();
    const kevin = new Parse.User();
    kevin.set('username', 'kevin');
    kevin.set('password', 'mypass');
    await kevin.signUp();
    const query = new Parse.Query(Parse.User);
    const count = await query.count({ useMasterKey: true });
    equal(count, 2); // count is 0
    done();
  });
```

Related: #8286

**Comment by mtrezza** [comment]
As long as the Postgres bug exists, could you use `find` instead and count the objects? So the CI stays green.

**Review by mtrezza — CHANGES_REQUESTED** [review]
Could you also update the Deprecations.md and set the status to "removed"? There also seems to be an issue with a test.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
