### PR TITLE
fix-3789

### PR DESCRIPTION
**Pull request by youngerong**
Log print password clearly, fix it. Issue: https://github.com/parse-community/parse-server/issues/3789

### CODE REVIEW

**Comment by flovilmart** [comment]
@youngerong we'd love to make a release today with your fix in, do you think you can add the relevant unit tests?

**Comment by youngerong** [comment]
Yes. I have added one relevant unit test.

**Comment by youngerong** [comment]
Yes. I have added one relevant unit test.





At 2017-05-10 21:00:54, "Florent Vilmart" <notifications@github.com> wrote:


@youngerong we'd love to make a release today with your fix in, do you think you can add the relevant unit tests?

**Comment by youngerong** [comment]
@flovilmart Yes. I have added one relevant unit test.

**Comment by flovilmart** [comment]
Thanks!

**Pull request merged**
