### PR TITLE
Remove Stage name check on aggregate pipelines

### PR DESCRIPTION
**Pull request by BRETT71**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues/7238).

### Issue Description

Add search to the array of `PIPELINE_KEYS` in `AggregateRouter.js`. This allows the use of Atlas Search Index [Click Here](https://www.mongodb.com/atlas/search) for information on atlas search

### TODOs before merging

- [ ] Add test cases
- [x] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for opening this PR.

Would you please open an issue and reference the issue here, as indicated in the PR template?

**Comment by BRETT71** [comment]
#7238

**Comment by dplewis** [comment]
@BRETT71 Check the CI there is a test case that has to be removed.

**Comment by dplewis** [comment]
Can you update the change log? And the title of this PR?

**Review by dplewis — APPROVED** [review]

**Review by davimacedo — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
