### PR TITLE
test: Add test IDs

### PR DESCRIPTION
**Pull request by mtrezza**
This adds test IDs to be excluded in external adapter repos.

Based on https://github.com/parse-community/parse-server/pull/9195; reduced changes for easier review.

### CODE REVIEW

**Review by ddrechse — APPROVED** [review]
Looks good to me.  Let's do it. Once this gets into alpha, i'll kick a build of the Storafe adapter using alpha

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.5](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)

**Pull request merged**
