### PR TITLE
Add include option to Login

### PR DESCRIPTION
**Pull request by dplewis**
https://github.com/parse-community/parse-server/issues/288

Parse previously didn't have any way to get all pointer data a User class might have on login, unnecessarily requiring an additional call to get full pointer objects.

Let me know if there is a better way to implement it.

### CODE REVIEW

**Comment by flovilmart** [comment]
Sorry but I really hate it :(

**Comment by dplewis** [comment]
I noticed there were a lot of things going on the the User class as well. There may be a lot of issue that would arise in the future.

Which part do you dislike?

**Comment by flovilmart** [comment]
That it’s kinda messy... the login method is to acquire a sessionToken, the fact there’s a user attached is actually a ‘side effect’. The thing that matters on login is not the user but the token....

**Comment by dplewis** [comment]
Ah I see your point, makes sense.

**Comment by flovilmart** [comment]
While I agree this is a bit shitty, that post login, you may wanna run a fetch with includes. 

Which makes me think, that we don’t support fetch with includes in the SDK. What do you say we add it?

**Comment by dplewis** [comment]
If you use include you don't have to fetch right?

I'm currently using fetch without include on user login on iOS. Thats why I made this PR.

Ive had it this way for a few years and early on I ran into deadlock issues when I went to refresh users. It always bugged me that I had to use fetch.

**Comment by flovilmart** [comment]
What I mean, is that on iOS, calling object.fetch() doesn’t let you specify a list of keys to include.

**Comment by dplewis** [comment]
Oh, thats interesting. How do you see it being implemented in the SDK, the fetch with keys? 

Also I always wondered is fetch faster than query.get()

**Comment by flovilmart** [comment]
Those are the exact same calls BUT, the query let you be a bit more expressive with includes

**Comment by dplewis** [comment]
@flovilmart Should we close this one?

**Comment by flovilmart** [comment]
Let’s not close it :) in the end, it may be useful if we add it with the login options .

**Pull request closed without merging**
