### PR TITLE
ci: Fix flaky definitions check

### LINKED ISSUE #8579: CI definitions check flaky
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Definitions check in CI seems to be flaky.

### Steps to reproduce

- Failed: https://github.com/parse-community/parse-server/actions/runs/5079395697/attempts/1
- Passed: https://github.com/parse-community/parse-server/actions/runs/5079395697/attempts/2

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8579

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by mtrezza** [comment]
I thought it was flaky, good fix. Is this ready for merge?

**Comment by dblythy** [comment]
It is still flaky, I haven't changed anything just yet - trying to identify the cause

**Comment by dblythy** [comment]
Screenshot 2023-05-29 at 5 28 33 pm

Changes seem to resolve the issue

**Comment by mtrezza** [comment]
Nice, can we merge this?

**Comment by dblythy** [comment]
Yep! It’s good to go

**Review by mtrezza — APPROVED** [review]
Nice!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
