### PR TITLE
GraphQL: Optimize queries, fixes some null returns (on object), fix stitched GraphQLUpload

### PR DESCRIPTION
**Pull request by Moumouls**

### CODE REVIEW

**Comment by Moumouls** [comment]
@mtrezza @davimacedo  can we merge this ?

**Comment by mtrezza** [comment]
I'm OOO today, so I won't have a chance to review immediately. The enhancement makes sense in principle though.

**Review by davimacedo — APPROVED** [review]
Sorry. I missed this one. Could you please just resolve the conflict?

**Comment by davimacedo** [comment]
Actually I've resolved myself. Let's just wait for the CI and we can merge.

**Pull request merged**
