### PR TITLE
Fix schemaCacheTTL ParseServerOption is not working

### LINKED ISSUE #7119: "schemaCacheTTL" ParseServerOption is not working
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
It seems `schemaCacheTTL` ParseServerOption is not working. It still follows cacheAdapter's setting.

### Steps to reproduce
ParseOption
`enableSingleSchemaCache`: true,
`schemaCacheTTL`: 3600000, (1hr)
`cacheAdapter`: RedisCacheAdapter

### Actual Outcome
After a simple request, I check the keys in Redis. The schema cache's TTL is 30 seconds which is the RedisCacheAdapter's default TTL.

###  Environment
Server
- Parse Server version: `4.3.0`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`
---
I'm not quite sure, but I think the problem might be [here](https://github.com/parse-community/parse-server/blob/master/src/Controllers/SchemaCache.js#L33). It doesn't pass the TTL config to the cache.

### PR DESCRIPTION
**Pull request by jack092123**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
It seems `schemaCacheTTL` ParseServerOption is not working. It still follows cacheAdapter's setting.

Related issue: closes #7119

### Approach
Pass the schemaCacheTTL config to the cacheController while setting the schema cache.

### TODOs before merging
- [x] Add test cases
- [ ] Add entry to changelog

### CODE REVIEW

**Comment by dplewis** [comment]
Can you write a test for when TTL expires?

**Review by davimacedo — APPROVED** [review]
It looks good to me. @dplewis any other comment?

**Review by dplewis — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
