### PR TITLE
Upgrade parse from 3.0.0 to 3.1.0

### PR DESCRIPTION
**Pull request by dplewis**
https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.1.0

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
I think we need a changelog entry? Makes me wonder, how do we currently inform about Parse Server <-> Parse JS SDK compatibility?

**Comment by dplewis** [comment]
We did keep track of the SDK version in the changelog (as well as other deps) a while ago. We removed it in favor of users can check the version through tags.

**Comment by mtrezza** [comment]
Can you explain? - I am thinking of: the docs say for certain features "available from parse server version x.y". But how would a developer know which Parse JS SDK version is required for the feature?

**Comment by dplewis** [comment]
They should always be using the latest version. The JS SDK doc / guide also has the versions.

**Comment by mtrezza** [comment]
Thanks, got it.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
