### PR TITLE
fix: Unable to create new role if `beforeSave` hook exists

### LINKED ISSUE #8473: Error "Tried to create an ACL with an invalid permission type."
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I am updating the parse server from "5.2.8" to "5.4.2", and getting the below error
```
TypeError: Tried to create an ACL with an invalid permission type.
    at new ParseACL (/project/node_modules/parse/lib/node/ParseACL.js:70:21)
    at ParseRole._handleSaveResponse (/project/node_modules/parse/lib/node/ParseObject.js:614:25)
    at /project/node_modules/parse/lib/node/ParseObject.js:3183:22
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
```
Whenever I got the above error the arg1 parameter in the ParseACL.js constructor is called with the below value.
```
{ __op: 'Delete' }
```

I noticed when starting from the fresh empty database. I need to start the server multiple times to start the server as before starting the server it creates some roles. Every attempt create a few more entries in the Role table, Once all roles are created Server starts.

I also tried resetting  acl in before save of Role ```request.object.setACL(new Parse.ACL());``` but still end up with same error.

Server
- Parse Server version: `5.4.2`
- Operating system:  Ubuntu
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Docker`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2.3`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `3.4.2`

### PR DESCRIPTION
**Pull request by yog27ray**
Unable to save role when before save hook is present on role.

Closes: #8473 

- [X] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by mtrezza** [comment]
This PR has been opened against the LTS branch. Could you change the base branch to `alpha` to see whether the issue also exists for the latest alpha release of Parse Server?

**Comment by yog27ray** [comment]
@mtrezza  created PR on alpha https://github.com/parse-community/parse-server/pull/8476

**Comment by mtrezza** [comment]
Thanks, let's see what the CI says there...

**Comment by yog27ray** [comment]
@mtrezza PR on alpha branch desired test cases is passing. The failing ones look like flaky test cases. The issue is on the LTS branch.

**Comment by mtrezza** [comment]
Yes, so this issue is a 5.x issue, good to know. See https://github.com/parse-community/parse-server/issues/8473#issuecomment-1463977584.

**Comment by yog27ray** [comment]
@mtrezza I updated the code to fix the issue. But the random test flows are breaking.

**Comment by mtrezza** [comment]
It seems to be just a flaky test. I've restarted the test, it should pass.

**Comment by yog27ray** [comment]
@mtrezza tried multiple times restarting all tests but one or the order test flow keeps failing. Is there some way to restart only failing test cases?

**Comment by mtrezza** [comment]
Not sure if you can restart tests with your permissions. I can do that, so I'll just restart until they all pass.

**Comment by yog27ray** [comment]
@mtrezza thanks. Can this PR be reviewed now.

**Comment by mtrezza** [comment]
All the test pass, so that's good; let's just wait for another review and merge.

**Comment by yog27ray** [comment]
@mtrezza by when this PR can be merged and released?

**Review by dblythy — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.3](https://github.com/parse-community/parse-server/releases/tag/5.4.3)

**Pull request merged**
