### PR TITLE
added support for line auth

### PR DESCRIPTION
**Pull request by saimoomsafayet**
I have added support for Line's OAuth Authentication.

### CODE REVIEW

**Comment by dplewis** [comment]
Thanks for the PR. Can you add test cases and lint your code? npm run lint

**Comment by saimoomsafayet** [comment]
@dplewis I have modified authorization adapter's test to cover line's auth adapter inclusion. Let me know if anything needs to be done from my end.

**Comment by dplewis** [comment]
Can you improve the test coverage?

**Comment by saimoomsafayet** [comment]
> Can you improve the test coverage?

The code coverage of the edited/added codes seems alright. It is affecting other modules. Any insights about it?

**Pull request merged**
