### PR TITLE
Remove redundant checks for _User as it now uses ACL

### LINKED ISSUE #4647: ParseError {code: 206, message: "Cannot modify user FQrZUWcoW9."}
ParseError {code: 206, message: "Cannot modify user FQrZUWcoW9."}.

### Issue Description

ParseError {code: 206, message: "Cannot modify user FQrZUWcoW9."} when setting another user
even though set this ACL

### Steps to reproduce
In source code, I found these
```js
//RestWrite.js 975-979
if (this.className === '_User' &&
      this.query &&
      !this.auth.couldUpdateUserId(this.query.objectId)) {
    throw new Parse.Error(Parse.Error.SESSION_MISSING, `Cannot modify user ${this.query.objectId}.`);
  }
```
```js
//Auth.js 21-31

// Whether this auth could possibly modify the given user id.
// It still could be forbidden via ACLs even if this returns true.
Auth.prototype.couldUpdateUserId = function(userId) {
  if (this.isMaster) {
    return true;
  }
  if (this.user && this.user.id === userId) {
    return true;
  }
  return false;
};
```

#### Expected Results

What you expected to happen.

#### Actual Outcome

What is happening instead.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :2.7.2

### PR DESCRIPTION
**Pull request by mullwaden**
Fixes #4647

### CODE REVIEW

**Comment by mullwaden** [comment]
Would perhaps make sense to add a test to check that the user can not lock herself out by changing her ACL? Not sure how to go about it however

**Comment by flovilmart** [comment]
@mullwaden there are 3 tests failing, so obviously, you’re onto something. You can run your tests locally with `npm test`.

Also, i’m Not sure that all 3 tests should be removed.

**Comment by mullwaden** [comment]
Ah, rookie mistake... So the 3 errors in question: 

```
Parse.User testing cannot save non-authed user
  - Expected 101 to equal 206.

Parse.User testing cannot delete non-authed user
  - Expected 101 to equal 206.

Parse.User testing cannot saveAll with non-authed user
  - Expected 101 to equal 206.
```

For user there is a special case that when the ``Auth.prototype.couldUpdateUserId`` does not pass it returns 206, all other classes as far as I can tell return 101. Really hard for me to say of course, but to me it makes more sense to consistently return 101.

**Comment by aBuder** [comment]
@mullwaden Would this PR would accepted. Your solution would help me and let other users modify other users. I would hope 👍

**Comment by flovilmart** [comment]
@mullwaden sorry I dropped the ball on this one.

Can we add tests that ensure that the safeguards that were in place are still properly working? We removed some security checks so I'd like to be 100% sure that everything is still safe.

**Comment by aBuder** [comment]
@mullwaden Could you create some tests for it?

**Comment by mullwaden** [comment]
Bit unsure here, did we not come to the conclusion that it was probably not a good idea to make this change in #4789 ? One quick fix could then be to overwrite the setACL function on _User so that it prints a warning that ACL can't be used on the _User object.

**Comment by flovilmart** [comment]
We should add tests that by default users can’t be overwritten by another user, or worst by an unauthenticated call. Originally those were protected by code, now it isn’t. The last thing we want, is to have a publicly accessible and opened user table

**Pull request closed without merging**
