### PR TITLE
fix explain on user class

### PR DESCRIPTION
**Pull request by mtrezza**
fixes https://github.com/parse-community/parse-server/issues/6647

### CODE REVIEW

**Comment by mtrezza** [comment]
@acinader ready for review

**Comment by mtrezza** [comment]
Thanks!

**Comment by mess-lelouch** [comment]
Thanks for the fix! Any chance this change will make it to a hotfix soon?

**Comment by mtrezza** [comment]
@mess-lelouch The change will be part of the (regular) next release. Expect it to happen soon though, as it‘s been a month since the next release and the (informal) release cycle is somewhat monthly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mess-lelouch** [comment]
@mtrezza got it. Thanks!

**Pull request merged**
