### PR TITLE
Hotfix instagram api

### PR DESCRIPTION
**Pull request by timination**
https://github.com/parse-community/parse-server/issues/6728

change from old to new instagram API

### CODE REVIEW

**Comment by Moumouls** [comment]
thanks @timination can you please run `npm test` and fix/update tests for instagram auth 😃  
We cannot merge until all tests are ok 💯

**Comment by timination** [comment]
Sure, apologies I completely forgot about the test cases, they're updated now.

**Comment by Moumouls** [comment]
@timination currently it seems that instagram has 2 Apis for 2 different purposes
Currently on their docs it seems for auth that the old api.instagram is the correct one: https://developers.facebook.com/docs/instagram-basic-display-api/overview

Did you encounter some errors using api.instagram ?

**Comment by Moumouls** [comment]
@timination  it seems that the correct api call is here : https://developers.facebook.com/docs/instagram-basic-display-api/guides/getting-access-tokens-and-permissions

**Comment by timination** [comment]
No, just bug hunting on GitHub to make better use of my time. It was in response to https://github.com/parse-community/parse-server/issues/6728 this open bug issue, although looking at the current instagram/facebook documentation, the bug should be closed along with this PR. Thank you =)

**Comment by Moumouls** [comment]
So LGTM based on the docs here: https://developers.facebook.com/docs/instagram-basic-display-api/guides/getting-profiles-and-media

Did you test the URL on a local implementation ?

**Comment by Moumouls** [comment]
@timination

**Comment by Moumouls** [comment]
@timination can you push again your branch ?

**Comment by timination** [comment]
@Moumouls Should be back now

**Comment by timination** [comment]
oh dear, I hit re-open and travis CI is gonna fail again lol. I'm not sure why, though. I get many F's even from master branch when running `npm run coverage`. Strange.

**Review by Moumouls — APPROVED** [review]
LGTM thanks @timination  for your contribution :)

**Comment by Moumouls** [comment]
@timination our ci seems to have some instability and cod cov currently seems to not work properly, on another PR i added some new tests case and we got also a coverage decrease warning.

**Comment by Moumouls** [comment]
If you want to be sure about tests, the reopen ci action is currently running: https://github.com/parse-community/parse-server/pull/6922/checks?check_run_id=1194629325

**Comment by timination** [comment]
I'll check it out, thanks @Moumouls =)

**Pull request merged**
