### PR TITLE
build: Release

### PR DESCRIPTION
**Pull request by mtrezza**

### CODE REVIEW

**Comment by mtrezza** [comment]
This will be the last stable release for Parse Server 5 before it moves into LTS. This release happens ~2 weeks earlier than the expected release date Dec 1st, to free resources for Parse Server 6 release.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.31](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.31)

**Pull request merged**
