### PR TITLE
Added route to reset password with token

### PR DESCRIPTION
**Pull request by moonion**
Server side route for this pull request https://github.com/parse-community/Parse-SDK-JS/pull/716

Created to be able to use Parse function on client side to set new password for user that requested password reset, using token he receives by email.

### CODE REVIEW

**Comment by flovilmart** [comment]
The code is simply a copy / paste from a public route, therefore not needed.

**Comment by nashivan** [comment]
@flovilmart 

Sorry, I sent wrong code, I will fix and want to send my code.
Also I have  provided more information about my solution [link](https://github.com/parse-community/Parse-SDK-JS/pull/716#issuecomment-453122335)
Could you reopen pull request?

**Comment by moonion** [comment]
@flovilmart 

You can see changes there https://github.com/moonion/parse-server/pull/1/files

**Comment by flovilmart** [comment]
This is still wrong, if you need a different status code while resetting password, then do it on the PublicApiRouter module.

**Pull request closed without merging**
