### PR TITLE
CHANGELOG: typo fix braking->breaking [ci skip]

### PR DESCRIPTION
**Pull request by olleolleolle**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

This PR fixes a PR in the CHANGELOG.

Perhaps people are searching/scanning for "breaking", and with this change, they can find that line.

Related issue: (none)

### Approach

I edited on GitHub, with the pen icon, and added "CI skip", to make this a tiny change.

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for correcting my typo.

**Review by mtrezza — APPROVED** [review]
LGTM, spell correction, merging with 1 review.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
