### PR TITLE
refactor: test moved to correct test group

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

A variable named `ors` is used in #7593 which should probably be named `ands` to better represent what it's used for. In addition, the test case added is placed under the `sendEmail` tests which it should be placed under other `beforeFind` tests.

Related issue: #7714 

### Approach

Move the added test in the same category as other `beforeFind` tests. This will make debugging failures in the future easier. Replace variable names.

### TODOs before merging

- [x] Update tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by mtrezza** [comment]
For the record, as I understand from your [comment](https://github.com/parse-community/parse-server/issues/7714#issuecomment-978079315), this PR is merely a minor refactor and not related to #7714. Is this ready for merge?

**Comment by cbaker6** [comment]
It’s a minor refactor. I discovered these changes should be made while investigating 7714

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)

**Pull request merged**
