### PR TITLE
refactor: Upgrade semver from 7.3.8 to 7.5.0

### PR DESCRIPTION
**Pull request by parseplatformorg**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade semver from 7.3.8 to 7.5.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **2 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-04-17.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>semver</b></summary>
    <ul>
      <li>
        <b>7.5.0</b> - <a href="https://snyk.io/redirect/github/npm/node-semver/releases/tag/v7.5.0">2023-04-17</a></br><h2><a href="https://snyk.io/redirect/github/npm/node-semver/compare/v7.4.0...v7.5.0">7.5.0</a> (2023-04-17)</h2>
<h3>Features</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/503a4e52fe2b1c6ed1400d33149f7733c8361eed"><code>503a4e5</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/548" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/548/hovercard">#548</a> allow identifierBase to be false (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1664663102" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/548" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/548/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/548">#548</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/lsvalina/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/lsvalina">@ lsvalina</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/e219bb454036a0c23e34407591f921c8edb688e7"><code>e219bb4</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/552" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/552/hovercard">#552</a> throw on bad version with correct error message (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1668540369" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/552" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/552/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/552">#552</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/wraithgar/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/wraithgar">@ wraithgar</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/fc2f3df0b5d25253b3580607e111a9a280d888ca"><code>fc2f3df</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/546" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/546/hovercard">#546</a> incorrect results from diff sometimes with prerelease versions (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1663310560" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/546" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/546/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/546">#546</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/tjenkinson/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/tjenkinson">@ tjenkinson</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/27817677794f592b592bf6181a80a4824ff762b2"><code>2781767</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/547" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/547/hovercard">#547</a> avoid re-instantiating SemVer during diff compare (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1664004169" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/547" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/547/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/547">#547</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/macno/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/macno">@ macno</a>)</li>
</ul>
      </li>
      <li>
        <b>7.4.0</b> - <a href="https://snyk.io/redirect/github/npm/node-semver/releases/tag/v7.4.0">2023-04-10</a></br><h2><a href="https://snyk.io/redirect/github/npm/node-semver/compare/v7.3.8...v7.4.0">7.4.0</a> (2023-04-10)</h2>
<h3>Features</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/113f51312a1a6b6aa50d4f9486b4fde21782c1f5"><code>113f513</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/532" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/532/hovercard">#532</a> identifierBase parameter for .inc (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1656423851" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/532" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/532/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/532">#532</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/wraithgar/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/wraithgar">@ wraithgar</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/b-bly/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/b-bly">@ b-bly</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/48d8f8fa63bf6e35db70ff840b6da1a51596a5a8"><code>48d8f8f</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/530" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/530/hovercard">#530</a> export new RELEASE_TYPES constant (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/hcharley/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/hcharley">@ hcharley</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/940723d22bca824993627c45ac30dd3d2854b8cd"><code>940723d</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/538" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/538/hovercard">#538</a> intersects with v0.0.0 and v0.0.0-0 (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658181254" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/538" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/538/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/538">#538</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/wraithgar/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/wraithgar">@ wraithgar</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/aa516b50b32f5a144017d8fc1b9efe0540963c91"><code>aa516b5</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/535" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/535/hovercard">#535</a> faster parse options (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1656582318" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/535" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/535/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/535">#535</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/H4ad/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/H4ad">@ H4ad</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/61e6ea1e9b7af01baf19ab0c0a63c8e3ebfac97c"><code>61e6ea1</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/536" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/536/hovercard">#536</a> faster cache key factory for range (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1656603827" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/536" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/536/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/536">#536</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/H4ad/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/H4ad">@ H4ad</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/f8b8b619e71746a47852a9d301f3087ab311444f"><code>f8b8b61</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/541" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/541/hovercard">#541</a> optimistic parse (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658229988" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/541" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/541/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/541">#541</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/H4ad/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/H4ad">@ H4ad</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/796cbe29b06d102e1b16f3ed78eaba210ece951e"><code>796cbe2</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/533" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/533/hovercard">#533</a> semver.diff prerelease to release recognition (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1656439533" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/533" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/533/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/533">#533</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/wraithgar/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/wraithgar">@ wraithgar</a>, <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/dominique-blockchain/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/dominique-blockchain">@ dominique-blockchain</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/3f222b144033525ca9f8a2ce5bc6e02f0401881f"><code>3f222b1</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/537" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/537/hovercard">#537</a> reuse comparators on subset (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658176606" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/537" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/537/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/537">#537</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/H4ad/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/H4ad">@ H4ad</a>)</li>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/f66cc45c6e82eebb4b5b51af73e7b8dcaeda7e21"><code>f66cc45</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/539" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/539/hovercard">#539</a> faster diff (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1658213383" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/539" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/539/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/539">#539</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/H4ad/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/H4ad">@ H4ad</a>)</li>
</ul>
<h3>Documentation</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/c5d29df6f75741fea27fffe3b88c9c3b28e3ca73"><code>c5d29df</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/530" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/530/hovercard">#530</a> Add "Constants" section to README (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/hcharley/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/hcharley">@ hcharley</a>)</li>
</ul>
      </li>
      <li>
        <b>7.3.8</b> - <a href="https://snyk.io/redirect/github/npm/node-semver/releases/tag/v7.3.8">2022-10-04</a></br><h2><a href="https://snyk.io/redirect/github/npm/node-semver/compare/v7.3.7...v7.3.8">7.3.8</a> (2022-10-04)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/d8ef32cee7a7e34310838f32451c9bcf52956b64"><code>d8ef32c</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/383" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/383/hovercard">#383</a> add support for node.js esm auto exports (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="891095680" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/383" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/383/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/383">#383</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/MylesBorins/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/MylesBorins">@ MylesBorins</a>)</li>
</ul>
<h3>Documentation</h3>
<ul>
<li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/7209b14ccd7ca35b9a1077a0b67d9ce884fe6d00"><code>7209b14</code></a> <a href="https://snyk.io/redirect/github/npm/node-semver/pull/477" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/477/hovercard">#477</a> update range.js comments to clarify the caret ranges examples (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1364336753" data-permission-text="Title is private" data-url="https://github.com/npm/node-semver/issues/477" data-hovercard-type="pull_request" data-hovercard-url="/npm/node-semver/pull/477/hovercard" href="https://snyk.io/redirect/github/npm/node-semver/pull/477">#477</a>) (<a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/amitse/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/amitse">@ amitse</a>)</li>
</ul>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/npm/node-semver/releases">semver GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>semver</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/5b02ad7163a3ddcbcadf499e4f6195d6f2226dce">5b02ad7</a> chore: release 7.5.0</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/e219bb454036a0c23e34407591f921c8edb688e7">e219bb4</a> fix: throw on bad version with correct error message (#552)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/503a4e52fe2b1c6ed1400d33149f7733c8361eed">503a4e5</a> feat: allow identifierBase to be false (#548)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/fc2f3df0b5d25253b3580607e111a9a280d888ca">fc2f3df</a> fix: incorrect results from diff sometimes with prerelease versions (#546)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/27817677794f592b592bf6181a80a4824ff762b2">2781767</a> fix: avoid re-instantiating SemVer during diff compare (#547)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/82aa7f62617d445f578584543565329a62343aab">82aa7f6</a> chore: release 7.4.0</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/731d896bf4d1c9905d845220da7da3060e6359f9">731d896</a> chore: enable CD (#545)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/940723d22bca824993627c45ac30dd3d2854b8cd">940723d</a> fix: intersects with v0.0.0 and v0.0.0-0 (#538)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/aa516b50b32f5a144017d8fc1b9efe0540963c91">aa516b5</a> fix: faster parse options (#535)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/61e6ea1e9b7af01baf19ab0c0a63c8e3ebfac97c">61e6ea1</a> fix: faster cache key factory for range (#536)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/f8b8b619e71746a47852a9d301f3087ab311444f">f8b8b61</a> fix: optimistic parse (#541)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/796cbe29b06d102e1b16f3ed78eaba210ece951e">796cbe2</a> fix: semver.diff prerelease to release recognition (#533)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/3f222b144033525ca9f8a2ce5bc6e02f0401881f">3f222b1</a> fix: reuse comparators on subset (#537)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/113f51312a1a6b6aa50d4f9486b4fde21782c1f5">113f513</a> feat: identifierBase parameter for .inc (#532)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/ea689bcbf134bd01d4cb7557ffef620b4e7357d4">ea689bc</a> chore: basic type test for RELEASE_TYPES</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/c5d29df6f75741fea27fffe3b88c9c3b28e3ca73">c5d29df</a> docs: Add &quot;Constants&quot; section to README</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/48d8f8fa63bf6e35db70ff840b6da1a51596a5a8">48d8f8f</a> feat: export new RELEASE_TYPES constant</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/f66cc45c6e82eebb4b5b51af73e7b8dcaeda7e21">f66cc45</a> fix: faster diff (#539)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/f4fa069c9304b847a5083cf77c2ea7c568692ab8">f4fa069</a> chore: bump @ npmcli/template-oss from 4.12.0 to 4.13.0 (#531)</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/da08e01cd96f9d70a8b4fbc7dc3f69eef930f67a">da08e01</a> chore: postinstall for dependabot template-oss PR</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/5f8eb660502141261030c40531680758b2abe3bd">5f8eb66</a> chore: bump @ npmcli/template-oss from 4.11.4 to 4.12.0</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/8f11f7ccff471b33da701c5a307300bacee64c1d">8f11f7c</a> chore: postinstall for dependabot template-oss PR</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/344f316921b0ef729fb351f08e634e80e8db8334">344f316</a> chore: bump @ npmcli/template-oss from 4.11.3 to 4.11.4</li>
      <li><a href="https://snyk.io/redirect/github/npm/node-semver/commit/bdda212f4f6126a1b8821dc0731a17fdc2fc533f">bdda212</a> chore: postinstall for dependabot template-oss PR</li>
    </ul>

   <a href="https://snyk.io/redirect/github/npm/node-semver/compare/dc0fe202faaf19a545ce5eeab3480be84180a082...5b02ad7163a3ddcbcadf499e4f6195d6f2226dce">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?pkg&#x3D;semver&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
