### PR TITLE
Support pointer in distinct query

### PR DESCRIPTION
**Pull request by dplewis**
Per https://github.com/parse-community/parse-server/issues/2238#issuecomment-353487687

Let me know if theres a better way to implement this.

### CODE REVIEW

**Comment by flovilmart** [comment]
@dplewis The `mongoObjectToParseObject` method should already transform the pointers, perhaps just extract the logic: https://github.com/parse-community/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoTransform.js#L1133

**Comment by dplewis** [comment]
@flovilmart I extracted the logic because distinct returns a string like 'TestObject$ObjectId' which returns here. https://github.com/parse-community/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoTransform.js#L1024

**Comment by flovilmart** [comment]
Yeah, I mean what you can do is make a `transformPointerString` method in the `MongoTransform.js` module and use it at both places.

**Comment by vitaly-t** [comment]
I generally do not like this line:

`.catch(() => [])`

It is dangerous, swallowing all possible errors like that.

Also, I would replace this block:

```js
let qs = `SELECT DISTINCT ON ($1:raw) $2:raw FROM $3:name ${wherePattern}`;
if (isArrayField) {
   qs = `SELECT distinct jsonb_array_elements($1:raw) as $2:raw FROM $3:name ${wherePattern}`;
}
```
with this one:
```js
const transformer = isArrayField ? 'jsonb_array_elements': '';
let qs = `SELECT DISTINCT ON ${transformer}($1:raw) $2:raw FROM $3:name ${wherePattern}`;
```

**Comment by dplewis** [comment]
Interesting I omitted AS and it still worked.

`SELECT DISTINCT ${transformer}($1:raw) AS $2:raw FROM $3:name ${wherePattern}`

pushed-to-repo-travis-ci-build-passed

**Comment by vitaly-t** [comment]
Can't see which PR made this one out-of-date, but requested a branch update, since it is required.

**Comment by dplewis** [comment]
There were a lot of node packages that were merged

**Comment by srameshr** [comment]
@dplewis Does not work for me.
```
const query = new Parse.Query('MyClass');
query.include('content');
query.distinct('content.objectId');
query.find();
```
It just returns records with duplcation collection

**Comment by flovilmart** [comment]
Well, the single unit test that is exactly what you describe passes. So open a an issue with the full details as well as code examples and relevant logs

**Comment by dplewis** [comment]
Do your objects have a field called “content.objectId”?

**Comment by srameshr** [comment]
```content``` is a pointer field on ```MyClass```. I need to fetch records with unique ```content``` pointer field.

**Comment by flovilmart** [comment]
well @srameshr did you read the test file [here](https://github.com/parse-community/parse-server/pull/4471/files#diff-8e77c0ebc3608e43aefc6e9e9912e3d7R403)

because what you're doing isn't how it's supposed to be used.

**Comment by srameshr** [comment]
@flovilmart ```query.distinct('pointer')``` assuming ```pointer``` is the field name, so for me, the query would be ```query.distinct('content')```, cos ```content``` is my field name. Even this did not work and also am I missing something?

**Comment by flovilmart** [comment]
did you notice that in the test it is:

```
const query = new Parse.Query(TestObject);
query.distinct('pointer').then((results) => {

});
``` 

and in your example:

```
const query = new Parse.Query('MyClass');
query.include('content');
query.distinct('content.objectId');
query.find();
```

Well if you don't see the differences now, I'm not sure how to help you.

**Comment by srameshr** [comment]
Shit, ok got it. ```.distinct``` returns a promise with distinct values. My bad.

**Comment by flovilmart** [comment]
Well, that's what's written in the test file. Next time consider reading what the maintainers share as well as perhpas the docs: https://docs.parseplatform.org/js/guide/#distinct

**Comment by srameshr** [comment]
I heard you the first time.

**Pull request merged**
