### PR TITLE
Need a Shutdown Function for PostgresAdapter.

### PR DESCRIPTION
**Pull request by trylovetom**
Add Postgres `handleShutdown` Function

### CODE REVIEW

**Comment by trylovetom** [comment]
What!!
I use the same code in ci testing. CI give two different result.
What happened?

**Comment by steven-supersolid** [comment]
For some reason another change in meetup.js is being considered - perhaps your branch is not up to date with master?

**Comment by trylovetom** [comment]
@steven-supersolid Really? I have been rebase to the latest master.

**Comment by flovilmart** [comment]
You should probably run the tests locally, before opening the PR, as it’s notifying all maintainers.

**Comment by trylovetom** [comment]
@flovilmart How can I switch the db of testing to postgres, please. I really need this feature.

**Comment by flovilmart** [comment]
PLease read the contributing guide https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md

**Comment by trylovetom** [comment]
@flovilmart thx

**Comment by trylovetom** [comment]
@flovilmart I need help, I wrote the testing code of `handleShutdown()`. But I didn't know how to test it correctly. Can you give me some tips?

**Comment by flovilmart** [comment]
To test the code locally with postures, you need postgres 9.5.
then you'll need to setup a few things as PostGis extensions and the test DB:

```
$ psql -c 'create database parse_server_postgres_adapter_test_database;' -U postgres
$ psql -c 'CREATE EXTENSION postgis;' -U postgres -d parse_server_postgres_adapter_test_database
$ psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d parse_server_postgres_adapter_test_database
```

Then to run the tests:

```
$ PARSE_SERVER_TEST_DB=postgres npm test
```

**Pull request closed without merging**
