### PR TITLE
fix: Rate limiter may reject requests that contain a session token

### LINKED ISSUE #8398: Rate limiter can fail if `request.auth` is undefined
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When using a rate limiter, the rate limiter can fail when `request.auth` is undefined. This can lead the rate limiter to reject all requests.

### Steps to reproduce

Create a rate limiter and attempt to connect with auth

### Actual Outcome

Rate limiter rejects all requests

### Expected Outcome

Rate limiter passes

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Rate limiter can reject requests if any error is thrown in the rate limit handler, which can lead to server rejecting requests when it shouldn't. First commit is a failing test that demonstrates this occurring with rateLimit requests with a `sessionToken`.

Closes: #8398

### Approach

Adds a check to make sure that the rate limiter only rejects requests if the error is the right one.

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
> Rate limiter can reject requests if any error is thrown in the rate limit handler, which can lead to server rejecting requests when it shouldn't. 

In which cases for example could an error be thrown in the rate limit handler?

**Comment by dblythy** [comment]
Any request with a session token. There weren't any test with auth, so it wasn't caught.

**Review by mtrezza — APPROVED** [review]
Looks good! Is this ready to merge?

**Comment by dblythy** [comment]
Yep!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.28](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.28)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
