### PR TITLE
using per-key basis queue

### PR DESCRIPTION
**Pull request by georgesjamous**
Currently, the RedisCacheAdapter uses a global promise queue chain to handle redis cache operations.
https://github.com/parse-community/parse-server/blob/f798a60475eb37210ac93f4c100f0c36ed280ab5/src/Adapters/Cache/RedisCacheAdapter.js#L19
This produces a bottleneck point and causes several problems during high requests such as timeouts and delays since all cache operations are chained and depend on each other. As discussed in this ticket https://github.com/parse-community/parse-server/issues/5401
I believe that initially it was designed that way to allow maximum data consistency and prevent operations from overlapping.

A potential solution would be to chain the cache operations per key basis, that way consistency _on-key-basis_ is maintained and that would allow parallel operations to be invoked, which would loosen up the single bottleneck point.

I have used a custom _KeyPromiseQueue_ class as opposed to the built-in MemoryCache since ttl should not be used because expiring active operations would mean the next ones would not be chained (since the previous ones are not tracked anymore) and data consistency would be lost again. Which is our main concern here, otherwise we would not use any chain.

----

Any thoughts or concerns on such modification?

### CODE REVIEW

**Comment by saulogt** [comment]
Nice work!
I saw you dropped the idea of the lru cache... It produced a much more predictable code 👍 

I have two humble suggestions for your PR:
1) Use a single object to keep track of both count and promise chain. 
2) Replace the raw object by a `Map` to keep track o them for performance reason (mainly on delete)

Maybe something like this:
```js
  beforeOp(key) {
    let obj = this.queues.get(key);
    if (!obj) {
      obj = [0, Promise.resolve()];
      this.queues.set(key, obj);
    }
    obj[0]++;
  }

  afterOp(key, obj) {
    let count = obj[0];
    if (count === undefined) {
      return;
    }
    count--;
    if (count <= 0) {
      this.queues.delete(key);
      return;
    }
    obj[0] = count;
  }

  enqueue(key, operation) {
    let obj = this.beforeOp(key);
    const toAwait = obj[1];
    const nextOperation = toAwait.then(operation);
    const wrappedOperation = nextOperation.then(result => {
      this.afterOp(key, obj);
      return result;
    });
    obj[1] = wrappedOperation;
    return wrappedOperation;
  }
```

**Comment by georgesjamous** [comment]
@saulogt  I have modified the code reflecting your suggestions, you're right using one object is cleaner and faster, let me know what you think.

**Comment by saulogt** [comment]
@georgesjamous It looks great

**Comment by acinader** [comment]
@georgesjamous can you take a look at: https://codecov.io/gh/parse-community/parse-server/compare/8622e5c3788bf1c072e7ba1efba06b77f54ac702...63618a5ce65ca5317ee413331c8eebdacb49b196/diff

**Comment by georgesjamous** [comment]
Travis check has passed but for some reason, it's not being updated in the PR. Is there a way to restart the test without a commit?

@acinader I don't use codecov much, can you be a little bit more specific?

**Comment by dplewis** [comment]
@georgesjamous This PR looks great.

I've restarted the test for you. If you want to restart it just close and reopen the PR.

Codecov shows which parts of your code haven't been tested. The goal is to have as much tested as possible to avoid regression.

Use `npm run coverage`.

Also, I noticed you moved the RedisCacheAdapter which lead to all the history being deleted. You can get around it with tags but we've had this in the past.

**Comment by georgesjamous** [comment]
Alright, I have added additional tests and made some minor alterations.

**Comment by georgesjamous** [comment]
@acinader @dplewis this is ready to be merged I guess.
I am not sure who is currently accepting PRs, I have tagged you both.

**Pull request merged**
