### PR TITLE
refactor: Upgrade @babel/eslint-parser from 7.19.1 to 7.21.8

### PR DESCRIPTION
**Pull request by parseplatformorg**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade @babel/eslint-parser from 7.19.1 to 7.21.8.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **7 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-05-02.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>@babel/eslint-parser</b></summary>
    <ul>
      <li>
        <b>7.21.8</b> - <a href="https://snyk.io/redirect/github/babel/babel/releases/tag/v7.21.8">2023-05-02</a></br><h2>v7.21.8 (2023-05-02)</h2>
<h4><g-emoji class="g-emoji" alias="eyeglasses" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f453.png">👓</g-emoji> Spec Compliance</h4>
<ul>
<li><code>babel-parser</code>
<ul>
<li><a href="https://snyk.io/redirect/github/babel/babel/pull/15602" data-hovercard-type="pull_request" data-hovercard-url="/babel/babel/pull/15602/hovercard">#15602</a> Remove <code>using await</code> restriction in explicitResourceManagement (<a href="https://snyk.io/redirect/github/JLHwung">@ JLHwung</a>)</li>
</ul>
</li>
</ul>
<h4><g-emoji class="g-emoji" alias="bug" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f41b.png">🐛</g-emoji> Bug Fix</h4>
<ul>
<li><code>babel-helper-create-class-features-plugin</code>, <code>babel-helper-create-regexp-features-plugin</code>
<ul>
<li><a href="https://snyk.io/redirect/github/babel/babel/pull/15605" data-hovercard-type="pull_request" data-hovercard-url="/babel/babel/pull/15605/hovercard">#15605</a> Fix backward compat for semver checks in class&amp;regexp feat plugins (<a href="https://snyk.io/redirect/github/nicolo-ribaudo">@ nicolo-ribaudo</a>)</li>
</ul>
</li>
</ul>
<h4>Committers: 2</h4>
<ul>
<li>Huáng Jùnliàng (<a href="https://snyk.io/redirect/github/JLHwung">@ JLHwung</a>)</li>
<li>Nicolò Ribaudo (<a href="https://snyk.io/redirect/github/nicolo-ribaudo">@ nicolo-ribaudo</a>)</li>
</ul>
      </li>
      <li>
        <b>7.21.4-esm.4</b> - 2023-04-04
      </li>
      <li>
        <b>7.21.4-esm.3</b> - 2023-04-04
      </li>
      <li>
        <b>7.21.4-esm.2</b> - 2023-04-04
      </li>
      <li>
        <b>7.21.4-esm.1</b> - 2023-04-04
      </li>
      <li>
        <b>7.21.4-esm</b> - 2023-04-04
      </li>
      <li>
        <b>7.21.3</b> - 2023-03-14
      </li>
      <li>
        <b>7.19.1</b> - 2022-09-14
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/babel/babel/releases">@babel/eslint-parser GitHub release notes</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?pkg&#x3D;@babel/eslint-parser&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
