### PR TITLE
fix: custom database options are not passed to MongoDB GridFS

### LINKED ISSUE #7910: mongoOptions aren't passed to GridFSBucketAdapter
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

If you are using custom `databaseOptions` in your Parse Server options (such as `sslKey`), the default GridFS file storage stops working.

### Steps to reproduce

Create a Parse Server with `databaseOptions`, using a mongoDB with certificate auth. Attempt to save a file..

### Actual Outcome

Certificate validation fails

### Expected Outcome

Files to save

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

If you have custom mongoDB options, they are not passed to the default file controller.

Related issue: #7910

### Approach

Passes databaseOptions to default file controller

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
I changed the title as it should describe what is broken. does the new title sum it up?

**Comment by dblythy** [comment]
Yep!

**Comment by dblythy** [comment]
Well, on second thought I don't know if _fails_ is the right word. If you are using sslKey/sslCert it will fail, but if it's another option such as `retryWrites` that doesn't impede the connection, then the file will still save

**Comment by mtrezza** [comment]
So the issue is related only to the ssl options? In that case can you rewrite the title to be more specific? When reading the changelog, a developer should easily identify whether that is something that affects them.

**Comment by dblythy** [comment]
Well the SSL options are meant to be a path of a .pem key, which I can’t replicate in testing (due to needing a SSL pem). This issue was that databaseOptions weren’t being passed, which is what this PR fixes

**Comment by mtrezza** [comment]
So what should the PR title be to cover the whole issue that this PR fixes?

**Comment by mtrezza** [comment]
Looks good to merge, once the tests pass

**Review by mtrezza — APPROVED** [review]

**Review by Moumouls — APPROVED** [review]
LGTM

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.4](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.4)

**Comment by dblythy** [comment]
Thanks all!

**Pull request merged**
