### PR TITLE
fix context for cascade-saving and saving existing object

### PR DESCRIPTION
**Pull request by mtrezza**
Fixes issues with `context` when saving objects:

1. Fixes issue that no `context` is set when saving an existing object:
```
const obj = new Parse.Object("TestObject");
await obj.save(null);
await obj.save(null, { context: { a: 'a' } });
```

2. Fixes issue that `context` is lost when cascade-saving objects so that `context` is inherited by child objects (`obj2` in this example):
```
const obj = new Parse.Object("TestObject");
const obj2 = new Parse.Object("TestObject2");
obj.set("obj2", obj2);
await obj.save(null, { context: { a: 'a' } });
```

**Requires:**
- [x] Changes in Parse JS SDK https://github.com/parse-community/Parse-SDK-JS/pull/1186

closes https://github.com/parse-community/parse-server/issues/6736

### CODE REVIEW

**Comment by dplewis** [comment]
Thanks for bumping the SDK, I was waiting for the PR from Synx. Can you run npm install to update the package lock?

**Comment by mtrezza** [comment]
Yes, it's already running. I gotta head out now, if CI fails I'll take a look at it in a couple of hours.

**Comment by dplewis** [comment]
It looks good to me, can you remove the comments that aren’t self documenting?

**Comment by mtrezza** [comment]
You mean these `// Save object` comments and alike in the tests ?

**Comment by mtrezza** [comment]
Looks like a false positive in coverage, ready to merge.

**Pull request merged**
