### PR TITLE
Feat: Add dashboard router to store Dashboard User Settings

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Currently, creating a Parse Server user has to be done via command line.

Related issue: #7479

### Approach

Creates endpoint to signup and login as a dashboard user. This would have to be implemented in the dashboard. Would also allow features per user, beforeDashboardLogin hooks, etc.

Draft PR to get thoughts before I work on Dashboard implementation.

### TODOs before merging

- [x] Add test cases
- [ ] Add entry to changelog

### CODE REVIEW

**Comment by dblythy** [comment]
Related: https://github.com/parse-community/parse-dashboard/issues/1618

**Comment by dblythy** [comment]
I'm thinking with our focus on security for V5, it could be good to have a `beforeDashboardLogin` trigger that can allow a developer can add their own auth flow to dashboard logins

**Comment by mtrezza** [comment]
Do we need an own trigger for that, or should dashboard login be handled the same (and invoke the same triggers) as any other user login?

**Comment by dblythy** [comment]
I would propose a different trigger, as a dashboard user would have different column requirements and completely handling to a Parse Server user.

**Comment by mtrezza** [comment]
What do you mean by column requirements?

**Comment by dblythy** [comment]
Well if you're using the default login flow, any user that could login to your app, could log into your dashboard. Which i'm not sure is a desired outcome.

I meant dashboard specific user settings, such as MFA secret, features, etc. But I guess they could be stored in a different collection as a pointer.

**Comment by mtrezza** [comment]
> Well if you're using the default login flow, any user that could login to your app, could log into your dashboard. Which i'm not sure is a desired outcome.

Not necessarily, I was referring only to the trigger usage. If we found a way to reuse existing auth triggers, we wouldn't have to duplicate triggers just for dashboard.

> From a triggers perspective, how would a developer be able to differentiate between an admin logging in to the dashboard, vs the app? Perhaps req.dashboard?

Yes, we can add a parameter to identify it. Maybe we can look at this in context of privacy compliant logging. A topic that we will soon have to pick up to keep the dashboard a practical tool for production applications. There we will probably want to identify a client (dashboard, admin app, etc) by a UUID. Passing such a UUID can allow the dev to identify not only the dashboard but any app. Currently, a dev can only differentiate by user, indifferent of where the user signs in. 

> I meant dashboard specific user settings, such as MFA secret, features, etc. But I guess they could be stored in a different collection as a pointer.

If we move the dashboard user auth process to the server side, there may be good reasons to not build a parallel auth system with distinct rules. The dashboard can be treated as just one app. Users can be grouped with roles. It seems we have everything there.

**Pull request closed without merging**
