### PR TITLE
feat: Upgrade to Parse JS SDK 5

### LINKED ISSUE #8818: Upgrade to latest Parse SDK breaks test
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Upgrading to latest Parse SDK (4.3.1 as of writing) breaks the test:

> 1) Security Advisory GHSA-8w3j-g983-8jh5 should validate credentials first and check if account already linked afterwards ()
>   - Expected 208 to equal 206.

The test specifically expects 206 instead of 208 (as commented in the test), so it doesn't seem to be a deliberate change but rather a bug.

### Steps to reproduce

See https://github.com/parse-community/parse-server/pull/8816.

### Actual Outcome

Test fails.

### Expected Outcome

Test passes.

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Upgrade parse to 5 alpha; needs to be upgrade to stable release version of parse js sdk before parse server beta release

Closes: https://github.com/parse-community/parse-server/issues/8818

### CODE REVIEW

**Comment by mtrezza** [comment]
This is amazing! Thanks a bunch for solving this 🙌

**Comment by dblythy** [comment]
No worries, I'm not sure if this introduces a breaking change, but all tests are passing so I think it's ok

**Comment by mtrezza** [comment]
Noted; we'll release this with Parse Server 5 anyway, so we can assume developers will test before a major upgrade. Finally we can make that release. So this PR is good to merge?

**Comment by mtrezza** [comment]
Note: Before merging, we'll make a stable release of Parse JS SDK 5 and update this PR to use the stable release.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.28](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.28)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
