### PR TITLE
fix: Deny requests for ip restricted master keys

### LINKED ISSUE #8829: Server logs master key error even if it has been not used
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

If `masterKeyIps` is defined and I try to access data in a public class via REST API and if the request has `X-Parse-Master-Key` header then the server returns the needed response but also logs this error `error: Request using master key rejected as the request IP address '::1' is not set in Parse Server option 'masterKeyIps'.`

Request (Has Master-Key header) ->(Tries to access a public class) -> Server (Gives response but logs error for IP is not allowed for masterKey)

Request (Has Master-Key header) ->(Tries to access a masterKey only class) -> Server (denies and logs error for IP is not allowed for masterKey)

### Steps to reproduce

Set your `masterKeyIps` , add X-Parse-Master-Key to your header in the request and try to access a public class

### Actual Outcome

`error: Request using master key rejected as the request IP address '::1' is not set in Parse Server option 'masterKeyIps'.`

### Expected Outcome

Server should not log that since I was not trying to use Master Key for my operation cause it was a access request to a public class data

### Environment

"dependencies": {
    "axios": "1.6.0",
    "dotenv": "^16.3.1",
    "express": "4.18.2",
    "ip-range-check": "^0.2.0",
    "parse": "4.1.0",
    "parse-server": "6.3.1"
  }

Server
- Parse Server version: `6.3.1`
- Operating system: `Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Localhost`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `7.0.3`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `REST API`
- SDK version: `None`

### Logs

`error: Request using master key rejected as the request IP address '::1' is not set in Parse Server option 'masterKeyIps'.`

### PR DESCRIPTION
**Pull request by suathh**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues/8829).

## Issue
[](https://github.com/parse-community/parse-server/issues/8829)

Closes: #8829 

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by mtrezza** [comment]
@suathh Tests are failing, could you please take a look?

**Comment by suathh** [comment]
@mtrezza Most of the fails are because of the update we are doing.

The test fails with these lines 

- Error: Access denied: IP address '127.0.0.1' is not authorized to use the master key.

Denial of Master Key 2
Denial of Master Key


But one test has a different problem which is the Node v14 test, it is timeout for live query

Timeout

**Comment by mtrezza** [comment]
What do you suggest as solution?

**Comment by suathh** [comment]
At this point, I need to check what those failing tests stand for and what they are doing. It would be better to take advice or help from the test creators or someone who knows what they stand for.

But as an oversight, what I see from error logs;

1. We need to add local IP addresses to our Parse-Server config for our tests. In this case `127.0.0.1` but that won't work if the test env running on an IPv6 env.
2. Update the tests according to our breaking change
3. Remove the failing tests cause they are trying to test a breaking change but this will eventually lead to step 2

**Comment by EhsanParsania** [comment]
I have fixed the test cases that were related to this current change, there are still more failed tests are exist but they are unrelated to this change, please give me Write access to this pull request so I can push my commit @suathh @mtrezza

**Comment by mtrezza** [comment]
Superseded by https://github.com/parse-community/parse-server/pull/8957

**Pull request closed without merging**
