### PR TITLE
refactor: Upgrade pg-promise from 11.3.0 to 11.5.0

### LINKED ISSUE #8587: Pg-promise is out-of-date
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The dependencies pg-promise is not up-to-date and the node-postgres driver pg-promise depends on is out-of-date. 

### Feature / Enhancement Description

Update to the latest versions.

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

The dependencies pg-promise is not up-to-date and the node-postgres driver pg-promise depends on is out-of-date. For some reason, these are not being updated by the dependency bot or the snyk bot

Closes: #8587 

## Approach

Update the dependencies using `npm i -E pg-promise@11.5.0`.

## Tasks

- [x] Ensure tests pass

### CODE REVIEW

**Comment by cbaker6** [comment]
#8511 seems to have consistently failed a test in the suite which can be seen as a failure in multiple postgres versions [original PR failure](https://github.com/parse-community/parse-server/actions/runs/5104054659/jobs/9174714851#step:8:5044) and [alpha branch failure](https://github.com/parse-community/parse-server/actions/runs/5105446713/jobs/9177043726?pr=8586#step:8:5045) with:

```bash
1) InstallationsRouter query installations with count = 1
  - Expected 0 to equal 2.
```

I've checked the test and it seems like the original way returned an accurate value.

Should that PR be reverted until it's fixed as it never passed CI in the first place? cc: @mtrezza @dblythy

**Comment by cbaker6** [comment]
I'm not sure why there's a definitions check failure as I didn't touch any definitions. I ran the line it suggests, but it generates no changes in my local repo to commit.

**Comment by mtrezza** [comment]
Definitions is flaky, see https://github.com/parse-community/parse-server/issues/8579.

#8511 should fix https://github.com/parse-community/parse-server/issues/8502, which seems to be an issue others can replicate. If the fix introduces new issues we can revert it. https://github.com/parse-community/parse-server/pull/8588

**Comment by cbaker6** [comment]
> https://github.com/parse-community/parse-server/pull/8511 should fix https://github.com/parse-community/parse-server/issues/8502, which seems to be an issue others can replicate. If the fix introduces new issues we can revert it.

I don't see the issue the others have reported (screenshot below, Parse Dashboard v5.1.0, Postgres 15-3.3). The count query used in the Dashboard is intended to be an estimate due to Postgres counting being expensive/slow (the [Postgres wiki](https://wiki.postgresql.org/wiki/Count_estimate) suggests something similar to the original parse-server implementation for count). It looks like the devs reporting the issue all have small amounts of rows in their tables which can easily be estimated to zero by Postgres. In addition, if a fix is suggested, I believe it should follow the process of any other PR, it should: 
1. Introduce a test to prove it works (#8511 didn't do this)
2. Not break other tests (#8511 broke a test). If the PR creator believes the test is incorrect, they should justify why it's incorrect and provide a fix for the test. From what I can see, the original test is correct and matches the response value for the equivalent mongo test which is right above it in the same file. 

image

I believe the PR should be reverted and the creator of the PR should continue to work on it. Even if a change is made, the adjustments in PR 8511 are still `estimates`, meaning they won't be exact either. The broken test is below for reference: https://github.com/parse-community/parse-server/blob/6c5f89a56bf21609818b8aac7c55137101f8c62f/spec/InstallationsRouter.spec.js#L169-L203

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
