### PR TITLE
Add warning in changelog regarding upgrade to 4.0 and index creation

### PR DESCRIPTION
**Pull request by acinader**
fixes: #6464

### CODE REVIEW

**Comment by TomWFox** [comment]
Could we not just update the changelog and release notes instead of creating a new release?

**Comment by acinader** [comment]
¯\_(ツ)_/¯

**Comment by TomWFox** [comment]
It’s possible, seems like an easier solution to me?

**Comment by acinader** [comment]
at this point, it's easier for __me__ to just release this if you think the wording is good and correct.

having said that, i'm glad to close this and you can do as you see fit and I'd be just as happy with that!

:).  and thanks for the prompt review and responses.  much appreciated as always.

**Comment by TomWFox** [comment]
Fair enough, I feel that it could be confusing to create a new release even though the change is in a previous one.

I’m happy to apply my suggestions in this PR and then update the release notes accordingly.

**Comment by TomWFox** [comment]
I know you can't add a review, but does this look ok to you?

**Comment by acinader** [comment]
@TomWFox that looks great.  Let 'er rip.  I really appreciate it.

**Comment by TomWFox** [comment]
No worries, you did most real work, nicely written!

**Pull request merged**
