### PR TITLE
feat: Add support for Postgres 16

### LINKED ISSUE #8899: Add official support for Postgres 16
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

[Postgres 16](https://www.postgresql.org/about/press/presskit16/en/#original_release) was released 9/19/23.

### Feature / Enhancement Description

It should be added to the CI to test compatibility.

### Example Use Case

Developer wants to use Postgres 16 with Parse.

### Alternatives / Workarounds

Use older versions of Postgres.

### 3rd Party References

N/A

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8899 

## Tasks

- [x] Ensure CI passes
- [x] Add changes to documentation (guides, repository pages, code comments)
- [x] Update repo branch settings with new Postgres requirements and delete old requirements

### CODE REVIEW

**Comment by cbaker6** [comment]
This is ready for review...

Before merging you will need to update the branch settings by adding the new Postgres CI names as `required` and removing the old names

**Review by mtrezza — COMMENTED** [review]
Thanks for the PR; looks good! Deleted my previous comment, that README table looks confusing. Waiting for CI to pass...

Commit message:

> feat: Add support for Postgres 16
> BREAKING CHANGE: Removes support for Postgres 11 and 12

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.11](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
