### PR TITLE
fix(package): update pg-promise to version 6.7.0

### PR DESCRIPTION
**Pull request by flovilmart**
Closes #4160

### CODE REVIEW

**Comment by flovilmart** [comment]
@vitaly-t it seems that this pg-promise / manakin has an issue with node 8 https://travis-ci.org/parse-community/parse-server/jobs/276402315

**Comment by vitaly-t** [comment]
Can't be. Manakin works in all Node.js version and hasn't been changed in a while: https://travis-ci.org/vitaly-t/manakin

And pro-promise is also tested against Node.js 8 all the time, here's 6.7.0: https://travis-ci.org/vitaly-t/pg-promise/builds/276399400

**Comment by vitaly-t** [comment]
@flovilmart 

Anyhow, at this point I would advise to update pg-promise to the latest - 6.9.0

**Comment by flovilmart** [comment]
@vitaly-t I would love to, but no matter how many times i restart it, travis still fails.

**Comment by vitaly-t** [comment]
But does it fail for you locally? Maybe Travis CI doesn't works again, which it does frequently, especially on weekends.

**Comment by flovilmart** [comment]
just the node 8 tests are not running, 

```
module.js:487
    throw err;
    ^
Error: Cannot find module 'manakin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/parse-community/parse-server/node_modules/pg-promise/lib/main.js:4:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by flovilmart** [comment]
repend here: https://github.com/parse-community/parse-server/pull/4205

**Comment by vitaly-t** [comment]
I've just re-run all tests locally and on Travis CI, no problems: https://travis-ci.org/vitaly-t/pg-promise

Something doesn't add up. And the error doesn't make sense either, especially considering that it refers to something that hasn't changed in ages.

**Comment by flovilmart** [comment]
yeah, perhaps just related to node 8.1.3 and the npm version going with it, re-ran travis against 8.5, we'll see how it goes. Sorry for the disturb.

**Comment by vitaly-t** [comment]
n.p., let me know how you're getting on ;)

**Comment by flovilmart** [comment]
It's looking good now, I'll point the issue on npm being npm.

**Pull request closed without merging**
