### PR TITLE
Don't error when attempting to sort on an object field

### PR DESCRIPTION
**Pull request by acinader**
fixes: #4805 

see https://github.com/parse-community/parse-server/blob/3b40d2227d9b9b7a768de0c6faf6916982fe8e89/src/Controllers/DatabaseController.js#L414

There is a validation check for the name of a field to make sure that it is valid.  This check is performed in both the Schema Controller and the Database Controller.  In the database controller, the check is applied when an update or a find operation is requested on the database.

Since updates can occur to and find's can be performed on members of a document, it is important that the check only be performed on the name of the field, and not the member.

In the case of the update, there is an existing split that separates the field from the member.

The split is missing from the find when trying to sort on a field which is erroneously causing an error.

This pull request introduces a test to sort on a member of a document and a fix to allow the test to pass.

### CODE REVIEW

**Comment by acinader** [comment]
@vitaly-t any feedback on the postgress failure?

**Comment by vitaly-t** [comment]
No, I never touched the generic database code here, only the driver-related stuff.

**Comment by dplewis** [comment]
@acinader The fix for PG should be a simple fix. Transform `sortField.value` into `sortField ->> 'value'` or something like that. I'm sure you can order by json object value.

**Comment by flovilmart** [comment]
So actually in the validation, we should allow the dot notation / transformation of this sorting no?

**Comment by dplewis** [comment]
@flovilmart I know this issue https://github.com/parse-community/parse-server/issues/2113 has needed addressing. I can add support for PG order by nested since mongo already does.

**Comment by flovilmart** [comment]
Go ahead, perhaps à PR on @acinader’s or use a branch on this repo so you guys can contribute together

**Comment by dplewis** [comment]
@acinader I added some additional test. How does this look?

**Comment by acinader** [comment]
@dplewis awesome!  thanks.

@flovilmart comment added.  I factored out the operation into a function and commented.  Got rid of param reassignment too, bonus.

**Comment by flovilmart** [comment]
Yeah that’s better. I would probably have called it ‘rootFieldName’ but that’s ok as is :)

**Comment by acinader** [comment]
yeah, that is a lot better name.  see #4817.  thanks.

**Pull request merged**
