### PR TITLE
support pg-promise init options

### PR DESCRIPTION
**Pull request by rendongsc**
add database init options , hook pg connect.
```
var api = new ParseServer({
  databaseURI: databaseUri || 'postgres://Test:123@localhost:5432/Test',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '',
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse', 
  databaseOptions: {
    initOptions: {
      connect: function (client, dc, isFresh) {
        //do something here 
      }
    }
  }
});
```

### CODE REVIEW

**Comment by flovilmart** [comment]
@rendongsc can you fix the lint issue and add tests to make sure we don't incur any regression?

**Comment by vitaly-t** [comment]
As the author of pg-promise, this looks wrong to me...

```js
 client.pg.defaults[key] = dbOptions.pgOptions[key];
```

Variable `client` is the database object, which doesn't have property `pg`. Only the library's initialized object has it:

```js
pgp.pg.defaults[key] = dbOptions.pgOptions[key];
```

**Comment by flovilmart** [comment]
@vitaly-t what do you recommend. Could you have a look if there's anything wrong there?

**Comment by vitaly-t** [comment]
I have, and I published right there what it should be ;)

**Comment by flovilmart** [comment]
@vitaly-t got time for a PR? Who better than you? Should I close that one? Also, I believe with the amount of contributions you have, you should probably be granted commit access. Are you interested?

**Comment by vitaly-t** [comment]
I'm not sure what this PR is really doing, but there issue that I described was there before.

There's only that one change is needed ;) I do not have rights to update the PR, you can do it ;)

**Comment by flovilmart** [comment]
Just open a new one in that case, closing :)

**Comment by rendongsc** [comment]
@vitaly-t  
```
pgp.pg.defaults[key] = dbOptions.pgOptions[key];
```
Not wrong, but does not work.
```
var api = new ParseServer({
  databaseURI: databaseUri || 'postgres://Test:123@localhost:5432/Test',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  databaseOptions: {
    pgOptions: {
      connect: function (client, dc, isFresh) {
        if (isFresh) {          
          client.query('SET search_path = cust');
        }
      }
    }
  }
});
```

**Comment by flovilmart** [comment]
Could you add a test for that?

**Comment by rendongsc** [comment]
@flovilmart  I test the way through the output log, and spec test specifications vary greatly, give me some time.

**Comment by flovilmart** [comment]
Perhaps a mock and expectations of call for example

**Comment by flovilmart** [comment]
@rendongsc did you get a chance to add some tests?

**Comment by rendongsc** [comment]
@flovilmart  I can do that.

**Comment by flovilmart** [comment]
@rendongsc thanks for adding the tests, it seems that the linter is complaining about your spec files

**Comment by flovilmart** [comment]
@rendongsc Thanks for the PR!

**Pull request merged**
