### PR TITLE
Patch handleShutdown feature

### PR DESCRIPTION
**Pull request by trylovetom**
Patch handle Shutdown spec of ParseServer.spce.js
Patch handle Shutdown spec of PostgresStorageAdapter.spec.js
Patch handle Shutdown spec of MongoStorageAdapter.spec.js

### CODE REVIEW

**Comment by dplewis** [comment]
@vitaly-t looks good to go, can you look this over?

**Comment by vitaly-t** [comment]
@dplewis seems fine to me ;)

**Comment by dplewis** [comment]
@flovilmart can you add @vitaly-t  to the team?

**Comment by flovilmart** [comment]
Onl’y is @vitaly-t wants to ;) let me know!

**Comment by vitaly-t** [comment]
I don't mind :smile:

**Comment by dplewis** [comment]
@trylovetom thanks much needed

**Comment by vitaly-t** [comment]
I am currently rewriting all the documentation related to shutting down the library/pool (no functional changes) ;) Will ping when done ;)

**Comment by vitaly-t** [comment]
[Library de-initialization](https://github.com/vitaly-t/pg-promise#library-de-initialization) has been fully updated (documentation).

**Comment by trylovetom** [comment]
@dplewis You are welcome.
I appreciate @vitaly-t ’s effort.

**Pull request merged**
