### PR TITLE
Move graphql-tag from devDependencies to dependencies

### PR DESCRIPTION
**Pull request by davimacedo**
### New Pull Request Checklist

- [ X ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

graphql-tag is required by one of the GraphQL files: https://github.com/parse-community/parse-server/blob/033a0bd443ba846fa5a7fae969eb8f71cf492162/src/GraphQL/loaders/schemaDirectives.js#L1

Related issue: close https://github.com/parse-community/parse-server/issues/7182

### Approach
Move graphql-tag from devDependencies to dependencies

### TODOs before merging

- [ N/A ] Add test cases
- [ X ] Add entry to changelog
- [ N/A ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ N/A ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ N/A ] Add new Parse Error codes to Parse JS SDK 
- [ N/A ] ...

### CODE REVIEW

**Comment by davimacedo** [comment]
@dplewis @mtrezza any idea why CI Self-Check is failing?

**Comment by dplewis** [comment]
Looks like a mongo patch 4.4.4 was release and we test 4.4.3

**Comment by davimacedo** [comment]
Maybe we should enforce that for releasing but not for every commit. I will try to fix anyways.

**Comment by mtrezza** [comment]
I will look into auto-creating a PR with the updated version, like Snyk, to reduce the effort.

**Review by mtrezza — APPROVED** [review]
LGTM!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
