### PR TITLE
feat: Switch GraphQL server from Yoga v2 to Apollo v4

### LINKED ISSUE #8728: Switch from Yoga v2 to Apollo V4
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Yoga V4 is currently not suitable for prod. I encountered issues on upload feature, and types issues in a monorepo.

### Feature / Enhancement Description

Use the last version of Apollo Server. It could also help in the futur to get some extra features for developers using apollo client.

### Example Use Case

More details on the linked PR

### Alternatives / Workarounds

None

### 3rd Party References

https://www.apollographql.com/

### PR DESCRIPTION
**Pull request by onurhanife**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8728 

## Approach
#8727 cloned, merged into alpha and conflicts resolved

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by onurhanife** [comment]
Hi @mtrezza i created this pr and closed old one

**Comment by mtrezza** [comment]
Could you please resolve the conflict so that the CI can run?

**Comment by mtrezza** [comment]
@onurhanife I have fixed the failing CI, it was really just a package-lock sync issue.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.22](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.22)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
