### PR TITLE
feat: Remove deprecation `DEPPS2`: Config option `directAccess` defaults to true

### LINKED ISSUE #8269: Remove deprecation `DEPPS2`: Config option directAccess defaults to true
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Deprecation to be removed in Parse Sever 6:
- `DEPPS2`: Config option directAccess defaults to true

### Feature / Enhancement Description

Remove deprecation, see [list](https://github.com/parse-community/parse-server/blob/alpha/DEPRECATIONS.md).

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

`directAccess` should default to `true`

Related issue: #8269
Closes: #8269

### Approach

Changes `directAccess` to `true`

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
Could you also set the status in DEPRECATION.md from "planned" to "removed"? Every other deprecation PR requires that change as well.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.4](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
