### PR TITLE
refactor: Remove duplicate user index creation

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Duplicate code added in #7214. @dplewis I’m guessing this was accident?

Closes: n/a

## Approach

Remove duplicate code.

## Tasks

- [ ] Ensure tests pass

### CODE REVIEW

**Comment by cbaker6** [comment]
@mtrezza @dblythy this is ready for review

**Review by dblythy — APPROVED** [review]
Good pickup!

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.4](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)

**Pull request merged**
