### PR TITLE
Allow throw native Error in beforeSave hook

### PR DESCRIPTION
**Pull request by reallyimeric**

### CODE REVIEW

**Comment by reallyimeric** [comment]
@flovilmart Maybe we should not wrap thrown exception on `getResponseObject().error()`, or any error thrown in https://github.com/parse-community/parse-server/blob/91f121eb62d99ceeb184502f3ed0d49921af312a/src/triggers.js#L563-L577 will be regarded as a hook handler error.

**Comment by flovilmart** [comment]
I’m not sure I understand what you mean.

**Comment by reallyimeric** [comment]
@flovilmart I mean we should convert whatever user's `beforeSave` handler throws to a `Parse.Error` (with `Parse.Error.SCRIPT_FAILED`) as early as possible, or errors occured in library code (if any),which should be an "internal error", could be regarded as user aborting current save action. Sorry for not stating that clearly.

**Comment by flovilmart** [comment]
That seems reasonable

**Pull request merged**
