### PR TITLE
[WIP] Enable test suite to be randomized

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Per a discussion https://github.com/parse-community/parse-server/pull/7262#issuecomment-797831744
This is an attempt to run the tests at random. By random means each test file will be ran at random. While a test file is running the test within the file will be randomized. A test may rely on a previously run test and would be deemed poorly written.

Related issue: FILL_THIS_OUT

### Approach

Majority of the tests have already been fixed in https://github.com/parse-community/parse-server/pull/7262. This is a first pass attempt. This could be a community effort. If it seems too daunting of a task we can still merge but remove random.

**Known Failing Test Suites**
- [x] CLI.spec.js
No error here just wanted to set the server to different ports. Easier for debugging
- [x] FileController.spec.js
The mock adapter was changed and never reset
- [x] GridFSBucketStorageAdapter.spec.js
`Config` not properly set
- [x] index.spec.js
Properly close servers and reset
- [x] LdapAuth.spec.js
**Bug** I rewrote the test getting rid of Promise.finally. I then noticed the servers couldn't close on group search error. If there was an error I unbind and destroyed the client similar to how other errors are handled.
- [x] LoggerController.spec.js
Assumed a log would exist.
- [x] ParseGeoPoint.spec.js
**Bug** Ensure multiple geopoint field validation runs before any operation.
- [x] ParseGraphQLServer.spec.js
Initialized new server beforeEach test and close after. Set unique field names in tests.
- [x] ParseHooks.spec.js
Remove the use of AppCache. Changed server port to not conflict with `LdapAuth.spec.js`
- [x] ParseLiveQueryServer.spec.js
Properly close servers and reset
- [x] PostgresInitOptions.spec.js
Changed server port to not conflict with `index.spec.js`
- [x] PushController.spec.js
Ensure pushStatus object exists.
- [x] UserController.spec.js
Resets the mockEmailAdapter. Remove the use of AppCache. This cause the Config to be improperly set. Normally it would run at the end of the test run alphabetically. In a random test it ran first. Thats how I was able to find this issue.
See: https://github.com/parse-community/parse-server/runs/2103910826 The tests immediately started failing. I don't know why when the cache gets cleared on every reconfigureServer.
- [x] RedisCacheAdapter.spec.js
Clear cache before every test
- [x] UserPII.spec.js
The issue was the protectedFields gets merged with defaults. Once merged every subsequent `reconfigureServer` call would use the previous protectedFields from defaults. Caused by https://github.com/parse-community/parse-server/blob/random-tests/src/ParseServer.js#L419
- [ ] batch.spec.js / ParseRESTController.spec.js (transactions)
These tests timeout I believe this could be a server issue
- [ ] PushController.spec.js / Parse.Push.spec.js
These tests timeout I believe this could be a server issue

**Critical**
- [x] Error: Unable to connect to Parse API
The most likely cause of this that the JS SDK is a singleton and will get reinitialized when you create a new Server instance. It also gets initialized with the serverURL you set. In our case the servers closed but the serverURL was the same. Meaning all test will use the old serverURL until a new Server instance is created.
- [x] Error: listen EADDRINUSE: address already in use 0.0.0.0:8378
Caused when a test timeout the file descriptor is open keeping the server from closing. Similar to the client being alive prevents closing the server in `LdapAuth.spec.js`. I added `destroyAliveConnections` to mitigate this risk.
It was caused by `error: tuple concurrently updated`

**Nice to have**
- [x] Move non spec files to `/support`

### TODOs before merging

- [ ] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Comment by dplewis** [comment]
@parse-community/core-maintainers I need some help with an issue.

I realized that sometimes config.fileController or config.database (databaseController) is undefined. Is there any situation when you start a server the config would be empty or any other way it could be set to empty? I can't remember and will look around, just wanted to ask.

**Comment by mtrezza** [comment]
> Is there any situation when you start a server the config would be empty or any other way it could be set to empty? 

I remember someone mentioning this in an issue some weeks ago, I think @davimacedo made a comment on it, not sure. In the context of jasmine, I can think of
- a test starting before the server is fully initialized, maybe when calling `reconfigureServer` without `await`?
- an issue in the `helper.js` or `reconfigureSever` itself?

**Comment by dplewis** [comment]
> Is there any situation when you start a server the config would be empty or any other way it could be set to empty?

@mtrezza I figured out the issue, it was caused by UserController.spec.js. I updated my finding in the OP.

**Comment by dplewis** [comment]
@davimacedo @mtrezza This is good for review. Let me know if you have any questioms

**Comment by mtrezza** [comment]
> My final conclusion is 2800+ test and not one server change, that says something.

Can you explain what that means?

**Comment by dplewis** [comment]
After spending dozens of hours cleaning up hundreds of poorly written test. I didn’t find a single server bug. At least I have enough knowledge about the test suite to fix the flaky tests next

**Comment by mtrezza** [comment]
Pretty cool! Do you have any general recommendations as to how the test suite is set up or is that principally fine as it is?

**Comment by dplewis** [comment]
> Do you have any general recommendations as to how the test suites are set up or is that principally fine as it is?

I think it's fine the way it is. Its actually pretty simple when you compare it to the JS SDK.

> I didn’t find a single server bug. 

@mtrezza I found one lol in the LdapAuth.spec.js

**Comment by dplewis** [comment]
`should not save anything when one operation fails in a transaction` test caused the following error. It should be properly handled in a separate PR.

```
{ error: tuple concurrently updated
    at Parser.parseErrorMessage (/home/runner/work/parse-server/parse-server/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/runner/work/parse-server/parse-server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/runner/work/parse-server/parse-server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/home/runner/work/parse-server/parse-server/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  length: 90,
  name: 'error',
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heapam.c',
  line: '3888',
  routine: 'simple_heap_update' }
```

**Review by davimacedo — APPROVED** [review]
Great job, @dplewis ! It looks all good to me.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
