### PR TITLE
fix: Facebook Limited Login not working due to incorrect domain in JWT validation

### LINKED ISSUE #9117: Add support for Facebook auth JWT token
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Due to Apple's ATT requirements, the "normal" Facebook Login requires a user to allow app tracking.  For users who do not allow app tracking, Facebook Limited Login must be used instead, which uses JWT for authentication. Parse Server currently only supports the token provided by "normal" Facebook Login. It does not support the token generated by Limited Login.

This is an urgent issue, because:
- The majority of users does not allow app tracking, so developers must often fall back to Limited Login.
- The Facebook SDKs <= 16 are rejected by AppStore review because they lack the privacy manifest file. The Facebook SDK 17 automatically prohibits "normal" Login and requires Limited Login if the user has not allowed app tracking.

**That means that Parse Server (and possibly the Parse Apple SDK) currently do not support Facebook auth when submitting a new app or an app update to the AppStore with Facebook SDK 17.**

See https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1787

### Feature / Enhancement Description

Extend the Facebook auth adapter, so that it supports JWT auth from Facebook Limited Login. Ideally, no change will be required on the Parse Apple SDK side.

### Alternatives / Workarounds
Unknown.

### 3rd Party References

- https://github.com/facebook/facebook-ios-sdk/issues/2384#issuecomment-2080038284
- https://developers.facebook.com/docs/facebook-login/limited-login/

### PR DESCRIPTION
**Pull request by chriscborg**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue
[Add support for Facebook auth JWT token #9117](https://github.com/parse-community/parse-server/issues/9117)

Closes: #9117

## Approach
A JWT token validation implementation seems to be already in place, however the host needs to be changed from facebook.com to www.facebook.com as suggested by @SebC99, because the old host is returning error 301 which is not followed by the jwt-rsa package.

## Tasks
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
@chriscborg would you please merge alpha or rebase? Unfortunately I can't do it since your PR is protected.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Pull request merged**
