### PR TITLE
Improve test code

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

I noticed that when you write failing tests sometime it fails 5 times which makes it difficult to pin point where to debug. 
Also I noticed an extra parse instance getting created from what seems to be an old test file. (Wasted hours on this 😭 )

Related issue: https://github.com/parse-community/parse-server/pull/6644

### Approach

Set network retry to 1 (Changed Promise.all to saveAll in Auth.spec.js to reduce load)
Remove strange file.

### TODOs before merging

- [ ] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
- There is/was a `rest_create_app` endpoint? 😳
- Changing retry to 1 may also help to identify flaky tests easier.

**Review by erencihangir — COMMENTED** [review]
#

**Comment by dplewis** [comment]
@erencihangir Did you want to comment?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
