### PR TITLE
chore(package): update jasmine to version 3.0.0

### PR DESCRIPTION
**Pull request by flovilmart**
Closes #4547

- Use consts / lets in tests as jasmine 3.0 don't like vars.
- Fixes a few flaky tests
- Keep the tests non random as it still yield a few issues on shared variables.

### CODE REVIEW

**Comment by dplewis** [comment]
f7b849c5661ad2aaeae52610feb1f2265105e45ee3f932196d23efd18638d35e

**Comment by flovilmart** [comment]
Yeah, find replace all by const, and fix all wrong conts

**Comment by dplewis** [comment]
@flovilmart Is your email florent _ at _ flovilmart _ dot _ com?

**Comment by flovilmart** [comment]
@dplewis  yep it is

**Pull request merged**
