### PR TITLE
Fix read preference for aggregate

### PR DESCRIPTION
**Pull request by mtrezza**
added failing test cases

### CODE REVIEW

**Comment by mtrezza** [comment]
The fix in https://github.com/parse-community/Parse-SDK-JS/pull/1143 seems to work looking at the mongodb logs.

But I am stuck verifying the read preference in the test case. I don't know what to `spyOn`. 

- `spyOn(databaseAdapter.database.serverConfig, 'command').and.callThrough();` doesn't work because `command` is not called when executing the aggregate query.

- `spyOn(databaseAdapter.database.serverConfig, 'cursor').and.callThrough();` doesn't work because `cursor` is only called 1 time for the schema when executing the aggregate query.

@dplewis Can you help me out on this?

**Comment by dplewis** [comment]
@davimacedo Is the expert on readPreferences and wrote most of the tests.

**Comment by mtrezza** [comment]
Alright, got the test case fixed for aggregate.

**Comment by mtrezza** [comment]
All parse server tests pass locally with the parse SDK merged with fix https://github.com/parse-community/Parse-SDK-JS/pull/1143.

So before merging this PR the new parse SDK has to be released.

**Comment by mtrezza** [comment]
@acinader ready for review

**Comment by mtrezza** [comment]
Thanks!

**Pull request merged**
