### PR TITLE
ci: reduce timeout after idempotency tests

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: n/a

### Approach

Idempotency tests mutate `DEFAULT_TIMEOUT_INTERVAL` to 3 and a half minutes, so any tests thereafter will maintain that timeout. This means that if 3-5 tests timeout, the whole test suite will stop (as it's limited to 15 minutes).

This PR sets the timeout back to the default after the Idempotency tests.

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by Moumouls — APPROVED** [review]
LGTM

**Comment by mtrezza** [comment]
@dblythy is this ready for review?

**Comment by dblythy** [comment]
Yes, apologies

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.30](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.30)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Pull request merged**
