### PR TITLE
refactor: remove unnecessary error checking in PostgresAdapter

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

There are unnecessary error checks in `PostgresStorageAdapter.js` that were left over from adding `IF NOT EXISTS` in #6741 and #6506 

Related issue: #6741 and #6506

### Approach

Remove error checks and code that isn't used anymore.

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by cbaker6** [comment]
@mtrezza this is ready for review.

**Review by mtrezza — APPROVED** [review]
Looks good

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.16](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.16)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)

**Pull request merged**
