### PR TITLE
style: re-Run Prettier on master

### PR DESCRIPTION
**Pull request by sadortun**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

`master` seems to miss a few of Prettier styling. This is just to fix that.

Related issue: #n/a

### CODE REVIEW

**Comment by sadortun** [comment]
FYP @parse-github-assistant tell us we can use `n/a`, but does not accept it

image

**Comment by mtrezza** [comment]
Yes, thanks for your feedback, we will generally simplify the templates soon to make contribution easier.

**Comment by mtrezza** [comment]
@sadortun do you think you could resolve the conflict so we can merge this?

**Comment by sadortun** [comment]
@mtrezza 

✔️ Done

**Comment by mtrezza** [comment]
Maybe we should merge https://github.com/parse-community/parse-server/pull/7446 before this, since its quite a large change.

**Comment by sadortun** [comment]
@mtrezza 

This PR is outdated.

Please just run prettier on alpha/beta/master branches to stop having to manually revert unchanged PR files that were updated by the `pre-commit` hook

**Pull request closed without merging**
