### PR TITLE
Add auto-creation of PR for upgrade of MongoDB / Node.js CI env

### LINKED ISSUE #7185: Add auto-creation of PR for upgrade of MongoDB / Node.js CI env
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Upon fail of ci-self-check a PR has to created manually to update the MongoDB / Node.js versions, before other CI runs pass.

### Feature / Enhancement Description
Add auto-creation of PR when a new MongoDB / Node.js version is released to update the versions in CI environments.

### Example Use Case
(none)

### Alternatives / Workarounds
Manually creating PR.

### 3rd Party References
(none)

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Upon fail of ci-self-check a PR has to created manually to update the MongoDB / Node.js versions, before other CI runs pass.

Related issue: closes #7185

### Approach
Ci-Self-Check modifies `ci.yaml` if necessary and commits the change to a new PR.

### Side changes
This also moves the lint check out of the mongodb check.

### TODOs before merging

- [ ] Add entry to changelog

### CODE REVIEW

**Comment by mtrezza** [comment]
This is currently in draft because I couldn't find a way around the issue that a GH action in a public repo, triggered by a forked PR, apparently has no write access and therefore cannot create a PR.

**Comment by dplewis** [comment]
I think we should bump the env when we do releases. We could run the CI check on a specific branch like x.x.x for the release.

**Comment by mtrezza** [comment]
I am actually not sure about this because:

- Bumping this simply requires existing PRs to rebase on master, it's not much different from any other PR that gets merged.
- We want to automate releases and reduce the effort down to 5 minutes without the requirement to touch any code.
- If we shift more work to the time of release we increases the effort required to make a release, which is why releases are currently made only every 4 months.

**Comment by mtrezza** [comment]
> ## ⚠️ Important change for merging PRs from Parse Server 5.0 onwards!
  >
  > We are planning to release the first beta version of Parse Server 5.0 in October 2021.
  >
  > If a PR contains a breaking change and is not merged before the _beta_ release of Parse Server 5.0, it cannot be merged until the end of 2022. Instead it has to follow the [Deprecation Policy](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#deprecation-policy) and phase-in breaking changes to be merged during the course of 2022.
  >
  > One of the most voiced community feedbacks was the demand for predictability in breaking changes to make it easy to upgrade Parse Server. We have made a first step towards this by introducing the Deprecation Policy in February 2021 that assists to phase-in breaking changes, giving developers time to adapt. We will follow-up with the introduction of [Release Automation](https://github.com/parse-community/parse-server/issues/7271) and a branch model that will allow breaking changes only with a new major release, scheduled for the beginning of each calendar year.
  >
  > We understand that some PRs are a long time in the making and we very much appreciate your contribution. We want to make it easy for PRs that contain a breaking change and were created _before_ the introduction of the Deprecation Policy. These PRs can be merged with a breaking change without being phased-in before the beta release of Parse Server 5.0. We are making this exception because we appreciate that this is a time of transition that requires additional effort from contributors to adapt. We encourage everyone to prepare their PRs until the end of September and account for review time and possible adaptions.
  > 
  > If a PR contains a breaking change and should be merged before the beta release, please mention @parse-community/server-maintenance and we will coordinate with you to merge the PR.
  >
  > *Thanks for your contribution and support during this transition to Parse Server release automation!*

**Pull request closed without merging**
