### PR TITLE
Verify Password before returning User email is not verified.

### PR DESCRIPTION
**Pull request by dblythy**
Related to #4693.

"User email is not verified" error should return unless password is correct.

### CODE REVIEW

**Comment by flovilmart** [comment]
@dblythy thanks for the PR! That's usually the way to go for those small nits!

**Comment by addisonElliott** [comment]
Why didn't this PR close upon merging?

**Comment by flovilmart** [comment]
@addisonElliott it's not merged yet.

**Comment by flovilmart** [comment]
@dblythy thanks again for the PR!

**Pull request merged**
