### PR TITLE
add context to Parse.Object.save

### PR DESCRIPTION
**Pull request by mtrezza**
Exposes the context object in Parse.Object.save() so that parameters can be made accessible in Cloud Code triggers beforeSave, afterSave.

Example:

```
const obj = new TestObject();
await obj.save(null, {context: {a: "a"}});

Parse.Cloud.beforeSave("TestObject", req => {
    console.log(req.context.a);
});

Parse.Cloud.afterSave("TestObject", req => {
    console.log(req.context.a);
});
```
---
Don't merge until

- [x] Concept agreed on in https://github.com/parse-community/parse-server/issues/6459
- [x] Merged https://github.com/parse-community/Parse-SDK-JS/pull/1150 (this PR depends on it)

### CODE REVIEW

**Comment by acinader** [comment]
seems useful to me and looks good.  curious any thoughts you might have @davimacedo and @dplewis 

if we merge, i can add to the PHP sdk

**Comment by mtrezza** [comment]
@acinader There is an open question regarding security when exposing the context to the client.

I added this question to https://github.com/parse-community/parse-server/issues/6459.
Let me know what you think.

**Comment by dplewis** [comment]
@mtrezza The latest version of the SDK has been released and merged. You can update your branch and add the test cases.

**Comment by mtrezza** [comment]
@dplewis Great! Let's see if the tests pass 🤞

**Comment by mtrezza** [comment]
@acinader ready for review

**Comment by uzaysan** [comment]
How can we use master key with context?

Is this correct:
`await obj.save(null, {context: {a: "a"}, useMasterKey: true});`

**Comment by davimacedo** [comment]
Yes. It should work.

**Pull request merged**
