### PR TITLE
Update MongoDB to 3.3.5

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/parse-server/issues/6261, https://github.com/parse-community/parse-server/issues/6041

This is a work in progress, any help will be appreciated

[Unified Topology Guide](https://github.com/mongodb/node-mongodb-native/blob/9fcf73d44c65ed5e04f41d72ed5ccba3195a6d4a/docs/reference/content/reference/unified-topology/index.md)

### CODE REVIEW

**Comment by dplewis** [comment]
@acinader @davimacedo The tests pass locally for me. I can't replicate this.

**Comment by davimacedo** [comment]
Travis is really strange recently. I am trying to figure it out.

**Comment by dplewis** [comment]
@davimacedo This error occurs for me when I run the entire test suite instead of individual files

**Comment by dplewis** [comment]
@acinader @davimacedo I don't know why `xit` that test fixed this.

**Pull request merged**
