### PR TITLE
Improve contribution guide

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
The contribution guide is missing documented processes for:
- Add new Parse Error
- Add new Parse Server configuration parameter

This sometimes resulted in incomplete implementations in the past.

Related issue: #7100

### Approach
Added processes.

### TODOs before merging

(none)

____

_Edit: This originally larger PR has been broken up into smaller tasks by moving the discussion into issue #7100._

### CODE REVIEW

**Comment by dblythy** [comment]
@mtrezza would you see any value in including some basic fork / commit / submit a PR instructions using a visual tool such as GitHub desktop? I know for me understanding git was a challenge at the start.

**Comment by mtrezza** [comment]
That's a good idea, some screenshots can definitely help here. I actually think screenshots are key here. It may be flood of text that discourages some new developers from getting into contributing. It surely must be for people who rather absorb information visually. If we have some extra time, I would like to add some tutorial videos as well.

**Comment by dblythy** [comment]
> I'm thinking the guide should be focused on bug fixing. We've had many instances where obvious small bugs were identified that would have been easy to fix, but the bug reporter did not know how to do that. The result was that the bugs stayed unfixed for longer than necessary.

100% agree. The beauty of this package is that it is accessible to developers of all skill levels, which often means that some terminology or processes might be hard to understand for some new developers.

I would be more than happy to write instructions if you'd require me to. I was thinking I could tackle #7058 (as I think it will be a pretty easy fix) and walk through the entire process from fork, spec, PR, merge, etc, and maybe that could be as a blog post on blog.parseplatform.org?

**Comment by mtrezza** [comment]
> I was thinking I could tackle #7058 (as I think it will be a pretty easy fix) and walk through the entire process from fork, spec, PR, merge, etc

Do you mean as a screen recording or why do you mention the specific issue #7058?

> maybe that could be as a blog post on blog.parseplatform.org?

Good idea, the new contribution guide could make for an interesting blog post once it's done.

**Comment by mtrezza** [comment]
This originally larger PR has been broken up into smaller tasks by moving the discussion into issue #7100.
This PR is ready for review.

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
