### PR TITLE
docs: fix incorrect deprecation date of `allowClientClassCreation` option

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

The incorrect date was used in #7925 to deprecate allowClientClassCreation.

Related issue: #7925

### Approach

Fix date

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! I remember we examined this so much and still wrong date 🙃

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-server/releases/tag/5.3.0)

**Pull request merged**
