### PR TITLE
refactor: Upgrade apollo-upload-client from 17.0.0 to 18.0.1

### PR DESCRIPTION
**Pull request by Moumouls**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: https://github.com/parse-community/parse-server/pull/9009

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [x] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Review by mtrezza — DISMISSED** [review]
Looks good

**Comment by mtrezza** [comment]
This requires at least Node 18.15, which is higher than the current min node engine version. We'll merge this in Parse Server 8 around Dec 2024.

**Comment by Moumouls** [comment]
flaky on mongo 7 it seems @mtrezza

**Comment by mtrezza** [comment]
We may merge this in Nov, when we start with Parse Server 8 preparations.

**Comment by Moumouls** [comment]
@mtrezza if i remember the breaking stuff was about 6.X, for current alpha it should be okay to merge now.

**Comment by mtrezza** [comment]
I must have mixed up the browser tabs, thanks

**Pull request merged**
