### PR TITLE
fix: server crash using GraphQL due to missing @apollo/client peer dependency

### LINKED ISSUE #7786: Production install fails at runtime, missing @apollo/client peer dep
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Missing apollo client peer dep from graphql tools, so a production install will fail at runtime if GraphQL is used

### Steps to reproduce
Install a parse-server in production mode and use graphql

### Actual Outcome
```sh
Error: Cannot find module '@apollo/client/link/core'
Require stack:
- /srv/app/node_modules/@graphql-tools/links/index.js
- /srv/app/node_modules/parse-server/lib/GraphQL/loaders/defaultGraphQLTypes.js
- /srv/app/node_modules/parse-server/lib/GraphQL/ParseGraphQLSchema.js
- /srv/app/node_modules/parse-server/lib/GraphQL/ParseGraphQLServer.js
- /srv/app/node_modules/parse-server/lib/ParseServer.js
- /srv/app/node_modules/parse-server/lib/index.js
- /srv/app/packages/dashboard-back/lib/src/server.js
- /srv/app/packages/dashboard-back/lib/index.js
```

### Expected Outcome
Not to crash
### Environment

Server
- Parse Server version: `5.0.0-alpha.20`
- Operating system: `Docker Alpine`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `N/A`

Database
- System (MongoDB or Postgres): `N/A`
- Database version: `N/A`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `N/A`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `N/A`
- SDK version: `N/A`

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: https://github.com/parse-community/parse-server/issues/7786

### Approach
Switch to dep

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by Moumouls** [comment]
Branch updated, feel free to merge this one @mtrezza

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.23](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.23)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)

**Pull request merged**
