### PR TITLE
PG: Fix updating numeric array

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/parse-server/issues/5239

### CODE REVIEW

**Comment by flovilmart** [comment]
@dplewis can you add tests for mixing text, object and numeric on updating objects?

**Comment by dplewis** [comment]
I don't think that is supported in Postgres unless we add something like [Composite Types](https://www.postgresql.org/docs/9.1/rowtypes.html)

@vitaly-t Is it possible to have an array of multiple types in PG? I wrote a test case for it locally and it fails

**Comment by flovilmart** [comment]
I wanted to check the failure indeed :)

**Comment by vitaly-t** [comment]
@dplewis From `pg-promise` side, it supports arrays with mixed types. When you use filter `:csv`, each value is formatted according to its JavaScript type. And the filter also respects [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting).

**Comment by dplewis** [comment]
@vitaly-t Thanks, thats really helpful.

I tried to do something like

`$${index}:name = json_build_array($${index + 1}:csv)`

But objects are stored as `text` instead of `json`

`{foo: 'bar'}` =>` '{"foo": "bar"}'`

Also is that filter recursive. Like if I have an array of array of mixed types?

**Comment by vitaly-t** [comment]
> But objects are stored as text instead of json

If you give me an example of what you are trying to achieve, I could come up with a usable example.

>  if I have an array of array of mixed types?

For an array of mixed types, each value that's a mixed type needs to implement [Custom Type Formatting]. And then it can be recursive also.

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting

**Pull request merged**
