### PR TITLE
Use newer jwks-rsa library and its async/await functions

### PR DESCRIPTION
**Pull request by olleolleolle**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue). See #7304

### Issue Description

This adds the requirement "parse-server works with Node 10 and newer" a real thing in `package.json`.

This PR intends to upgrade a dependency and switch from promisify to async/await.

Bumping the min Node.js requirement is merely a side-effect, but it makes also sense for another reason because Parse Server is officially only compatible (and tested) with Node >= 10.

Related issue: #7304

### Approach

- Set engines to include Node 10+, since the library requires that. This makes sense, also for parse-server, since it is tested with Node 10+, already.
- Change the apple & facebook auth files to use jwks client with its new async/await-ready functions as seen in the upgrade guide for 2.x: https://github.com/auth0/node-jwks-rsa/blob/master/CHANGELOG.md#migrated-callbacks-to-asyncawait

(I attempted to run `npm install`, but that happened to have a newer npm (7) which bumped the [lockfileVersion](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion). Hm. Not what I wanted to do.)

### TODOs before merging

Current trouble w/ my bad use of the tests: 

```
1) facebook limited auth adapter (using client id as string) should verify id_token
  - Error: <spyOn> : getSigningKey() method does not exist
  Usage: spyOn(<object>, <methodName>)
```

- [ ] use spyOn correctly
- [x] Use the 2.x version of the library
- [x] Use the new functions in facebook auth file
- [x] Use the new functions in apple auth file
- [x] Add entry to changelog?

### CODE REVIEW

**Comment by olleolleolle** [comment]
Ah, perfect, the right tests are failing, I'll get to that.

**Comment by olleolleolle** [comment]
@mtrezza 👋 Hi, I know that I won't have time to get the tests in shape in the forseeable future, so please do investigate.

**Comment by mtrezza** [comment]
Thanks for the update, let's leave this open for now.

**Comment by mtrezza** [comment]
> ## ⚠️ Important change for merging PRs from Parse Server 5.0 onwards!
  >
  > We are planning to release the first beta version of Parse Server 5.0 in October 2021.
  >
  > If a PR contains a breaking change and is not merged before the _beta_ release of Parse Server 5.0, it cannot be merged until the end of 2022. Instead it has to follow the [Deprecation Policy](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#deprecation-policy) and phase-in breaking changes to be merged during the course of 2022.
  >
  > One of the most voiced community feedbacks was the demand for predictability in breaking changes to make it easy to upgrade Parse Server. We have made a first step towards this by introducing the Deprecation Policy in February 2021 that assists to phase-in breaking changes, giving developers time to adapt. We will follow-up with the introduction of [Release Automation](https://github.com/parse-community/parse-server/issues/7271) and a branch model that will allow breaking changes only with a new major release, scheduled for the beginning of each calendar year.
  >
  > We understand that some PRs are a long time in the making and we very much appreciate your contribution. We want to make it easy for PRs that contain a breaking change and were created _before_ the introduction of the Deprecation Policy. These PRs can be merged with a breaking change without being phased-in before the beta release of Parse Server 5.0. We are making this exception because we appreciate that this is a time of transition that requires additional effort from contributors to adapt. We encourage everyone to prepare their PRs until the end of September and account for review time and possible adaptions.
  > 
  > If a PR contains a breaking change and should be merged before the beta release, please mention @parse-community/server-maintenance and we will coordinate with you to merge the PR.
  >
  > *Thanks for your contribution and support during this transition to Parse Server release automation!*

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/issues/7304#issuecomment-2234287275

**Pull request closed without merging**
