### PR TITLE
feat: Add context to Cloud Code Triggers `beforeLogin` and `afterLogin`

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Ref: https://github.com/parse-community/Parse-SDK-JS/issues/1991

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
@dplewis You indicated that his PR closes a JS SDK issue. Can I move the JS SDK issue to the server repo then? A PR can only be linked to an issue if it's in the same repository.

**Comment by dplewis** [comment]
@mtrezza Is this good to merge?

**Comment by mtrezza** [comment]
Could you clarify how this PR is related to the JS issue? And what bug this PR fixes?

**Comment by dplewis** [comment]
@mtrezza This is a feature.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.5.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.5.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
