### PR TITLE
fix: ES6 modules do not await the import of Cloud Code files

### LINKED ISSUE #8367: Dynamic imports do not correctly await with ES6 modules
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When using Parse Server as an ES6 module, cloud code is not correctly `awaited` on import.

### Steps to reproduce

Use Parse Server in an ES6 module, create a cloud code file

### Actual Outcome

Cloud code should import before `.start` is resolved.

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

ES6 modules do not correctly import cloud code. Using `.default` does not await for the entire file to be imported.

I initially wrote this code with `.default` as my cloud code was not importing at all, it was freezing. With `.default` it works, but the server would mount before the cloud code was resolved.

The freeze was actually caused by a circular dependancy on my `index.js`.

Closes: #8367

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this a bug that exists in Parse Server 5? If not, then we'll merge this as a `refactor` commit type because a PR that fixes a bug that only exists in the alpha branch shouldn't be in the changelog.

**Review by mtrezza — APPROVED** [review]
Looks good! Does the PR title make sense?

**Comment by dblythy** [comment]
Yep!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.26](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.26)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
