### PR TITLE
Run nsp check on release

### PR DESCRIPTION
**Pull request by flovilmart**
As suggested by #4266

### CODE REVIEW

**Comment by steven-supersolid** [comment]
Could also look at snyk (snyk.io) although that requires sign-in.

We install snyk and nsp as dev depencies run both during build. Nsp usually catches what snyk does - not sure if they use the same vulnerabilities database.

Snyk can also watch a repository and run tests on a PR https://snyk.io/docs/github

**Comment by montymxb** [comment]
Same as mentioned for snyk, nsp can also run on our PRs as a [separate step](https://nodesecurity.io/) in our CI. Believe this also requires us to signup however.

**Comment by flovilmart** [comment]
This runs on PR's, that's why it fails.

**Comment by flovilmart** [comment]
@steven-supersolid I merged your branch onto master and updated this one, in all goodness, this should be OK with nsp check. They also have an eslint plugin that warns on unsafe potential code.

**Comment by flovilmart** [comment]
@montymxb what do you think? should we go with nsp for now, at least, next release will be safe :)

**Comment by montymxb** [comment]
@flovilmart Yeah nsp works for me. I think it's good to know our options though, should we choose to look into this in further detail.

**Comment by montymxb** [comment]
@flovilmart at some point we'll probably want this to run on PRs too. Release checking is better than nothing, but it would be nice to know if some pending feature was about to introduce a potential issue. Was there some problem with trying it on PRs originally?

**Comment by flovilmart** [comment]
This is running on PR’s, as you can see in https://travis-ci.org/parse-community/parse-server/builds/291256870

It’s only run at the release stage. This is why in this builds, we can clearly identify that we’d have issues releasing that PR, which is not related to the code itself.

**Comment by montymxb** [comment]
Ah I stand corrected! We're all good then.

**Comment by steven-supersolid** [comment]
Nice :)

**Pull request merged**
