### PR TITLE
pg-promise refactoring

### PR DESCRIPTION
**Pull request by vitaly-t**
initial refactoring of `pg-promise` code.

### CODE REVIEW

**Comment by vitaly-t** [comment]
The issue on Travis CI is unrelated to the change.

**Comment by flovilmart** [comment]
If you rebase on master this should be good!

**Comment by vitaly-t** [comment]
@flovilmart yes, just conventions. Also, in line with the use of [pg-monitor], which I believe you guys are not using, though it is very useful, to be able to see exactly what is going on. :wink:

[pg-monitor]:https://github.com/vitaly-t/pg-monitor

**Comment by vitaly-t** [comment]
@flovilmart I should have just used ES6 `yield` for now, which works the same, will do in another PR ;) Those will be directly convertible into `await/async` ;)

**Comment by flovilmart** [comment]
Let’s try not to have Babel regenerator runtime as we’ve had performance problems with it in the past, that’s why I aim to maintain the minimum amount of transpilation and move forward with LTS. Now we’re targeting 6.11. And we could /should probably target current LTS. What do you think?

**Comment by vitaly-t** [comment]
@flovilmart That's absolutely not what I suggested. ES6 generators are supported since Node 4 :wink: Also, I never use Babel for anything, not a fan :smile:

**Pull request merged**
