### PR TITLE
Adding logLevel info to README

### PR DESCRIPTION
**Pull request by QB3L**

### CODE REVIEW

**Comment by QB3L** [comment]
Change made @acinader. Your descriptions is perfect! Thanks for the reference. I tracked back the code to the winston logger levels and was thinking about doing a reference to the specific filepath but the github link is much better!

**Comment by natanrolnik** [comment]
@QB3L thanks for the PR! Small request, if possible: add the link to Winston inside the markdown, like this:

More info [check Winston](link)

**Comment by QB3L** [comment]
@natanrolnik done

**Comment by natanrolnik** [comment]
Thanks @QB3L ! Merged :)

**Pull request merged**
