### PR TITLE
Add Github process to contributing guide

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
As far as I can tell, there are no references in the contributing guide to the expected GitHub process (e.g open issue -> discuss approach -> open PR)

The guide currently jumps to "submit a PR", which I know makes @mtrezza annoyed, but more importantly, can make new contributors assume that any new feature should be submitted straight through a PR, not an FR first.

Related issue: #7100

### CODE REVIEW

**Comment by mtrezza** [comment]
That's a good one! A process description for this would surely be helpful.

**Comment by TomWFox** [comment]
Could we add a not about the importance of documentation changes, perhaps to the please do's?

**Comment by dblythy** [comment]
@TomWFox changed to "Please Do's"

**Comment by TomWFox** [comment]
I didn't mean for you to move what you had already done to the Please Do's (I think that was great as it was!) I just thought it would be good to add a point about documentation there e.g. `* Please consider if any changes to the [docs](http://docs.parseplatform.org) are needed or add additional sections in the case of an enhancement or feature`

You could revert the last commit.

**Review by TomWFox — APPROVED** [review]
LGTM 👍

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
