### PR TITLE
fix: enforce stricter lint

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

This PR adds more modern ESLint rules, such as:

`no-await-in-loop`
`eqeqeq`
`no-empty`
`prefer-template`
`no-var`

Related issue: #7260

### Approach

Updates a lot of code

### TODOs before merging

- [ ] Fix failing tests
- [ ] Add entry to changelog

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for opening this PR!

Did you have a look if there is any manual change required that lint cannot auto-fix? If one of the rule causes a lot of code refactoring we may want to deal with it in a separate PR to better focus on it.

**Comment by dblythy** [comment]
There was a fair bit of manual refactoring that I had to do in this PR (that i've already done 😊 ).

Ok, I can remove `no-await-in-loop` and revert the changes

**Comment by mtrezza** [comment]
I think for tests we can exclude the no await in loops rule?

**Comment by dblythy** [comment]
> await in loop is just necessary, when reconfiguring the server for example.

I figured that out when I tried to refactor them!

Ok, so keep `no-await-in-loop` but allow it to be disabled in tests using `/* eslint-disable no-await-in-loop */`?

**Comment by mtrezza** [comment]
> Ok, so keep no-await-in-loop but allow it to be disabled in tests using /* eslint-disable no-await-in-loop */?

Is it possible to exclude the `specs` path for an individual rule?

**Comment by mtrezza** [comment]
I had a look at the changes in the meantime, and they are a lot, which may be an issue combined in a single PR.
So I just want to iterate from the comments above:

- This PR should only add rules that may require changes that are made by `lint --fix`, no manual changes.
- Each rule we introduce, that requires manual refactoring of the code should be in a separate PR. This is to break down a huge change into smaller changes for better quality control and debugging. We cannot solely rely on tests, but we have to look over each change whether it makes sense, just looking at the implications of the `eqeqeq` rule.
- For each rule we have to discuss whether it should apply to the `spec` folder (tests). If we discuss that before making changes we can optimize the work effort. The specific lint config for `spec` should be defined in a [lint config file](https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy), rather than adding lint exceptions to code files.

**Comment by dblythy** [comment]
Ok, no worrries! Closing as every rule required manual refactoring.

**Pull request closed without merging**
