### PR TITLE
Remove  sigkill and sigint handler added to overcome a long closed issue with node

### PR DESCRIPTION
**Pull request by acinader**
fixes: #4593 

rip out all of the `configureListener` code since https://github.com/nodejs/node/issues/2642 has been long resolved.

I have confirmed that when parse server receives sigkill or sigint and the server closes, connections to mongo are also closed.

This removes some questionable code, which I can elaborate on if anyone is curious....

### CODE REVIEW

**Comment by dplewis** [comment]
> I think that this is proper hygiene? Wait a tick before process exit, not for any particular reason other than it seems defensive?

I think this is better than `nextTick`. Maybe not needed but I like defensive programming.

> I can rip out all of the configureListener code since nodejs/node#2642 has been long resolved (i've tested and it shutsdown all nice without that code now.).

Does #2 also solves #3?

**Comment by acinader** [comment]
excellent question @dplewis!

Yes, if I just rip it all out, it just works as I'd expect.  So what do I expect? I expect that when I start my server I can see the connection count on the mongo server increase.  When I then kill the server with ctrl-c or with `kill $PARSE_PID`I see the connection decrease to the level it was at before I started the server.

So I think that the right answer is to just rip it all out.  Pr update coming.

Am I missing something?

**Comment by flovilmart** [comment]
Some adapters still need the handleShutdown IIRC

**Comment by flovilmart** [comment]
@acinader we actually need the shutdown handler here as some external adapters are expecting it to be called to do some cleanup.

Removing it is a bad idea :) also the liveQuery should register it’s own shutdown handler if that’s the issue at hand

**Comment by acinader** [comment]
k will go back to the drawing board and figure out how to get the livequery server to shutdown.

**Comment by flovilmart** [comment]
Probably in a similar way to the parse server. Is it when it’s run stand alone that it’s not shutting down? Do you have a code example?

**Comment by acinader** [comment]
@flovilmart this is just when I am running the livequery server in the same process as parse-server which I do for development.  
This is what my config looks like to start:

```
"liveQuery": {
    "classNames": ["Test"]
  },
  "liveQueryServerOptions": {
    "appId": "...",
    "masterKey": "...",
    "serverURL": "http://localhost:1337/parse",
    "port": "8082",
    "keyPairs": {
      "clientKey": "...",
      "masterKey": "..."
    }
  }
```

**Pull request closed without merging**
