### PR TITLE
fix: Cloud Code Trigger `afterSave` executes even if not set

### LINKED ISSUE #502: SaveAll on new objects does not return objectIds
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-php-sdk/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-php-sdk/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse PHP SDK](https://github.com/parse-community/parse-php-sdk/releases). 

### Issue Description

When setting liveQuery.classNames in the server config save all doesn't return object Id when saving more than one new objects. I assume that some sort of afterSave trigger is called that strips away the objectId. I've tested this against Parse Server 6. ObjectIds are returned when you saveAll on one object.

Since objectIds aren't returned you can't delete / save etc.

I believe the issue can be found by looking https://github.com/parse-community/parse-server/blob/alpha/src/RestWrite.js#L1607

### Actual Outcome

Objects save but objectId is missing

### Expected Outcome

Objects save and return Id.

Parse PHP SDK
- SDK version: `2.0.0`
- PHP version: `8.1`

Server
- Parse Server version: `6.0.0`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

AfterSave triggers will run when the triggers don't exist. This can cause major issues when trying to merge an afterSave result that is undefined with an object. This PR will also reduce overhead on afterSave calls

Closes: https://github.com/parse-community/parse-php-sdk/issues/502

### CODE REVIEW

**Review by mtrezza — DISMISSED** [review]
Looks good!

To be more specific with the PR title, does this describe what this PR fixes?

> fix: Cloud Code Trigger `afterSave` executes even if not set

**Comment by dplewis** [comment]
@mtrezza Title has been changed, sorry I'm horrible at naming these

**Comment by mtrezza** [comment]
All good, most important is the code fix after all. I'm just always double checking to hopefully create an understandable changelog entry for developers.

Let's merge #8519 before this so we can also see the new API docs generated.

**Comment by dblythy** [comment]
Could we possibly add a failing test here? I’ve found in the past afterSave response changes can result in certain JS SDK tests failing, I’m worried if that happens again the bug will be re-introduced

**Comment by dplewis** [comment]
@dblythy I'm not sure how to write a failing test. Perhaps you can write one.

**Comment by dplewis** [comment]
@dblythy @mtrezza I've added a failing test.

**Comment by mtrezza** [comment]
Thanks, I'm re-running the CI to get all tests passing; if @dblythy could review this again then I'll go ahead and merge.

**Comment by dplewis** [comment]
@mtrezza Can we merge this?

**Review by dblythy — APPROVED** [review]

**Review by dblythy — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
