### PR TITLE
fix: Rate limiting across multiple servers via Redis not working

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

#8394 introduced a small typo causing the RedisCache CI to fail

Closes: #8394

## Approach

Fixes typo

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
I'm using the same PR title here as the feature isn't actually usable in the previous patch due to the typo. I think the issue was missed due to a number of flaky other tests, which I have addressed in #8468

**Comment by mtrezza** [comment]
This is an alpha fix, but unfortunately it will incorrectly appear also in beta and stable release changelogs because of https://github.com/semantic-release/changelog/issues/303.

I think the best way is to treat this as the `fix` that it is and accept that it will appear in the changelog. If we use `refactor` then there won't be any changelog entry even in the alpha changelog, which may be even more confusing. If we use `feat` then (I believe) it will appear multiple times in the changelog and it's again confusing for readers of the alpha changelog because the feature has already been added a few pre-release versions earlier.

**Comment by mtrezza** [comment]
Rerunning failing CI jobs

**Review by mtrezza — APPROVED** [review]
Looks good, rerunning failing CI jobs

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Pull request merged**
