### PR TITLE
fix(direct-access): save context not present if direct access enabled

### PR DESCRIPTION
**Pull request by omairvaiyani**
Related [PR](https://github.com/parse-community/parse-server/pull/6626) introduced a new feature but does not work with experimental Direct Access which uses `ParseServerRESTController`.

Proposed change just adds `context` into `data` as expected by `RestWrite`

[Open discussion](https://github.com/parse-community/parse-server/issues/6459) for feature with other issues

### CODE REVIEW

**Comment by dplewis** [comment]
Can you add a test case?

**Comment by dplewis** [comment]
@yog27ray Shouldn't this be fix via https://github.com/parse-community/parse-server/pull/6666 now that you moved context to the middleware?

**Comment by dplewis** [comment]
@omairvaiyani I'm going to add a test case to cover direct access. This has already been fixed via 
https://github.com/parse-community/parse-server/pull/6666/files#diff-698500347c579cf381cfce33fb74e2ff

**Comment by omairvaiyani** [comment]
@dplewis thanks for that! My apologies for the uncertainty around the fix. We've been settled on parse-server v3~ since the GraphQL Relay change so my patches are hazy!

**Pull request merged**
