### PR TITLE
add request headers to trigger functions

### PR DESCRIPTION
**Pull request by miguel-s**
Contributing to #1461

Adds the node request headers to the request object in Parse trigger functions.

### CODE REVIEW

**Comment by flovilmart** [comment]
Hi @miguel-s , I was pretty sure you would have gone down that road and that's why we didn't implement it already, the req.config should 'per-request' so I believe this would be a better place to put those headers instead of a new parameter everywhere which could be very fragile. 

Could you factor the request headers in the Config, or a Config subclass so it's easier to manage in the future?

**Comment by oallouch** [comment]
From the outside, and from someone who doesn't know the implementation, it feels weird not to have the header in req.headers.
Btw, I just needed this feature to check that a Job is called by Google App Engine's cron.yaml using the "X-Appengine-Cron" header.
Thx a lot, @miguel-s !

**Comment by flovilmart** [comment]
@oallouch, this is already implemented in functions and jobs. Here it’s for the hooks

**Comment by oallouch** [comment]
Ah ok. Great. Just asking, do you plan to update the docs for things like this (like afterFind in the Guide and before/afterFind in the JS SDK API ref, for instance) ?

**Comment by flovilmart** [comment]
If you wanna make a PR on the docs, go ahead!

**Comment by miguel-s** [comment]
@flovilmart just to make sure I understood you correctly, I could add the headers to the config object in the handleParseHeaders function in middlewares.js, would this be an acceptable solution?

**Comment by flovilmart** [comment]
@miguel-s that would be better as I believe we create a new Config for each request

**Comment by oallouch** [comment]
I knew you would say that !
I'll try.

**Comment by miguel-s** [comment]
@flovilmart let me know what you think of the new approach

**Comment by montymxb** [comment]
Now that this is merged in we can go ahead and close out #1461 ?

**Comment by flovilmart** [comment]
Yes!

**Pull request merged**
