### PR TITLE
test: Fix flaky tests for comment in MongoDB query

### LINKED ISSUE #8799: Add a comment field in queries
Hi,

For my clients, I monitor their MongoDB Atlas cluster using the Profiler, which shows a graph of all slow queries.
When I see a slow query, it's hard for me to know where it comes from, in the codebase. We have many coders in many projects that all use the Parse JS SDK.
MongoDB query options have a comment field.
It would be great to have it in Parse.

Thx

Olivier

### PR DESCRIPTION
**Pull request by Meglali20**
Closes: https://github.com/parse-community/parse-server/issues/8799

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, is this ready for merge?

**Comment by Meglali20** [comment]
Yes, I did run tests multiple times and they all pass.

**Comment by dplewis** [comment]
@Meglali20 the test suite runs off of a singleton server. There should be only 1 beforeAll which exist in the helper.js. Can you get this test done without an additional beforeAll and beforeEach? This commit would create more flaky tests.

**Comment by mtrezza** [comment]
Nice, I'll go ahead and merge then.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.28](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.28)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
