### PR TITLE
Should not call next when validateAuthData throw an error

### PR DESCRIPTION
**Pull request by Etto91**
### New Pull Request Checklist

this pull request is related to #7200 issue.
I added the tests.

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues/7200).

### Issue Description

Related issue:  #7200

### TODOs before merging

- [x] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Comment by davimacedo** [comment]
Thanks for the PR. Would you mind to rebase to the current version of master so we can see the tests results?

**Comment by Etto91** [comment]
tell me if what i have done is correct

**Comment by davimacedo** [comment]
Something looks wrong with the pr as it looks there are more changes than the ones you did.

**Comment by Etto91** [comment]
sorry about that...is it ok now?

**Comment by davimacedo** [comment]
Thanks for your effort in reporting this issue. Seeing the test case I can now understand your problem. Basically the problem is happening because you are throwing a generic error. You need to throw a `Parse.Error` in order to have it correctly handled by the api. So if you change this test case to something like this in your adapter it will pass and probably work as you expect:

```js
// Custom oauth provider by module

// Returns a promise that fulfills iff this user id is valid.
function validateAuthData() {
  return Promise.reject(new Parse.Error(Parse.Error.OBJECT_NOT_FOUND, 'Custom auth is invalid for this user.'));
}
function validateAppId() {
  return Promise.resolve();
}

module.exports = {
  validateAppId: validateAppId,
  validateAuthData: validateAuthData,
};
```

**Comment by Etto91** [comment]
Thank you for your reply. I have just one doubt. For example in the Facebook adapter, if the API call to Facebook fails, is throw a parse error?
I have already tried throwing a parse error but the problem still persists, at this point, i think that is a problem with webpack transpiling.

**Comment by davimacedo** [comment]
Yes. As you can see here: https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/facebook.js

Make sure you are throwing the Parse.Error of the parse package installed in your parse-server package. Maybe if you have a different parse package installed in your adapter project, you may have some problem. You can try to require parse as a peer dependency on your project or make sure the version you are using is the same that parse-server is using.

**Comment by Etto91** [comment]
Maybe I'm wrong, but if the HTTPS request to facebook fails, it throws a parse error only because the handleError function in the RESTController (parse/node) converts the responseText string to a Parse.Error. I'm using axios to make the api call and I need to catch and throw a Parse.Error instead of the axios error. 
I hope it will be useful to someone.

**Pull request closed without merging**
