### PR TITLE
3.7.1

### PR DESCRIPTION
**Pull request by davimacedo**

### CODE REVIEW

**Comment by dplewis** [comment]
@davimacedo Can you hold off on the release for a second? I want to try something

**Comment by davimacedo** [comment]
sorry @dplewis 
I've just seen the message

**Comment by davimacedo** [comment]
I think I can try to stop on travis though... let me try

**Comment by dplewis** [comment]
Its ok

**Comment by davimacedo** [comment]
done
I will remove the release as well. We can add again when you are done.

**Comment by davimacedo** [comment]
Actually.. there is no way to delete the release... but we can execute the build again on travis when you're done.. let me know then.

**Comment by dplewis** [comment]
The reason why is because the JS-SDK is failing

https://travis-ci.org/parse-community/Parse-SDK-JS/jobs/565743737

It might be related to https://github.com/parse-community/parse-server/pull/5866

**Comment by davimacedo** [comment]
I think I figured it out
https://github.com/parse-community/parse-server/pull/5871

**Comment by davimacedo** [comment]
@dplewis what do you think that we should do now? Prepare 3.7.2 and leaver 3.7.1 with no npm deploy?

**Comment by dplewis** [comment]
Prepare 3.7.2 as 3.7.1 would break builds

**Pull request merged**
