### PR TITLE
Support for Distinct Query

### PR DESCRIPTION
**Pull request by dplewis**
Ref: https://github.com/parse-community/parse-server/issues/2238, https://github.com/parse-community/parse-server/issues/2877

I added support for distinct query. Also works with nested queries.

Let me know if more tests should be added.

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart 

I realized that arrays works differently between mongo and postgres.
```
const size1 = new TestObject({size: ['S', 'M']});
const size2 = new TestObject({size: ['M', 'L']});
const size3 = new TestObject({size: ['S']});
const size4 = new TestObject({size: ['S']});
```

Mongo returns 
```
[ 'L', 'M', 'S' ]
```
PG returns
```
[ [ 'S' ], [ 'M', 'L' ], [ 'S', 'M' ] ]
```

I can make PG match the results from mongo by checking if `size` is type `Array`.

I see a problem with nested arrays on PG since I can't check the type for array.

Thoughs?

**Comment by flovilmart** [comment]
We should have the same results on both DB’s can you point to the example test?

**Comment by dplewis** [comment]
If they should be the same I'll commit a solution shortly

**Comment by dplewis** [comment]
@flovilmart I think this is OK for now

**Comment by flovilmart** [comment]
@dplewis, if we’re going with an aggregate api, do we want the distinct early on?

**Comment by dplewis** [comment]
Some users want it and it's easier to use than aggregate. What do you think?

**Comment by flovilmart** [comment]
I think we need to be careful adding new API's more over, the classes/Object is supposedly returning a list of Parse Objects, not just an array of values (which would completely break all clients)

**Comment by dplewis** [comment]
I haven't tried using distinct/aggregate on clients yet so I don't know the end results. I don't want to break clients but are their any alternatives for these features?

**Comment by dplewis** [comment]
We also can make these REST exclusive

**Comment by flovilmart** [comment]
Yeah but we need consistency.

All `/classes/ClassName` return an array of results which are Objects of type ClassName, no matter what you pass, (adding count add an additional key; `count: N`)

Addind distinct as a query param, on the same endpoint would break that stability.

However, on a new endpoint, like /aggregate/ClassName, we can guarantee that 
- it will never break client SDK's
- it ill not break the consistency of the endpoints
- it's backwards/forward compatible
- we can define a new return type for those

what do you think? The code itself look great, I'm just pondering as it's a major shift from the current API stability, having a query param that triggers a completely different return type.

**Comment by dplewis** [comment]
You bring up a lot of good points. Let go that route (no pun intended)

**Comment by flovilmart** [comment]
@dplewis even if the REST interface is a bit more verbose like


```
GET /aggregate/ClassName?distinct=key1,key2&where=...
```

it's not that bad

we can interpolate types, (key1, key2), structures etc...

**Comment by dplewis** [comment]
I understand now thanks for clarifying endpoints.

**Comment by flovilmart** [comment]
@dplewis what do you think if I close that one for now, and we'll get it merged as part of a 1st iteration for aggregations?

**Comment by dplewis** [comment]
@flovilmart Sounds good to me. Quick question should we use for mongo db.Collection.distinct() or transform distinct into $group aggregate?

**Comment by flovilmart** [comment]
Uhm, are they both the same? @tylerbrock?

**Comment by dplewis** [comment]
`GET /aggregate/ClassName?distinct=key1,key2&where=..`

`db.collection.distinct(field, query, options)`

.distinct only supports 1 field but allows for queries.

If we want to support key1, key2 we have to interpolate that into group with no query option or is there a work around.

Theres also the issue of speed map-reduce (distinct) vs aggregate (group). I haven't done much research on these options.

Thoughts?

**Comment by flovilmart** [comment]
uhm, not much thoughts on that one! Hopefully @TylerBrock can probably point out something or someone from @mongodb like @christkv could shed some light!

**Comment by dplewis** [comment]
Another option is to get rid of the `distinct=key1,key2` and only use aggregate `where...`.

**Comment by flovilmart** [comment]
perhaps we can branch on the use case no? use .distinct() if certains params are passed otherwise use aggregation

**Comment by dplewis** [comment]
So the use cases would be

Distinct one key
use `.distinct()` and allows `where` for queries like find()

Distinct multiple keys
Use aggregates and ignore `where` as it will be overridden

Aggregate
Checks for special keys `$match`, `$group`, `$project` in `where` etc...

How does that sound?

**Comment by flovilmart** [comment]
> Distinct multiple keys
> Use aggregates and ignore where as it will be overridden

What do you mean it will be overriden? 

> Aggregate
> Checks for special keys $match, $group, $project in where etc...

Actually they won't be in the where, but:

GET /aggregate/MyClass?match=...&group=...&where=...

And in that case match and where are equivalent no? As they filter the data set.

Then the order of aggregation matters a lot, I'm not sure we can guarantee it through query params.

**Comment by dplewis** [comment]
> GET /aggregate/MyClass?match=...&group=...&where=...

Makes sense.

> Then the order of aggregation matters a lot

Does it?

**Comment by flovilmart** [comment]
I believe itMa à pipeline, nothing prevents you to run match after group etc..:

**Pull request closed without merging**
