### PR TITLE
fix: GridFS file storage doesn't work with certain `enableSchemaHooks` settings

### LINKED ISSUE #8466: GridFS fails with `enableSchemaHooks` is not supported
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

As mongoOptions are now set to Parse Server's default options, `enableSchemaHooks` can be passed to the GridFSAdapter

### Steps to reproduce

- Start Parse Server on alpha
- Attempt to save a file

### Actual Outcome

- Rejected

### Expected Outcome

- Should resolve

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

GridFS does not work on alpha due to `enableSchemaHooks` is not supported

Closes: #8466

## Approach

Strips out invalid options

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
Note that issue goes back to Parse Server 5, and doesn't only affect alpha, see https://github.com/parse-community/parse-server/issues/8466#issuecomment-1461539482. Hence this should be a `fix` commit.

**Comment by mtrezza** [comment]
@omairvaiyani thanks for opening https://github.com/parse-community/parse-server/pull/8470. @dblythy is there anything from that PR that you can incorporate into this PR?

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.12](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
