### PR TITLE
Prep release 4.2

### PR DESCRIPTION
**Pull request by acinader**

### CODE REVIEW

**Comment by TomWFox** [comment]
I was going to start a petition to switch to a changelog style like the JS SDK one with headings for new features, improvements, fixes, security.

I find it much more readable and the improvement would be more noticeable now the parse-server releases are consistently big.

**Comment by acinader** [comment]
1. this one is already done, so i'd like to start with the next
2. i'd like something automated.  just inserting a link to the github commit list would be fine with me and then if there was something noteworthy, it could be added ad-hoc.

**Comment by TomWFox** [comment]
1. that's cool, just wanted to open the discussion
2. I agree, I've been looking into different options for automation. I suppose it's about quickly showing to the dev what has changed (with that in mind I probably wouldn't include details about changes to unit tests - not to discredit that work!!). Having said that because we use squash & merge the commit list generally isn't too bad 🤷‍♂️

**Comment by dplewis** [comment]
@acinader A PR was merged. Can you update from master and include it in the release?

https://github.com/parse-community/parse-server/pull/6344

**Comment by acinader** [comment]
Will do @dplewis

**Comment by acinader** [comment]
@TomWFox could you please give the changelog a quick look again....

**Comment by cbaker6** [comment]
@acinader do you think #6376 can be added? @dplewis added some test cases for it.

**Pull request merged**
