### PR TITLE
test: fix failing tests after removal of session token

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Merging security fix 834ae366f98179c99332ea90692d943dd00851b1 introduced failing tests.

Related issue: #n/a

### Approach
Fixes failing tests.

### TODOs before merging

n/a

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this ready for review?

**Review by mtrezza — APPROVED** [review]
Looks good, I sense some Swift syntax here 🙂 I take it that the 4.10.4 release is fine, it was just the tests themselves? How was this overlooked, if the tests passed locally 🤔

**Comment by dblythy** [comment]
>  I take it that the 4.10.4 release is fine, it was just the tests themselves?

Yep! I guess the `?` operator isn't available until Node 14.

> I assume these were last-minute changes after the last local test run

It was my mistake for running the tests only on Node 16!

**Comment by mtrezza** [comment]
Right, so it should probably be at least one local test for:
- MongoDB
- Postgres
- lowest Node version in CI (Node 12)
- highest Node version in CI (Node 15)

**Comment by dblythy** [comment]
Actually I’m mistaken - it would’ve been Node 15 / npm 6 otherwise lockfile would be v2

**Comment by mtrezza** [comment]
Got it, thanks

**Comment by FransGH** [comment]
Could it be that this is not in the 4.10.4 release? Running the tests seem to fail on exactly this issue, see #7658

**Comment by mtrezza** [comment]
@FransGH yes, this was not merged into the 4.x branch but into `master`, now `alpha`. The `release-4.x` branch is currently maintained as a long-term support branch and only receives bug fixes, like the one you are following. This is the same PR for the 4.x branch, but it has become stale: https://github.com/parse-community/parse-server/pull/7600

**Comment by FransGH** [comment]
I'm currently running the tests with node 14, so far seen the same error as in #7600 but they are still running... 

Basically looks like the 4.x.x branch won't work with the current test-workflows as these require node 10.
How would a possible future 4.10.x release update work, for example with some critical security fix?

**Comment by mtrezza** [comment]
Let's discuss in https://github.com/parse-community/parse-server/pull/7658

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
