### PR TITLE
WIP: Initial feature for OTP / authenticator passwords

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by awgeorge** [comment]
> Implementing #2FA apps how do you store the TOTP secret so it is safe in case of a data leak? The server needs the secret in plain text to compare the token. What's your strategy?

Tokens should be secured at rest, check out 7.5 of the specification: https://www.ietf.org/rfc/rfc4226.txt. If the `master key` isn't already in the database, this could be used as the encryption key (not sure how often people change this key).

Depending on how you want the 2FA to be used, IE (only at login) you could use composite keys (Section 8), the user's password/pin is used to generate the token, meaning the database effectively only stores a seed.

**Comment by flovilmart** [comment]
Ok, we could introduce a runtime encryption key for the tokens, different from the master key. Or just use the master key. What do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by awgeorge** [comment]
Good idea - I'm looking for an email based solution - (although I want a single auth, email only, passwordless solution)

**Comment by flovilmart** [comment]
@acinader @dplewis closing this one as I don’t intend to work on it anymore 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by acinader** [comment]
@awgeorge any interest in getting this across the finish line?  I can review and get up to speed if it is still something you'd like to see in the product?

**Comment by awgeorge** [comment]
This is something I’m interested in - I’ll take a look and see what’s left to get this implantation merged.

—

**Comment by brianmwadime** [comment]
> This is something I’m interested in - I’ll take a look and see what’s left to get this implantation merged. —
Hey @awgeorge, were you able to get this to the finish line?

**Comment by awgeorge** [comment]
Not at this time, feel free to take it on. Thanks.

**Comment by brianmwadime** [comment]
Alright @awgeorge. Thanks for the update.

**Comment by tehsunnliu** [comment]
Hey guys! is it finished yet? If anyone is interested we can do it together.

**Pull request closed without merging**
