### PR TITLE
ci: fix Node version specific tests not running properly in local environment

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Fix implemented in #7980 do not use Node standard version APIs.

Related issue: #7980, #7978

### Approach
Use the correct API; process.version

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by Moumouls** [comment]
Hi, @mtrezza I saw that you self merged a fix for the GQL tests. #7980

The NODE_VERSION is custom and related to the CI env. Node version should be accessed by `process.version` otherwise it will not work correctly out of the CI env.

Also, I'm interested to know why #7980 PR skipped the review team or at least one approval?

**Comment by mtrezza** [comment]
It works the same as  `it_only_mongo_version` which is a good check for whether the CI is set up correctly. It seems the node version is not defined in the package script command. I wonder what's better, add the node version to the test command or ignore the CI defined node version in the test.

**Comment by Moumouls** [comment]
Yes mongo has a default env value. I think here we just need to use the standard node API. It works perfectly.

> add the node version to the test command

I think it's not a good idea, for example, I use `nvm` to switch between node versions on my local setup. The env will add unnecessary overhead and node standard API is capable to retrieve the correct version.

**Comment by mtrezza** [comment]
The CI should provide the authoritative definition of the node version, so it is an additional check to use the CI defined node version. But maybe for developers it's more convenient to remove that check and run tests based on node process version instead of adding more scripts to the package.json. So let's go with your suggestion while keeping in mind that we open a new source for bugs in the CI workflow.

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
I adapted the PR title to be more descriptive and changed the incorrect commit type. I suggest you make yourself familiar with our contribution guide to find out more about how commit types are used.

I deleted n/a TODOs, please mind the following note in the PR template:
> Delete suggested TODOs that do not apply to this PR.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-server/releases/tag/5.3.0)

**Pull request merged**
