### PR TITLE
feat: liveQuery support for unsorted distance queries

### LINKED ISSUE #7480: withinKilometers withinMiles withinRadians not working with Live Query
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I want to retrieve object only in a specific radius of the user current Position.
I use Live Query to get when object enter, update, leave theses conditions in real time.

However when i write a query with withinKilometers / withinMiles / withinRadians the Live Query never triggered when the Object has his GeoPoint enter / update / leave the specific radius.

### Steps to reproduce

1) Setup a parse-server with Live Query
2) Create a class with a GeoPoint column (in my example, my column is "location")
3) Create a client, i tried on Parse Flutter SDK and Parse Javascript SDK
4) Connect the client, make a Parse Query with a subscription based on [withinKilometers](http://parseplatform.org/Parse-SDK-JS/api/3.2.0/Parse.Query.html#withinKilometers) / withinMiles / withinRadians conditions
My javascript example :

```<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test</title>
    <script src="https://unpkg.com/parse/dist/parse.js"></script>
    <script>
        main();
        async function main() {
            Parse.initialize("xxxxxxxxxxxxx");
            Parse.serverURL = 'http://192.168.X.X:1337/parse'

            var query = new Parse.Query('TestObject');
            query.withinKilometers("location", new Parse.GeoPoint({latitude: 45, longitude: 2}), 1, false);
            var subscription = await query.subscribe();

            subscription.on('open', () => {
                console.log('subscription opened');
            });

            subscription.on('update', (object) => {
                console.log(object);
                console.log('object updated');
            });

            subscription.on('enter', (object) => {
                console.log(object);
                console.log('enter updated');
            });

            subscription.on('leave', (object) => {
                console.log(object);

                console.log('object left');
            });

            subscription.on('delete', (object) => {
                console.log(object);

                console.log('object deleted');
            });

            subscription.on('close', () => {
                console.log('subscription closed');
            });
        }
    </script>
</head>
<body>
    <p>Test</p>
</body>
</html>
```

### Actual Outcome

My Live Query subscription is never triggered when the GeoPoint respect the subscription conditions.

**If i replace the .subscription() by .find() the query worked fine, but this is not i want cause i need Live Query**

### Expected Outcome

I expect to get my `TestObject` when his location is update and still respect my subscription condition.

In my example : a `TestObject` with "location" `Parse.GeoPoint({latitude: 45, longitude: 2})` must be return to client because the client have the same position and the withinKilometers is respected.
(see my example line `query.withinKilometers("location", new Parse.GeoPoint({latitude: 45, longitude: 2}), 1, false);`)

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [x] 🧐 [I submitted a PR with a failing test case.](https://github.com/parse-community/parse-server/pull/7526)

### Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Windows 10.0.19043`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Clients
- SDK JavaScript version: `3.3.0`
- SDK Flutter version: `3.1.0`

### Logs

No log

Regards !

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/parse-server/issues/7480

### TODOs before merging

- [x] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@dplewis thanks for the PR; please request review from `@parse-community/server-review` instead of individual members, check the boxes at the top and remove TODOs that don’t apply in the template.

**Comment by dplewis** [comment]
Sorry it's a habit. I'll send it to the team in the future

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.28](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.28)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Pull request merged**
