### PR TITLE
Disable test suites using UUID

### PR DESCRIPTION
**Pull request by ddrechse**
## Pull Request

This change uses the new testExclusionList feature to disable tests

## Issue
Allows uptake of the new OracleStorageAdapter

Closes: 

## Approach
These are the testExclusions required for the OracleStorageAdapter

## Tasks
None

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
These changes are too vast, as they are breaking the line with `it_id` and indent all the test code. This makes it difficult to review the PR and ensure the there are no (accidental) changes in the test themselves. 

For example:

```
it_id('75c39ae3-06ac-4354-b321-931e81c5a927')(
    'properly set badges to 1 with complex query #2903 #3022',
```

Not sure where these line breaks come from, I assume from your local lint or prettier settings? I don't think it's our prettier `printWidth: 100` (which we should remove anyway), because running `npm run prettier` modifies a lot more unrelated code.

Edit: I'll go ahead and rewrite these changes...

**Comment by ddrechse** [comment]
When I pushed the PR, it ran eslint as part of the pre checks.  Ran it again in my branch

```

npm run lint                                        

> parse-server@7.3.0-alpha.1 lint
> flow && eslint --cache ./

No errors!
ddrechse@ddrechse-mac parse-server % git branch
  alpha
* useTestExclusionList
```

And this is .eslintrc.json

```
{
    "root": true,
    "extends": "eslint:recommended",
    "env": {
        "node": true,
        "es6": true
    },
    "parser": "@babel/eslint-parser",
    "plugins": [
        "flowtype"
    ],
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "requireConfigFile": false
    },
    "rules": {
        "indent": ["error", 2, { "SwitchCase": 1 }],
        "linebreak-style": ["error", "unix"],
        "no-trailing-spaces": 2,
        "eol-last": 2,
        "space-in-parens": ["error", "never"],
        "no-multiple-empty-lines": 1,
        "prefer-const": "error",
        "space-infix-ops": "error",
        "no-useless-escape": "off",
        "require-atomic-updates": "off",
        "object-curly-spacing": ["error", "always"]
    },
    "globals": {
        "Parse": true
    }
}
```

Hopefully, I can configure these setting correctly and run with the fix option
Another approach is to remove all the new lines in the it_id definitions

Let me know

**Comment by mtrezza** [comment]
No worries; I'm correcting it in https://github.com/parse-community/parse-server/pull/9205, as to keep your PR unchanged for reference; found some other unrelated issues along the way too. I doubt it's eslint, I think it's prettier that creates the line breaks, because our lint-fix script doesn't create them neither

**Comment by ddrechse** [comment]
Ok let me know.
I was trying to make those it_id's one line, i.e
```
-  it_id('af1111b5-3251-4b40-8f06-fb0fc624fa91')(
-    'should support legacy parse.com audience fields',
+  it_id('af1111b5-3251-4b40-8f06-fb0fc624fa91')('should support legacy parse.com audience fields',
     done => {
       const database = Config.get(Parse.applicationId).database.adapter.database;
```

But i swear prettier or eslint is reverting, imho

```
ddrechse@ddrechse-mac parse-server % git commit
husky > pre-commit (node v20.0.0)
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.

✔ Preparing...
✔ Running tasks...
✖ Prevented an empty git commit!
✔ Reverting to original state because of errors...
✔ Cleaning up... 

  ⚠ lint-staged prevented an empty git commit.
  Use the --allow-empty option to continue, or check your task configuration
```

Ok 
let me know :)

**Comment by mtrezza** [comment]
It may be husky, it could be that prettier runs in the pre-commit handler. I'll go ahead and fix this...

**Comment by mtrezza** [comment]
@ddrechse Could you please try to run the Oracle adapter CI with https://github.com/parse-community/parse-server/pull/9205? I tried to use all your test IDs from this PR here. If it works, then I'll go ahead and merge https://github.com/parse-community/parse-server/pull/9205 and we can close this PR here.

**Comment by mtrezza** [comment]
Superseded by https://github.com/parse-community/parse-server/pull/9205

**Pull request closed without merging**
