### PR TITLE
docs: add LTS explanation and open vulnerabilities to README

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

- no branch overview
- LTS branches may have open vulnerabilities that we leave to the community to fix; there is currently no overview for these

Related issue: #n/a

### Approach

- add branch explanation
- add instructions how to see open LTS vulnerabilities

### TODOs before merging
n/a

### CODE REVIEW

**Comment by mtrezza** [comment]
Note: merge after fixes

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.19)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Pull request merged**
