### PR TITLE
perf: Improve performance of recursive pointer iterations

### PR DESCRIPTION
**Pull request by chderen**
## Pull Request

Code change for performances.

Instead of creating and updating the answer array on each iterations, use map function.

### CODE REVIEW

**Comment by mtrezza** [comment]
Do you have any proof that this is actually better performing and not worse?

**Comment by chderen** [comment]
I tested on my computer. for arrays grater then 1000 there is a big diff

**Comment by mtrezza** [comment]
Could you share the metrics and tool you used for performance measurement? There may be factors in the test set-up that would need to be considered (caching, etc) to know how reliable the test results are.

**Comment by chderen** [comment]
I have isolated the relevant code, and created a test here [https://jsbench.me/talmgdggir/1](https://jsbench.me/talmgdggir/1)

**Review by mtrezza — APPROVED** [review]
Thanks for sharing the performance test; looks good. Maybe you can improve the PR title to explain the improvement in more practical terms.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)

**Pull request merged**
