### PR TITLE
refactor: Upgrade body-parser from 1.20.1 to 1.20.2

### PR DESCRIPTION
**Pull request by parseplatformorg**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade body-parser from 1.20.1 to 1.20.2.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **1 version** ahead of your current version.
- The recommended version was released **3 months ago**, on 2023-02-22.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>body-parser</b></summary>
    <ul>
      <li>
        <b>1.20.2</b> - <a href="https://snyk.io/redirect/github/expressjs/body-parser/releases/tag/1.20.2">2023-02-22</a></br><ul>
<li>Fix strict json error message on Node.js 19+</li>
<li>deps: content-type@~1.0.5
<ul>
<li>perf: skip value escaping when unnecessary</li>
</ul>
</li>
<li>deps: raw-body@2.5.2</li>
</ul>
      </li>
      <li>
        <b>1.20.1</b> - <a href="https://snyk.io/redirect/github/expressjs/body-parser/releases/tag/1.20.1">2022-10-06</a></br><ul>
<li>deps: qs@6.11.0</li>
<li>perf: remove unnecessary object clone</li>
</ul>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/expressjs/body-parser/releases">body-parser GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>body-parser</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/ee91374eae1555af679550b1d2fb5697d9924109">ee91374</a> 1.20.2</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/368a93a613a1ac6cbdec9694f4018e707b3c1f50">368a93a</a> Fix strict json error message on Node.js 19+</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/038587229c4409c7939d73df804c115da37fb3e8">0385872</a> deps: raw-body@2.5.2</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/2c35b413c25dc9212aaf6486b2d0d6e0b8e2e6f9">2c35b41</a> build: eslint@8.34.0</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/f0646c2b13e85a1dec771bc7a1239f4e3a25c582">f0646c2</a> build: Node.js@18.14</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/f345fb1ff2e74045010d83bce30ef99950a709c2">f345fb1</a> build: Node.js@14.21</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/6842efc2e68b986825d0072b7cf27e9921599044">6842efc</a> deps: content-type@~1.0.5</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/5af7315dd00c300be5ac4b12c023ff670e2c8d1a">5af7315</a> build: eslint-plugin-promise@6.1.1</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/8e605b3d9f3a1bc59793b20c3213f2ac4ff4f584">8e605b3</a> build: supertest@6.3.3</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/cba6e770d5e5654e2015e532e20b44d0a37e522e">cba6e77</a> build: mocha@10.2.0</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/6a464ab7b8556a4d5743520f27da703cacc22997">6a464ab</a> build: eslint-plugin-import@2.27.5</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/7ebf276354c63d66fc4120b7f32821d88657d28e">7ebf276</a> build: eslint@8.32.0</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/69bb649e68ae7419094dc84cbca818c15ee6cfd3">69bb649</a> build: Node.js@16.19</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/8ff995f9697afef32d89905e56cb48c379894880">8ff995f</a> docs: switch badges to badgen</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/850832feac26b963cc54941263cbf8a211e2de6d">850832f</a> build: Node.js@18.13</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/dad8f345c7d8424cb71b18a6060198040ad5ec04">dad8f34</a> build: actions/download-artifact@v3</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/b17df320b7fc9203f88ea305626d3dd11c6d881d">b17df32</a> build: use $GITHUB_OUTPUT for environment list</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/d22513a246fd50c593bd0783ee34082a13738365">d22513a</a> build: actions/upload-artifact@v3</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/9f44f7b8b42261dd1b7c99137f1bb30954a1d0c8">9f44f7b</a> build: actions/checkout@v3</li>
      <li><a href="https://snyk.io/redirect/github/expressjs/body-parser/commit/48e18ea00b40dfdd89d18320e368f7b7f138f654">48e18ea</a> build: mocha@10.1.0</li>
    </ul>

   <a href="https://snyk.io/redirect/github/expressjs/body-parser/compare/830bdfbee021d540a742de857dcbd43f40563a02...ee91374eae1555af679550b1d2fb5697d9924109">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?pkg&#x3D;body-parser&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
