### PR TITLE
feat: Upgrade to @parse/push-adapter 6.4.0

### LINKED ISSUE #256: regeneratorRuntime is not defined
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Parse-Server is not starting after update to parse 5.2.0

### Steps to reproduce

Update to parse 5.2.0

### Actual Outcome

Should work like before

### Expected Outcome

Should work like before

###  Environment

Server
- Parse Server version: `7.1.0`
- Operating system: `Docker image node:20.15.0-bookworm`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local / k8s`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `mongo:7-jammy`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local / k8s`

Client
- Parse JS SDK version: `5.2.0`

### Logs

***/node_modules/@parse/push-adapter/lib/WEB.js:59
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(data, devices) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at ***/node_modules/@parse/push-adapter/lib/WEB.js:59:50
    at ***/node_modules/@parse/push-adapter/lib/WEB.js:134:6
    at Object.<anonymous> (***/node_modules/@parse/push-adapter/lib/WEB.js:202:2)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (***/node_modules/@parse/push-adapter/lib/ParsePushAdapter.js:29:12)

Node.js v20.15.0

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

The push adapter now supports ES6 and Node 22

```
*/node_modules/@parse/push-adapter/lib/WEB.js:59
var _ref = _asyncToGenerator( /#PURE/regeneratorRuntime.mark(function _callee(data, devices) {
^

ReferenceError: regeneratorRuntime is not defined
at /node_modules/@parse/push-adapter/lib/WEB.js:59:50
at /node_modules/@parse/push-adapter/lib/WEB.js:134:6
at Object. (/node_modules/@parse/push-adapter/lib/WEB.js:202:2)
at Module._compile (node:internal/modules/cjs/loader:1358:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
at Module.load (node:internal/modules/cjs/loader:1208:32)
at Module._load (node:internal/modules/cjs/loader:1024:12)
at Module.require (node:internal/modules/cjs/loader:1233:19)
at require (node:internal/modules/helpers:179:18)
at Object. (/node_modules/@parse/push-adapter/lib/ParsePushAdapter.js:29:12)
```
Closes: https://github.com/parse-community/parse-server-push-adapter/issues/256

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza The server tried to transcompile the ES module but is not supported. I add Babel and CommonJS support back to the push adapter.

https://github.com/parse-community/parse-server-push-adapter/pull/266

**Comment by mtrezza** [comment]
> Instead change the require of /home/runner/work/parse-server/parse-server/node_modules/@parse/push-adapter/src/index.js in /home/runner/work/parse-server/parse-server/lib/Controllers/index.js to a dynamic import() which is available in all CommonJS modules.

Can't we do this instead of reverting the push adapter repo to CommonJS? Maybe we support both modules and CommonJS with a try/catch where it `require` and if that fails as it does above uses dynamic import?

```js
let module;
let modulePath;

try {
  module = require(modulePath);
} catch (err) {
  if (err.code === 'ERR_REQUIRE_ESM') {
    import(modulePath).then(mod => module = mod)
  } else {
    throw err;
  }
}
```

And we could write that as a method so we can re-use this in the future for other imports. Haven't tried this out though.

**Comment by dplewis** [comment]
The trick here is /**lib**/Controllers/index.js. The **lib** folder is autogenerated by babel. I'm not sure how that can be done. To be honest this is my first time using ESM.

**Comment by mtrezza** [comment]
I've added some code above, not sure if you're seen it.

**Comment by dplewis** [comment]
Oh thanks, let me try it out

**Comment by mtrezza** [comment]
It's an async import, as you have probably noticed. So this would need to go into an async function. If you paste it as-is it may be flaky, as the import sometimes may not have finished before the module is accessed.

**Comment by dplewis** [comment]
I noticed and the Server doesnt' support top level await. The controllers are loaded in the `ParseServer` constructor so adding it to an async function is out of the question unless we do some rewriting.

**Comment by mtrezza** [comment]
Here's a better version:

```js
async function loadModule(modulePath) {
  let module;

  try {
    module = require(modulePath);
  } catch (err) {
    if (err.code === 'ERR_REQUIRE_ESM') {
      module = await import(modulePath);
    } else {
      throw err;
    }
  }

  return module;
}
```

**Comment by dplewis** [comment]
@mtrezza I keep running into `Error: Adapter prototype don't match expected prototype`. Can you see if you can get it to work?

**Comment by dplewis** [comment]
@mtrezza This is ready for review! I used `6.4.0` in production and it works.

**Review by mtrezza — APPROVED** [review]
Wow, cool, I was trying around but got stuck in the async refactoring, glad you were able to fix this.

**Comment by mtrezza** [comment]
So this can be closed thanks to https://github.com/parse-community/parse-server/pull/9182#issuecomment-2213847850, right?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.2.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.2.0](https://github.com/parse-community/parse-server/releases/tag/7.2.0)

**Comment by jaysonng** [comment]
Hi all. I just tried to update from parse-server 6.5.5 to 7.2.0 and got this error. 

```
ReferenceError: regeneratorRuntime is not defined
    at /Users/jayson/Projects/Busog/parse-server/node_modules/parse-server-api-mail-adapter/lib/ApiMailAdapter.js:133:56
    at /Users/jayson/Projects/Busog/parse-server/node_modules/parse-server-api-mail-adapter/lib/ApiMailAdapter.js:166:6
    at Object.<anonymous> (/Users/jayson/Projects/Busog/parse-server/node_modules/parse-server-api-mail-adapter/lib/ApiMailAdapter.js:675:2)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/jayson/Projects/Busog/parse-server/node_modules/parse-server-api-mail-adapter/lib/index.js:25:46)

Node.js v18.17.0
```

was this not supposed to happen at 7.2.0?

**Pull request merged**
