### PR TITLE
fix aggregate geoNear with date query

### PR DESCRIPTION
**Pull request by mtrezza**
added failing test case

- this is the test case only without fix

### CODE REVIEW

**Comment by mtrezza** [comment]
@dplewis Could you take a look at this?

Test before the fix failed as expected.
Test after the fix fails with: 

> Unhandled promise rejection: TypeError: Cannot read property 'split' of undefined

I cannot find out where that split is.
Interestingly, locally the fix works locally with a query from cloud code.

**Comment by dplewis** [comment]
What version of Mongo are you running locally?

**Comment by mtrezza** [comment]
4.2.3

**Comment by mtrezza** [comment]
I am using VS Code to debug, but I didn't manage to set breakpoints when testing, or even run only a single test using the Test Explorer instead of all tests of a file with `npm test x.spec.js`. Therefore I am having a hard time to find the issue.

**Comment by mtrezza** [comment]
@dplewis Any help appreciated, I am stuck here unfortunately :/

**Comment by mtrezza** [comment]
@dplewis I should clarify that the test fails also locally with he same error.
I tried it with mongodb 4.0.4 mmapv1 and mongodb 4.2.3 wiredTiger.

However, the code itself works and returns the correct results when running a query in cloud code.
So maybe the test only fails because of some mock up for the test environment.

**Comment by mtrezza** [comment]
The error was the missing geo index, which is required for a `$geoNear` query.
This is may be the reason why there was not a single `geoNear` test case in parse server.

Test is passing.

**Comment by mtrezza** [comment]
The geo near query failed due to missing geo index, which is required for `geoNear`.

Ready to merge.

**Comment by mtrezza** [comment]
@acinader Can we get this into the next release?

**Comment by matheusdavidson** [comment]
Hey Guys, i think this broke geoNear. 

I had `parse-server@4.2.0` installed here when i tried to use geoNear aggregation with a very basic query and got this error: `MongoError: query must be an object`

I tried the same query directly on mongo and it worked, the query was very basic just to test, after searching i saw that this PR changed geoNear so i tried the version before(4.1.0) and it worked with the same query, went back again to 4.2.0 to confirm and got the same error.

This is the pipeline i was trying:
```typescript
const query: any[] = [
    {
        geoNear: {
            near: [-73.99279, 40.719296],
            distanceField: 'distance',
            maxDistance: 1000,
            spherical: true
        }
    }
];
```
@mtrezza @dplewis

**Comment by matheusdavidson** [comment]
I'm running `mongo v4.2.3` and `node v12.16.1` by the way.

**Comment by matheusdavidson** [comment]
I think maybe you forced the `query` option(which is optional) to be passed to the `geoNear` object so as i'm not using it, its value is not an object, maybe thats why the error says query must be an object.

**Comment by mtrezza** [comment]
@matheusdavidson Thanks for reporting, can you please open a new issue regarding this and reference this PR? I will look into this in the meanwhile.

**Comment by mtrezza** [comment]
Interesting, I added test cases without the `query` parameter and tested against mongodb 4.0.4 and 4.2.3. and tests passed. #6696

**Comment by matheusdavidson** [comment]
Strange, had another team member with that same problem with a version of our app without downgrading to 4.1.0. geoNear won't work anymore in the latest version

**Comment by mtrezza** [comment]
@matheusdavidson Are you or your team member able to replicate or observe this currently? It could also depend on the version of nodejs or mongodb driver.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mtrezza** [comment]
@matheusdavidson Can you please open an issue for this and post your findings there?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matheusdavidson** [comment]
i'm gonna do that. Just had the same problem now, will have to lock the version on 4.1.0 on all projects here.

**Comment by mtrezza** [comment]
@matheusdavidson Do you have any update on this issue? If not, I will go ahead and close the related [PR](https://github.com/parse-community/parse-server/pull/6696).

**Comment by matheusdavidson** [comment]
Hey @mtrezza, i didn't had time to see why this is happening but i'm sure the PR broke geoNear as i stated, for now what i did was downgrade all the projects to 4.1.0. Had lots of late projects and couldn't spend more time on this. Will open an issue in the future.

**Comment by mtrezza** [comment]
@matheusdavidson Since I was not able to reproduce this issue with the test cases in https://github.com/parse-community/parse-server/pull/6696, I added a potential fix for this potential issue by changing:

```js
if (stage.$geoNear) {
   stage.$geoNear.query = this._parseAggregateArgs(schema, stage.$geoNear.query);
}
```

to 

```js
if (stage.$geoNear && stage.$geoNear.query) {
   stage.$geoNear.query = this._parseAggregateArgs(schema, stage.$geoNear.query);
}
```

So `stage.$geoNear.query` is not set to `undefined` anymore.

It would be great if you could upgrade a project too confirm that it fails and then deploy a Parse Server version with PR  https://github.com/parse-community/parse-server/pull/6696 merged. Then we'd know for sure whether the issue is solved.

**Comment by matheusdavidson** [comment]
@mtrezza thank you for adding the fix, i will upgrade one of the projects and test today.

**Comment by mtrezza** [comment]
@matheusdavidson That would be great. Note that the PR is not merged into master yet, but you can use the PR branch.

**Comment by matheusdavidson** [comment]
Hey @mtrezza, sorry it took so long for me to test. That solves my problem, thank you for your efforts!!

**Comment by mtrezza** [comment]
@matheusdavidson Thanks for your feedback, glad it worked.

**Pull request merged**
