### PR TITLE
Attempt to get Travis to deploy to npmjs

### PR DESCRIPTION
**Pull request by acinader**
Use deprecated `skip_cleanup: true`
as `cleanup: false` doesn't
appear to be working

### CODE REVIEW

**Comment by dplewis** [comment]
I think the previous build was good it. The release didn't tag properly.

**Comment by acinader** [comment]
i don't think so.  if you expand the deploy step, even though it says it worked, you can see that npm is failing because it doesn't have babel

**Comment by acinader** [comment]
why do you think it didn't tag properly??

**Comment by acinader** [comment]
image

**Comment by dplewis** [comment]
https://travis-ci.org/parse-community/parse-server/jobs/657209717

Screen Shot 2020-03-02 at 12 36 26 PM

**Comment by acinader** [comment]
image

**Comment by acinader** [comment]
i'm optimistic that this change will fix it.

**Comment by dplewis** [comment]
Do you have a link to that job?

**Comment by acinader** [comment]
https://travis-ci.org/parse-community/parse-server/jobs/656523701

**Comment by acinader** [comment]
your link is to the pr merge, not the new tag.

**Pull request merged**
