### PR TITLE
Added docs for objectIdSize

### PR DESCRIPTION
**Pull request by jcguarinpenaranda**

### CODE REVIEW

**Comment by steven-supersolid** [comment]
Should perhaps add a note about what the default is if omitted

**Comment by jcguarinpenaranda** [comment]
oh yes you are right, I will change the description today or tomorrow night


2018-01-29 8:06 GMT-05:00 Steven Shipton <notifications@github.com>:

**Comment by milesrichardson** [comment]
Be careful setting `objectIdSize` to non-default values. There are a few side effects, see here: https://github.com/parse-community/parse-server/issues/4363

**Comment by flovilmart** [comment]
Thanks!

**Pull request merged**
