### PR TITLE
perf: reduce database operations when using the `constant` parameter in Cloud Function validation

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

When using the `constant` param for the inbuilt validator, the cloud code runs `req.object.set(key, req.original.get(key))`, which causes unnecessary database OPs as it thinks that `key` needs to be updated.

Related issue: #7534

### Approach

Uses the preferred JS method `.revert`

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Is this really a bug fix or can we classify it as `perf` (performance improvement)? Because I seems the feature worked before as well, but now it’s saving some unnecessary database ops, right?

**Comment by dblythy** [comment]
Yes `perf` is correct

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.1-alpha.2](https://github.com/parse-community/parse-server/releases/tag/5.2.1-alpha.2)

**Comment by dblythy** [comment]
Thanks @mtrezza 👑 👏

**Pull request merged**
