### PR TITLE
Add option to support push scheduling

### PR DESCRIPTION
**Pull request by felipemobile**
Add a configuration flag on the server to handle the availability of
push scheduling support.

### CODE REVIEW

**Comment by flovilmart** [comment]
Thanks! You should probably read the value from there too: https://github.com/parse-community/parse-server/blob/master/src/Routers/FeaturesRouter.js#L33

**Comment by flovilmart** [comment]
Also, we need to probably update:

https://github.com/parse-community/parse-server/blob/master/src/Controllers/PushController.js#L52

and [here](https://github.com/parse-community/parse-server/blob/master/src/Controllers/PushController.js#L52) to prevent enqueueing if "push_time" is set and valid.

**Comment by felipemobile** [comment]
[This](https://github.com/parse-community/parse-server/blob/master/src/Controllers/PushController.js#L52) is the hard part.. Can you give me an idea of how I can get started? I mean... store the message in _PushStatus collection.

**Comment by flovilmart** [comment]
> I mean... store the message in _PushStatus collection.

This is done in the PushStatus handler, so nothing to do here, besides skipping :)

**Comment by felipemobile** [comment]
@flovilmart Hahaha. Life is so difficult to some people but easy to others :)

**Pull request closed without merging**
