### PR TITLE
test: fix failing tests after removal of session token (#7599)

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Backport https://github.com/parse-community/parse-server/pull/7599

Related issue: https://github.com/parse-community/parse-server/pull/7599

### Approach
n/a

### TODOs before merging
n/a

### CODE REVIEW

**Comment by mtrezza** [comment]
@dblythy How strange, could you take a look why this fails when being backported to 4.x?

**Comment by dblythy** [comment]
Rather odd. I can have a look tomorrow, maybe `nextTick` is resolving too soon?

**Comment by mtrezza** [comment]
It's continues to fail, I already reran the tests.

**Comment by mtrezza** [comment]
Closing in favor of https://github.com/parse-community/parse-server/pull/7599

**Pull request closed without merging**
