### PR TITLE
Remove MongoDB 3.6 support (EOL)

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
MongoDB 3.6 reached its EOL support date in April 2021.

Related issue: (n/a, meta)

### Approach
MongoDB 3.6 support is removed from official Parse Server support.

This does not reduce the number of CI tests, because it was the only test with MMAPv1 engine and standalone topology. Consequently, that test now runs with MongoDB 4.0.

### TODOs before merging

- [x] Add entry to changelog
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by dplewis** [comment]
> MMAPV1:  This is the original storage engine for MongoDB, introduced in the first release, but from version 4.0 it is deprecated

I believe that test can be removed

**Comment by mtrezza** [comment]
We don't want to support MMAP and standalone anymore?

**Comment by mtrezza** [comment]
@dplewis If you are fine with https://github.com/parse-community/parse-server/pull/7315#issuecomment-812564739 I'll merge this later today.

**Review by davimacedo — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
