### PR TITLE
GraphQL with graphql-helix, graphql-ws and envelop

### PR DESCRIPTION
**Pull request by n1ru4l**
Hi from @the-guild-org !

We’ve recently built and open-sourced a new plugin system for GraphQL that we think would be a huge improvement for Parse developers - https://github.com/dotansimha/envelop

The goal of the library was to have a tool to handle GraphQL execution flow, allowing developers to develop, share and extend the behavior of their server implementation, in a standard, simple way. Basically the missing GraphQL execution plugin system.

Here are some possible benefits for Parse developers from the Envelop migration:
- Performance - Envelop is up to date and more performant and can use [graphql-helix](https://github.com/contrawork/graphql-helix) instead of the aging expressGraphQL and Apollo Server Express.  You could also improve performance by easily adding graphql-jit support or easily cache any GraphQL phase.
- Customization - users could customize their Parse GraphQL setup without hurting the initial easy experience
- Plugins - Any Parse user could get easy access [to all the plugins](https://github.com/dotansimha/envelop#available-plugins) in the ecosystem if they wish
- Better GraphQL Subscription implementation and support for the new [graphql-ws library](https://the-guild.dev/blog/graphql-over-websockets) and protocol and not only the old and unmaintained subscriptions-transport-ws and graphql-subscriptions libraries, and even Subscriptions over [HTTP SSE thanks to graphql-helix](https://dev.to/danielrearden/building-a-graphql-server-with-graphql-helix-2k44#subscriptions)
- Easily support new GraphQL features support like `@defer` and `@stream` and our [new live queries implementation](https://the-guild.dev/blog/subscriptions-and-live-queries-real-time-with-graphql)

We would love to hear your thoughts and feedback and see if any of the points above might be somehow helpful!

This PR is a start, we saw a couple of other things that could be updated and improved and we would love to support the Parse community better around GraphQL and would love to collaborate more in this area!

_______

### TODOs before merging

- [ ] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for opening this PR.

This seems to be in an early stage of discussion about fundamental changes in Parse Server. Such Discussions are better suited in our [Community Forum](https://community.parseplatform.org) while we expect feature requests on GitHub to be in a more advanced stage. After a general discussion in the Community Forum, a subsequent feature description is created as a GitHub issue, which gives more exposure and allows others to join in. Based on that, a PR is created that already attempts a specific implementation that has been previously discussed.

**Comment by n1ru4l** [comment]
Hey @mtrezza, please interpret this pull request more as a reference to look at and talk about instead of a final solution. We are not expecting this to be merged anytime soon, that is why this is only a draft pull request.

We are happy to start a discussion about the benefits, drawbacks, and concerns of moving this forward!

**Comment by mtrezza** [comment]
Sure, thanks again for this PR. Conceptual discussions are preferably started in the forum and then trickle into GitHub. This is primarily to ensure visibility and to prevent the discussion to be spread over multiple places.

Please feel free to open a thread in the forum and I am sure this topic will start an engaging discussion.

**Comment by Urigo** [comment]
Thank you for the comment @mtrezza !

We've opened a discussion about that change [here](https://community.parseplatform.org/t/improving-the-graphql-layer-execution/1683) according to your suggestion.

We opened this as draft PR just because we wanted see how it would look in code.
I hope we could leave it open just as a reference and to enrich the discussion, but we are not expecting anyone to merge it soon before a proper discussion.

Thanks and looking forward to discuss GraphQL in Parse in general!

**Comment by mtrezza** [comment]
@Urigo Sure, let's keep this open in Draft for now. We do not have a PR clean-up process at the moment, so it won't be closed due to inactivity.

**Comment by mtrezza** [comment]
> ## ⚠️ Important change for merging PRs from Parse Server 5.0 onwards!
  >
  > We are planning to release the first beta version of Parse Server 5.0 in October 2021.
  >
  > If a PR contains a breaking change and is not merged before the _beta_ release of Parse Server 5.0, it cannot be merged until the end of 2022. Instead it has to follow the [Deprecation Policy](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#deprecation-policy) and phase-in breaking changes to be merged during the course of 2022.
  >
  > One of the most voiced community feedbacks was the demand for predictability in breaking changes to make it easy to upgrade Parse Server. We have made a first step towards this by introducing the Deprecation Policy in February 2021 that assists to phase-in breaking changes, giving developers time to adapt. We will follow-up with the introduction of [Release Automation](https://github.com/parse-community/parse-server/issues/7271) and a branch model that will allow breaking changes only with a new major release, scheduled for the beginning of each calendar year.
  >
  > We understand that some PRs are a long time in the making and we very much appreciate your contribution. We want to make it easy for PRs that contain a breaking change and were created _before_ the introduction of the Deprecation Policy. These PRs can be merged with a breaking change without being phased-in before the beta release of Parse Server 5.0. We are making this exception because we appreciate that this is a time of transition that requires additional effort from contributors to adapt. We encourage everyone to prepare their PRs until the end of September and account for review time and possible adaptions.
  > 
  > If a PR contains a breaking change and should be merged before the beta release, please mention @parse-community/server-maintenance and we will coordinate with you to merge the PR.
  >
  > *Thanks for your contribution and support during this transition to Parse Server release automation!*

**Comment by Moumouls** [comment]
Close since Yoga is now implemented

**Pull request closed without merging**
