### PR TITLE
feat: Deprecation DEPPS7: Remove deprecated Cloud Code file trigger syntax

### LINKED ISSUE #8843: Remove deprecation DEPPS7: Remove file trigger syntax `Parse.Cloud.beforeSaveFile((request) => {})`
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Feature / Enhancement Description

Remove deprecation DEPPS7: Remove file trigger syntax `Parse.Cloud.beforeSaveFile((request) => {})`

### References 

https://github.com/parse-community/parse-server/pull/7966

### PR DESCRIPTION
**Pull request by onurhanife**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8843 

## Approach
Deprecated file triggers are removed

Tests are the same with alpha branch 

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by mtrezza** [comment]
Changelog entry:

> BREAKING CHANGE: Deprecation DEPPS7: Cloud Code file trigger syntax `Parse.Cloud.beforeDeleteFile'` has been refactored to `Parse.Cloud.beforeDelete(Parse.File, (request) => {})'`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Comment by kartal-ocell** [comment]
Mind you that the [docs](https://docs.parseplatform.org/cloudcode/guide/#file-triggers) are still using the old syntax

**Comment by mtrezza** [comment]
@kartal-ocell Thanks for pointing this out, would you mind opening an issue in the [docs](https://github.com/parse-community/docs) repo?

**Pull request merged**
