### PR TITLE
fix: Inaccurate table total row count for PostgreSQL

### LINKED ISSUE #8502: Count Objects not working in some classes
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Dashboard doesn't count object in most of the classes

### Steps to reproduce
Since the first installation I always had this issue...

### Actual Outcome
Only showing '2' in the `_Session` class, the other classes show '0'

### Expected Outcome
To show the total of objects in each class

### Environment
Parse dashboard hosted on AWS Ubuntu EC2

Dashboard
- Parse Dashboard `version: 4.1.1`
- Browser: `Safari, Safari Technology Preview Release, Firefox, Chrome`
- Browser version: `Safari 15.5, Safari Technology Preview Release 146, Firefox 100.0.2, Chrome 102.0.5005.61. `

Server
- Parse Server version: `5.2.1`
- Operating system: `macOS Monterrey `
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS Ubuntu EC2`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `14.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### Logs
Screen Shot 2022-06-04 at 19 15 17

### PR DESCRIPTION
**Pull request by patelmilanun**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8502 

## Approach

Before for performance we were using pg_class to fetch count but it was inaccurate, so now we are using pg_stat_all_tables which gives same performance if not more but with the accuracy that we were missing before.

### CODE REVIEW

**Comment by patelmilanun** [comment]
@mtrezza  this should resolve all the count related issues with PostgreSQL

**Comment by mtrezza** [comment]
Could you change the PR title to describe the issue in Parse Server that has been fixed; the title is still related to Parse Dashboard.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
