### PR TITLE
refactor: Upgrade express-rate-limit from 6.6.0 to 6.7.0

### PR DESCRIPTION
**Pull request by parseplatformorg**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade express-rate-limit from 6.6.0 to 6.7.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **1 version** ahead of your current version.
- The recommended version was released **6 months ago**, on 2022-11-15.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>express-rate-limit</b></summary>
    <ul>
      <li>
        <b>6.7.0</b> - <a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/releases/tag/v6.7.0">2022-11-15</a></br><p>You can view the changelog <a href="https://snyk.io/redirect/github/nfriedly/express-rate-limit/blob/master/changelog.md">here</a>.</p>
      </li>
      <li>
        <b>6.6.0</b> - <a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/releases/tag/v6.6.0">2022-09-04</a></br><h3>Added</h3>
<ul>
<li>Added <code>shutdown</code> method to the Store interface and the MemoryStore. (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1354594742" data-permission-text="Title is private" data-url="https://github.com/express-rate-limit/express-rate-limit/issues/322" data-hovercard-type="pull_request" data-hovercard-url="/express-rate-limit/express-rate-limit/pull/322/hovercard" href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/pull/322">#322</a>)</li>
</ul>
<p>You can view the full changelog <a href="https://snyk.io/redirect/github/nfriedly/express-rate-limit/blob/master/changelog.md">here</a>.</p>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/releases">express-rate-limit GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>express-rate-limit</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/8fdcbf01843e54dbcf971439623fb314b7391ccc">8fdcbf0</a> 6.7.0</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/0d238e3a2102fd71781fe0fd3c33a02592dcd3b6">0d238e3</a> update CI actions versions</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/17d14b348d03f12567a00271ced0f077986ebf7f">17d14b3</a> bump CI tests node.js versions</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/dda4e4b2ab91afd09ef01ca6f4875b632bdc9b84">dda4e4b</a> ci: don&#x27;t continue on error</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/232e524609e298635e4c41a2338454cc6b243a4f">232e524</a> 6.7.0 changelog</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/b589c4cdb398ebbb930d838eaf980f379c2e8d48">b589c4c</a> changes for new TS version:</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/31132765d08e2bafcd757b10b2375231eafe49b5">3113276</a> update dependencies</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/584f3ffa43b8d79632dcef1431b01ed0cb1bc86d">584f3ff</a> update links to point to new org</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/57cec3dd876c2d63da8ba7a7d84173fc6e8a2f72">57cec3d</a> formatting</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/f696ea5c650e67f5875ca412f042d35384e4f0fd">f696ea5</a> Update readme.md</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/ca6bbaaa7eb0d23b94b6540462bed62d57d17cff">ca6bbaa</a> Create FUNDING.yml</li>
      <li><a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/commit/d7a1ddd973a52de0d8e76d16e26dddd24ff6b0ac">d7a1ddd</a> 6.5.2 and 6.6.0 release notes</li>
    </ul>

   <a href="https://snyk.io/redirect/github/express-rate-limit/express-rate-limit/compare/a567fda35e2335a38ce7a83838ca26f39811e89b...8fdcbf01843e54dbcf971439623fb314b7391ccc">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?pkg&#x3D;express-rate-limit&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)

**Pull request merged**
