### PR TITLE
feat: Add `$setOnInsert` operator to `Parse.Server.database.update`

### LINKED ISSUE #8792: Add `$setOnInsert` operator to `Parse.Server.database.update`
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

When using the Parse Server DB adapter directly (as exposed in Cloud Code via `Parse.Server.database`) the operator [$setOnInsert](https://www.mongodb.com/docs/v4.4/reference/operator/update/setOnInsert/) is not supported for upsert operations via Parse Server's `upsertOneObject`.

### Feature / Enhancement Description

Add support for `$setOnInsert`.

### PR DESCRIPTION
**Pull request by mtrezza**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8792

## Approach

Add support for `$setOnInsert`.

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.6.0](https://github.com/parse-community/parse-server/releases/tag/5.6.0)

**Comment by oallouch** [comment]
Hi,
I can't find the corresponding API change in the JS SDK.

**Comment by mtrezza** [comment]
This is a Cloud Code only feature.

**Comment by oallouch** [comment]
So the API has to be so low level ? I could be wrong, but the js sdk is also for Cloud Code.
Are we supposed to write "__op" in our code ?

**Comment by mtrezza** [comment]
`Parse.Server` gives you access to undocumented APIs, with various levels, ranging from just below the official Parse APIs down to the raw MongoDB driver. In the case of this issue here, there is no Parse SDK involved (apart from the namespace); this is operating on the internal database adapter level. If you decide to use this, extensive testing is advised, see also https://github.com/parse-community/parse-server/issues/8786.

**Comment by oallouch** [comment]
Very interesting.
I still use Config.get(Parse.applicationId).database

**Review by chaiyen123 — COMMENTED** [review]
/npm start

**Pull request merged**
