### PR TITLE
fix: CacheAdapter does not connect when using a CacheAdapter with a JSON config

### LINKED ISSUE #8610: CacheAdapter cannot be used in the configuration file
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I prefer to configure Parse Server using a configuration file. In Parse Server 5.x, I used the following code to configure the cacheAdapter, but now in 6.x, I keep getting the error "The client is closed at Commander._RedisClient_sendCommand."
`
"cacheAdapter":{
    "module":"C:/Users/Administrator/AppData/Roaming/npm/node_modules/parse-server/lib/Adapters/Cache/RedisCacheAdapter",
    "options":{
	  "url":"redis://127.0.0.1:6379/1"
	}
  }
`

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

When using a CacheAdapter with a JSON config, Parse Server does not call the "connect" function.

Closes: #8610

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by dblythy** [comment]
@beiguancyc can you try this PR out and let me know if it solves your issue. After that I'll see if I can write a failing test.

`npm install dblythy/parse-server#fix-module-rate-limit`

**Comment by beiguancyc** [comment]
> npm install dblythy/parse-server#fix-module-rate-limit

No problem, I will take a few days to investigate this issue.

**Comment by beiguancyc** [comment]
> 

No problem, I will take a few days to investigate this issue.

**Comment by beiguancyc** [comment]
> @beiguancyc can you try this PR out and let me know if it solves your issue. After that I'll see if I can write a failing test.
> 
> `npm install dblythy/parse-server#fix-module-rate-limit`

No problem, I will take a few days to investigate this issue.

**Comment by beiguancyc** [comment]
After several days of testing, no errors have occurred again.

**Comment by dblythy** [comment]
Thanks for testing the PR and reporting back @beiguancyc. 

This PR is ready for merge / review

**Review by mtrezza — APPROVED** [review]
Looks good, waiting for CI...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.27](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.27)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
