### PR TITLE
Run Prettier JS

### PR DESCRIPTION
**Pull request by dplewis**
A lot of PR are being formatted via Husky which makes review difficult.

* Pin Packages
* Use prettier on the entire project

### CODE REVIEW

**Comment by mtrezza** [comment]
@dplewis thanks for picking up that issue so quickly. I find some of these new formatting rules rather verbose 🧐 Would it make sense to disable a single rule like these additional parenthesis? Would that pre-commit hook then be deployed with the repo or does this work?

**Comment by dplewis** [comment]
You would have to update `.prettierrc` with `arrowParens: avoid` or something like that

**Comment by mtrezza** [comment]
Do we want the code to be that verbose, or is that verbosity only my subjective impression? I haven't seen these mandatory parentheses in other lints and find them quite unintuitive, but maybe that's just me?

**Comment by davimacedo** [comment]
I also don't like these additional parentheses. I'm in for removing them.

**Comment by mtrezza** [comment]
According to the [docs](https://prettier.io/docs/en/options.html#arrow-function-parentheses) this should work:

`prettier --write --arrow-parens avoid`

**Comment by dplewis** [comment]
The space after function?

`function ()`

**Comment by davimacedo** [comment]
I think it would be better to change https://github.com/parse-community/parse-server/blob/master/.prettierrc so we don't need to send this option every time we run the command.

**Comment by davimacedo** [comment]
I like the space after functions, but we can also change if you prefer.

**Comment by mtrezza** [comment]
> The space after function?

I'm just [reading](https://github.com/prettier/prettier/issues/1139) up on this. I would also write it without space, but there seem to be good arguments for having it.

**Comment by dplewis** [comment]
Let’s keep the space

**Comment by mtrezza** [comment]
It seems that there isn't even an option for space-after-function in prettier. I just scanned through the threads and the last result was a somewhat 50-50 opinion and prettier decided to make it mandatory and not optional.

**Pull request merged**
