### PR TITLE
ci: add MongoDB 5 environment test

### LINKED ISSUE #7808: Add MongoDB 5.0 compatibility for Parse Server 4.x
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
MongoDB announced that some lower-tier MongoDB Atlas clusters will be force-upgraded MongoDB 5.0:
> Your M0/M2/M5 Atlas cluster(s) will automatically be upgraded to MongoDB 5.0 next week. Please note, this automatic upgrade will only impact your shared tier clusters (M0/M2/M5) and will not impact dedicated clusters (M10 or higher). 

### Feature / Enhancement Description
Port changes in https://github.com/parse-community/parse-server/pull/7794 to branch `release-4.x.x`.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Parse Server 4.x is currently on LTS while Parse Server 5.0 is not officially released. MongoDB Atlas is force-upgrading lower cluster tiers to MongoDB 5.0 soon. Parse Server 4.x uses a MongoDB Node.js driver version that is officially incompatible with MongoDB 5.0. This PR adds a test to at run the CI with MongoDB 5 to see whether there are any obvious incompatibilities that should be addressed until Parse Server 5.0 is released.

Related issue: #n/a

### Approach
Add MongoDB 5 env to CI tests.

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
To fix the failing MongoDB 5 tests, the fix in https://github.com/parse-community/parse-server/pull/7794 needs to ported to here.

**Comment by olleolleolle** [comment]
The "Mongo 4.0.4 ReplicaSet WiredTiger" failure seems to be about "a too-old Node.js version"?

> Update: yeah, Installing Node 12.22.7 fixed it for me.

https://github.com/jsdom/whatwg-url/issues/209#issuecomment-991945619

**Update**: I saw that that update happened in mainline already.

**Comment by olleolleolle** [comment]
Ah, @mtrezza perhaps this can be rebased on top of latest?

**Comment by mtrezza** [comment]
This is based on latest 4.x

**Pull request closed without merging**
