### PR TITLE
fix: Cloud Code trigger `beforeSave` does not work with `Parse.Role`

### LINKED ISSUE #8317: Cannot create Parse Role after "fix: return correct response when revert is used in beforeSave #7839"
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The PR https://github.com/parse-community/parse-server/pull/7839 introduce a regression. We cannot create a Parse.Role anymore if we have a beforeSave on Parse.Role.
We get an error: TypeError: Tried to create an ACL with an invalid permission type.

### Steps to reproduce

Add this test in spec/CloudCode.spec.js:

```
  it('create role with name and ACL and a beforeSave', async () => {
    Parse.Cloud.beforeSave(Parse.Role, ({ object }) => {
      // do nothing, it's just to reproduce the bug, we must have a beforeSave
      return object;
    });

    const obj = new Parse.Role('TestRole', new Parse.ACL({ '*': { read: true, write: true } }));
    await obj.save();

    expect(obj.getACL()).toEqual(new Parse.ACL({ '*': { read: true, write: true } }));
    expect(obj.get('name')).toEqual('TestRole');
    await obj.fetch();

    expect(obj.getACL()).toEqual(new Parse.ACL({ '*': { read: true, write: true } }));
    expect(obj.get('name')).toEqual('TestRole');
  });
```

### Actual Outcome

>   Message:
>     **TypeError: Tried to create an ACL with an invalid permission type.**
>   Stack:
>         at <Jasmine>
>         at new ParseACL (/Users/albin/iziwork/parse-server/node_modules/parse/lib/node/ParseACL.js:69:21)
>         at ParseRole._handleSaveResponse (/Users/albin/iziwork/parse-server/node_modules/parse/lib/node/ParseObject.js:614:25)
>         at /Users/albin/iziwork/parse-server/node_modules/parse/lib/node/ParseObject.js:3183:22
>         at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Expected Outcome

The created role with the right name and ACL.

### Environment

Server
- Parse Server version: `5.3.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.2.1`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `3.4.2`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

BeforeSave on Parse.Role no longer works. This is due to the fact that the state identifier is different before and after the trigger, meaning that the code to manage pending OPs does not properly run.

Related issue: #8317
Closes: #8317

### Approach

Stores state identifier beforeSave. This should prevent other similar issues, which could arise from subclassing Parse.Object.

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by Moumouls — COMMENTED** [review]
I'm not familiar with state mechanism here, but the code looks okay

**Review by AlbinIzi — APPROVED** [review]

**Comment by mtrezza** [comment]
Thanks everyone for their reviews; I notice that @dblythy hasn't requested a review yet - is this done?

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.10)

**Comment by AlbinIzi** [comment]
Thanks ! Is it possible to fix this issue in 5.3.4 please ?

**Comment by mtrezza** [comment]
We are moving Parse Server 5 to LTS. That means that only severe security vulnerabilities will be fixed in Parse Server 5 going forward. For this bug fix here to be available in a 5.x release, you (or someone else in the community) would need to open a PR against the branch `release-5.x.x`, which is the LTS branch.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
