### PR TITLE
Prepare for 3.4.1

### PR DESCRIPTION
**Pull request by acinader**

### CODE REVIEW

**Comment by dplewis** [comment]
Can you look into the docker build? I think ignore scripts on the release build should do the trick.

**Comment by acinader** [comment]
ugh, https://cloud.docker.com/orgs/parseplatform/teams is 500 for me now

what is the problem?  how do you know there is a problem?

**Comment by dplewis** [comment]
Its 500 for me too. I looked into it before but didn't have time to fix it.

**Comment by acinader** [comment]
its working again and I resynced the integration using my id. lets see if it works!

**Pull request merged**
