### PR TITLE
fix: liveQuery with `containedIn` not working when object field is an array

### PR DESCRIPTION
**Pull request by stewones**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to issue #2088

### Issue Description
previously it was not possible to use livequery with `containedIn` if the object field is an array
Related issue: #2088

### Approach
I figured out that if `notCointainedIn` is supported, then there must be a way to make the other way around work. 

### TODOs before merging

- [x] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by stewones** [comment]
you guys.

the issue is that `containedIn` only works currently for queries where the targeted field isn't an array. ie:

1st case
```js
    const message = {
      id: new Id('Message', 'O1'),
      profile: pointer('Profile', 'abc'),
    };
    let q = new Parse.Query('Message');
    q.containedIn('profile', [
      Parse.Object.fromJSON({ className: 'Profile', objectId: 'abc' }),
      Parse.Object.fromJSON({ className: 'Profile', objectId: 'def' }),
    ]);
 expect(matchesQuery(message, q)).toBe(true);
```
> ok works


2nd case
```js
   const message = {
      id: new Id('Message', 'O2'),
      profiles: [pointer('Profile', 'yeahaw'), pointer('Profile', 'yes')],
    };

    let q = new Parse.Query('Message');
    q.containedIn('profiles', [
      Parse.Object.fromJSON({ className: 'Profile', objectId: 'no' }),
      Parse.Object.fromJSON({ className: 'Profile', objectId: 'yes' }),
    ]);

 expect(matchesQuery(message, q)).toBe(true);
```
> not ok because profiles here is an array of pointers


so my PR aims to add support for the 2nd case above

thanks for your time reviewing this

**Comment by stewones** [comment]
Heyo @mtrezza is there anything I can help with to get this merged?

**Comment by mtrezza** [comment]
This is just awaiting review, sorry for the long wait.

cc @parse-community/server-review

**Review by dblythy — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.23](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.23)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Pull request merged**
