### PR TITLE
docs: Add issue scope to contribution guide

### PR DESCRIPTION
**Pull request by mtrezza**

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza Did you write this because of me lol

**Comment by mtrezza** [comment]
Naw, I was actually surprised that we didn't have that in writing yet since we are applying this for a long time already. It's a living document and we try to refine it as we go along.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.32](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.32)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Pull request merged**
