### PR TITLE
Before Connect + Before Subscribe help required

### PR DESCRIPTION
**Pull request by dblythy**
Hey guys,

This is my second attempt at creating two new cloud code triggers which affect LiveQuery: **beforeConnect** and **beforeSubscribe**.

**beforeConnect** allows validation prior to a LiveQuery opening connection. This is not class specific.

```
Parse.Cloud.beforeConnect(request => {
      if (!request.user) {
          throw "Please login before you attempt to connect."
      }
  });
```
beforeSubscribe handles the .subscribe methods from LiveQuery. Can be used to validate users, or to mutate the request.query, enforcing fields, equalTo, or whatever required.

  ```
Parse.Cloud.beforeSubscribe(Parse.User, request => {
      if (!request.user) {
          throw "Please login before you attempt to connect."
      }
      let query = request.query; // the Parse.Query
      query.select("name","year")
  });
```

However, as I'm a JS noob, I'm struggling to create tests that will pass. I was wondering if someone would be kind to help me close this out (I'll buy you a box of beers because I've been pulling my hair out trying to work this out).

Also my linter changed some other things, couldn't work out how to stop it (again, I'm a VS noob too).

Thank you all for your hard work!!

### CODE REVIEW

**Comment by dblythy** [comment]
In relation to #6649, #6642, and #6779.

**Comment by dblythy** [comment]
[Here](https://travis-ci.org/github/parse-community/parse-server/builds/707598816?utm_source=github_status&utm_medium=notification) are the failing tests

**Comment by dplewis** [comment]
@dblythy Can you give me access to your master branch? It's best practice to create a separate branch for every PR.

**Comment by dblythy** [comment]
Thanks for the tip @dplewis. I've invited you to my branch.

**Comment by dplewis** [comment]
Got it. I’ll review in the AM.

**Comment by dplewis** [comment]
@dblythy I need to add a few more tests. Is there anything else that should be returned in `beforeConnect` and `beforeSubscribe` request handler?

**Comment by dplewis** [comment]
@dblythy This beforeSubscribe will need a tiny update on the JS SDK to properly handle errors

**Comment by dblythy** [comment]
@dplewis thank you so much for your help again. Is it worth creating a test to make sure modifying req.query affects the subscription?

**Comment by dplewis** [comment]
No problem, add as many tests as you need.

**Comment by dblythy** [comment]
Ok, no worries. So once the JS SDK is updated, the tests should pass and we can submit the PR? 😊

**Comment by dplewis** [comment]
@dblythy Can you add that test for modifying the req.query? I really want to see what you are trying to do with that.

**Comment by jadsonlourenco** [comment]
Maybe we can add the trigger "afterDisconnect" too?

**Comment by dblythy** [comment]
@jadsonlourenco I believe you can use [onLiveQueryEvent](https://docs.parseplatform.org/cloudcode/guide/#livequery-triggers) for running a function after a disconnect.

**Comment by jadsonlourenco** [comment]
> @jadsonlourenco I believe you can use [onLiveQueryEvent](https://docs.parseplatform.org/cloudcode/guide/#livequery-triggers) for running a function after a disconnect.

Yes, I'm using, but like this PR did, if we have a trigger to handle before connect on a "live" system is good to know when the client disconnect, using it as Parse api will be more easy to implement, just to make the Parse api more complete, I think.

**Pull request merged**
