### PR TITLE
fix: Security upgrade jsonwebtoken to 9.0.0

### LINKED ISSUE #8356: Bump jsonwebtoken to 9.0.0
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Upgrade fixes security vulnerabilities, but since it's a major version upgrade, some tests fail.

### Feature / Enhancement Description

Adapt code for upgrade to 9.0.0.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

The latest JWT library prevents mocking of the `decode` property, which we use to determine a JWT's headers.

Closes: #8356
Closes: https://github.com/parse-community/parse-server/pull/8355

## Approach

Add ability to mock decode

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
Ready for review

**Review by mtrezza — COMMENTED** [review]
Is this really a `feat` PR? It seems that the auth adapter changes would be unnoticeable for the developer, in which case this would be a `refactor`.

**Comment by mtrezza** [comment]
Sorry, I figured it should probably be a `fix` to trigger a new release with the upgrade; otherwise the fix will only be released with the next `fix` or `feat` commit.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.32](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.32)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Pull request merged**
