### PR TITLE
refactor: Upgrade pg-promise to 11.3.0 and pg-monitor to 2.0.0

### LINKED ISSUE #8454: pg-promise and node-postgres are out-of-date
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The dependencies pg-promise and pg-monitor are not up-to-date and the node-postgres driver pg-promise depends on is out-of-date. 

### Feature / Enhancement Description

Update to the latest versions.

### Example Use Case

N/A

### Alternatives / Workarounds

Force updating packages in dedicated projects.

### 3rd Party References

N/A

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

pg-promise and pg-monitor are not up-to-date and the node-postgres driver pg-promise depends on is out-of-date. Continuation on #8365 #8364 

Closes: #8454

## Approach

Update pg-promise to 11.3.0 and pg-monitor to 2.0.0 (this version has a minimum dependency on pg-promise 11.0.0).

pg-promise 11.0.0 removed `poolSize` in favor of `max` more info [here](https://github.com/vitaly-t/pg-promise/releases/tag/11.0.0)). Since the parse-server `PostgresConfigParser` already supports both `poolSize` and `max` this PR sets `poolSize` to `max` so it's not a breaking change on the parse-server. If both are set, `max` always takes precedence.

## Tasks

- [x] Add tests
- [x] No documentation (guides, repository pages, code comments) changes needed as https://github.com/parse-community/docs/pull/731 is still valid

### CODE REVIEW

**Comment by cbaker6** [comment]
I suspect something is up with the node cache or something else as these pass locally. I used the following commands to update pg-promise and pg-monitor: 

```bash
npm i -E pg-promise@11.3.0 pg-monitor@2.0.0
```

I used `node 19.3.0`. Not sure why changes to `node_modules/mock-files-adapter` and `node_modules/mock-email-adapter` were made, maybe the lock file was created with an older version of node?

**Comment by cbaker6** [comment]
I managed to find an older version of node for the lock file.

This is ready for review.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Pull request merged**
