### PR TITLE
GraphQL support via cli

### PR DESCRIPTION
**Pull request by davimacedo**
GraphQL and Playground can now be launched using the CLI.

### CODE REVIEW

**Comment by dplewis** [comment]
You can [generate the definitions](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#generate-parse-server-config-definition)

**Comment by davimacedo** [comment]
Thanks for guiding me on this @dplewis . I've just updated the PR. I also included basic instructions in the repository README file about how to run/use the GraphQL API. Could you have a try on this?

**Comment by davimacedo** [comment]
I also created this project (https://github.com/parse-community/parse-server/projects/5) with the next priorities I have in mind.

**Comment by TomWFox** [comment]
@davimacedo I appreciate if you don’t feel it’s ready yet, but when you do could you please add a section in the Parse Server guide (docs repo) about GraphQL.

**Comment by davimacedo** [comment]
@TomWFox I am working on this right now:
https://github.com/back4app/parsedocs/tree/graphql

**Comment by davimacedo** [comment]
I am actually creating a new guide: /graphql/guide/

What do you think?

**Comment by TomWFox** [comment]
@davimacedo I can see the sense in that as Cloud Code is a separate guide, although it does seem a bit weird considering the GraphQL api is/will be included in the Parse Server API Reference.

Maybe you should open an issue/pr on the docs repo so we can add more thoughts there.

**Pull request merged**
