### PR TITLE
feat: Upgrade to Parse JS SDK 5.2.0

### LINKED ISSUE #9131: Upgrade to Parse 5.1.0 fails
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

CI fails for https://github.com/parse-community/parse-server/pull/9128. We cannot upgrade Parse Server to the latest Parse version.

### PR DESCRIPTION
**Pull request by mtrezza**
Closes: #9131

### CODE REVIEW

**Comment by mtrezza** [comment]
@parse-community/server @parse-community/js-sdk could someone take a look at why this CI fails when upgrading the Parse JS SDK? It seems that there are a 6 or so tests that consistently fail.

**Comment by dplewis** [comment]
@mtrezza @parse-community/server @parse-community/js-sdk Looks like https://github.com/parse-community/Parse-SDK-JS/pull/1453 is the cause. Although `attributes` does take care of pending operations, those pending operation returned from `toJSON` are heavily used in cloud code.

**Comment by mtrezza** [comment]
test-upgrade to parse 5.2.0-beta.1, to see whether CI passes, i.e. whether https://github.com/parse-community/Parse-SDK-JS/pull/2162 fixed the issue. Before merge: release parse 5.2.0 stable and upgrade to that in this PR.

**Comment by mtrezza** [comment]
CI now fails using parse 5.2.0-beta.1 with:

> 1) PushWorker pushStatus tracks push status per UTC offsets
>   - Expected undefined to be 1.
>   - Expected undefined to be 1.
>   - Expected undefined to be 3.
>   - Expected undefined to be 2.

Not sure whether this is related to https://github.com/parse-community/Parse-SDK-JS/pull/2162, or a different issue. @dplewis if you could take a look...

**Comment by dplewis** [comment]
It is related because sentPerUTCOffset and failed PerUTCOffset use dot notation even though they are saved as strings so a check is needed

**Comment by mtrezza** [comment]
@dplewis if you find the time to open a fix for this, that would be great

**Comment by mtrezza** [comment]
Test upgrade to parse 5.2.0-alpha.4, to see if https://github.com/parse-community/Parse-SDK-JS/pull/2194 fixed the issue.

**Comment by dplewis** [comment]
@mtrezza looks good to me 👍

**Comment by mtrezza** [comment]
Yes, finally, thanks for the fixes @dplewis

**Comment by mtrezza** [comment]
Changed to draft as to not merge it accidentally before changing the parse dependency to a stable release

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.11](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)

**Pull request merged**
