### PR TITLE
feat: Add Cloud Code triggers `Parse.Cloud.beforeSave` and `Parse.Cloud.afterSave` for Parse Config

### LINKED ISSUE #8267: Add trigger before Remote Config change
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

When changing any value in Remote Config, the previous value is lost without any possibility to undo the change. That means that any user mistake can lead to information irreversibly lost.

### Feature / Enhancement Description

Add a Cloud Code trigger that is invoked when the remove config is changed. This allows a developer to catch any changes to the Remote Config parameters and log them, or store a history of changed.

### Example Use Case
n/a

### Alternatives / Workarounds
None

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

When changing any value in Remote Config, the previous value is lost without any possibility to undo the change. That means that any user mistake can lead to information irreversibly lost.

Closes: https://github.com/parse-community/parse-server/issues/8267

## Approach

Add a Cloud Code trigger beforeSave and afterSave that is invoked when the remove config is changed. This allows a developer to catch any changes to the Remote Config parameters and log them, or store a history of changed.

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
Nice!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)

**Pull request merged**
