### PR TITLE
fix: lru deprecation warnings

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
LRU warnings introduced after lru update

Related issue: NONE

### Approach
Update API

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
Please add a proper description to this PR. That is exactly why we always ask to open an issue for a PR.

**Comment by Moumouls** [comment]
@mtrezza if you have a suggestion, this PR just fix LRU depreciation warnings.

It was introduced after the LRU cache package update.

**Comment by mtrezza** [comment]
The changes only show some method renaming, this PR needs more info. As you know, we require an issue for a PR, to avoid these fundamental Q/As about PRs.

**Comment by Moumouls** [comment]
closing since it's now outdated

**Pull request closed without merging**
