### PR TITLE
Relay spec

### PR DESCRIPTION
**Pull request by davimacedo**
- [x] Object identification
- [x] Mutations
- [ ] Connections
- [ ] Wait PR https://github.com/parse-community/parse-server/pull/5883 to be approved and merge
- [ ] Final review to check if any other type improvement is needed either in relay schema or in not relay schema

### CODE REVIEW

**Comment by davimacedo** [comment]
@Moumouls let me know your feedback

**Comment by Moumouls** [comment]
It seems to be missing `Connection` `Cursor` on `find results`.
Do you have an idea on how implementing `before` and `after` cursors with the Parse Server Rest API ?

**Comment by davimacedo** [comment]
Yes. I am still working on this.

**Comment by davimacedo** [comment]
Close this one in favor of https://github.com/parse-community/parse-server/pull/6089

**Pull request closed without merging**
