### PR TITLE
fix: Nested objects are encoded incorrectly for MongoDB

### LINKED ISSUE #7575: Nested `Date` type attributes are saved differently at different levels
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

If we try to create an object with below code

```js
const myObj = new Parse.Object('Company3');
await myObj.save({
  prop1: 'test1',
  prop2: {
    test: {
      date: new Date()
    }
  },
  prop3: {
    date: new Date()
  }
}, {useMasterKey: true});
```

This is how the saved object in mongo DB looks like

```json
{
  "_id": "5DTIqZcZv9fhbHu0qTZq",
  "prop2": {
    "test": {
      "date": {
        "__type": "Date",
        "iso": "2021-09-14T14:50:37.303Z"
      }
    }
  },
  "prop3": {
    "date": {
      "$date": "2021-09-14T14:50:37.303Z"
    }
  },
  "prop1": "test1",
  "_created_at": {
    "$date": "2021-09-14T14:50:38.108Z"
  },
  "_updated_at": {
    "$date": "2021-09-14T14:50:38.108Z"
  }
}
```

`prop2.test.date` is saved as JSON object instead of `$date` object while `prop3.date` is properly saved.
This breaks date queries

### Steps to reproduce
1. Create new object with below code

```js
const myObj = new Parse.Object('Company3');
await myObj.save({
  prop1: 'test1',
  prop2: {
    test: {
      date: new Date()
    }
  },
  prop3: {
    date: new Date()
  }
}, {useMasterKey: true});
```
2. Observe different date types at different levels in mongoDB Compass

### Actual Outcome
```json
{
  "_id": "5DTIqZcZv9fhbHu0qTZq",
  "prop2": {
    "test": {
      "date": {
        "__type": "Date",
        "iso": "2021-09-14T14:50:37.303Z"
      }
    }
  },
  "prop3": {
    "date": {
      "$date": "2021-09-14T14:50:37.303Z"
    }
  },
  "prop1": "test1",
  "_created_at": {
    "$date": "2021-09-14T14:50:38.108Z"
  },
  "_updated_at": {
    "$date": "2021-09-14T14:50:38.108Z"
  }
}
```

### Expected Outcome
```json
{
  "_id": "5DTIqZcZv9fhbHu0qTZq",
  "prop2": {
    "test": {
      "date": {
        "$date": "2021-09-14T14:50:37.303Z"
      }
    }
  },
  "prop3": {
    "date": {
      "$date": "2021-09-14T14:50:37.303Z"
    }
  },
  "prop1": "test1",
  "_created_at": {
    "$date": "2021-09-14T14:50:38.108Z"
  },
  "_updated_at": {
    "$date": "2021-09-14T14:50:38.108Z"
  }
}
```

### Environment

Server
- Parse Server version: `4.10.3`
- Operating system: `Mac OS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `3.3.0`

Old issue related to this #6840

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

The mongoDB adapter currently only encodes objects one level down, and the rest is stored as JSON. This results in a lot of nested objects being saved incorrectly, for example, nested dates saved as `JSON` with `iso` and `type` rather than a `Date`.

Related issue: #7575
Closes: #7575

### Approach

Loops through nested keys and encodes as expected.

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by dblythy** [comment]
I wonder if this is a breaking change, as this changes how nested keys are saved, which can impact nested indexes, or nested queries

**Comment by mtrezza** [comment]
It is a breaking change. I think we can prepare the PR and merge it for Parse Server 6-alpha in November.

**Comment by hariprasadiit** [comment]
@dblythy thanks for the PR. Should we consider applying similar fix for pointers as well? Nested pointers are also saved as plain JSON object instead of `Class$ObjectId` in MongoDB

**Comment by dblythy** [comment]
This PR probably does change how pointers are changed - I'll investigate

**Comment by dblythy** [comment]
This doesn't actually change that as lines 558 - 562 are programmed to return the JSON:

https://github.com/parse-community/parse-server/blob/16b1b2a19714535ca805f2dbb3b561d8f6a519a7/src/Adapters/Storage/Mongo/MongoTransform.js#L555-L574

Do we see any benefit of changing this?

**Comment by hariprasadiit** [comment]
> This doesn't actually change that as lines 558 - 562 are programmed to return the JSON:
> 
> https://github.com/parse-community/parse-server/blob/16b1b2a19714535ca805f2dbb3b561d8f6a519a7/src/Adapters/Storage/Mongo/MongoTransform.js#L555-L574
> 
> Do we see any benefit of changing this?

It'll remove possible edge cases with querying nested pointers. Right now, query on nested pointers works but it depends on the order of  the props in the generated JSON and  I think it's not future proof. Moreover how Postgres handles query on nested pointers is something I haven't tested

We'll also have consistent data format in the database

**Comment by dblythy** [comment]
@parse-community/server what are your thoughts regarding https://github.com/parse-community/parse-server/pull/8209#issuecomment-1311258587

**Comment by dblythy** [comment]
I think this is ready for merge

**Comment by mtrezza** [comment]
> https://github.com/orgs/parse-community/teams/server what are your thoughts regarding https://github.com/parse-community/parse-server/pull/8209#issuecomment-1311258587

Seems there are some open questions about implications, so I would see this out of scope for this PR. Can someone open a separate issue so we can take our time to look into this?

I'll go ahead and merge this PR once the CI passes.

**Comment by mtrezza** [comment]
Suggestion for changelog entry:

### BREAKING CHANGE
- Nested objects are now properly stored in the database using JSON serialization; previously, due to a bug only top-level objects were serialized, but nested objects were saved as raw JSON; for example, a nested `Date` object was saved as a JSON object like `{ "__type": "Date", "iso": "2020-01-01T00:00:00.000Z" }` instead of its serialized representation `2020-01-01T00:00:00.000Z`.

Does that sound right?

**Comment by dblythy** [comment]
Yep!!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.15)

**Comment by bdevore17** [comment]
@mtrezza I know this is marked as a breaking change, but is this safe in general? Unless there is a database migration, many existing queries are going to break. I think a lot of users have found workarounds for this bug in the past, and are now stuck in a bit of a quagmire with this change.

For example,

This is an existing query in our app:

```
const negotiationReminderQuery = new Parse.Query(Influencer)
	.lessThan("activeNegotiation.offer.expirationTimestamp.iso", new Date().toISOString())
	.findAll({ useMasterKey: true });
```

We can't rewrite this query unless we know that every document serialized before this PR has been updated.

If this change is to be made, it really seems like it needs to be tied to some kind of migration process and feature flagging.

**Comment by mtrezza** [comment]
@bdevore17 Could you please open a new issue with the info you posted here? Then let's discuss there.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Comment by magnacartatron** [comment]
Hi Team,
This change is a little confusing.
On Parse V6 release I've created a new Class called "Test". This contains an object field.
When I try to save an object with a date in that field, when I query said object the date is still {}

I can see in that in MongoDB the value is stored correctly. When I hook up a V5 Parse Server I can retrieve the value but trying to retrieve the object that was created on V6 from V6 gives me an empty object.

Is there some kind of data migration that I need to perform?

**Comment by RahulLanjewar93** [comment]
> @dblythy thanks for the PR. Should we consider applying similar fix for pointers as well? Nested pointers are also saved as plain JSON object instead of `Class$ObjectId` in MongoDB

@dblythy @mtrezza I think the above change is also needed 
Right now as of v7 the `transformWhere` function in `MongoTransform.js` is trying to query the nested pointer based on `Class$ObjectId` but since nested pointers are stored as their JSON representation, the query fails and returns empty array. 

So either we update the transformWhere to query on nested objects using the json representation or else store the nested pointers in `Class$ObjectId` format. For consistency I think the latter is better.

**Comment by mtrezza** [comment]
@RahulLanjewar93 If you found a bug, please open a new issue and reference this PR if related. Note that the issue needs to be reproducible in Parse Server 8. Parse Server 7 only receives security fixes at this point.

**Comment by RahulLanjewar93** [comment]
> @RahulLanjewar93 If you found a bug, please open a new issue and reference this PR if related. Note that the issue needs to be reproducible in Parse Server 8. Parse Server 7 only receives security fixes at this point.

I used v7 as base I think same is there in v8 #9737

**Pull request merged**
