### PR TITLE
refactor: Upgrade semantic-release from 17.4.6 to 21.0.1

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

`semantic-release` is currently out-of-date with the newest version being `21.0.1`

Closes: n/a

## Approach

Update `semantic-release` and all of its peer dependencies at the same time as the current versions of the peer dependencies are not compatible with the latest version.

## Tasks

- [ ] Ensure tests pass

### CODE REVIEW

**Comment by cbaker6** [comment]
CI Node Engine Check not passing related to #8151

**Comment by mtrezza** [comment]
This is a major version upgrade, did you read through the changelog to see what the breaking changes are and whether we need to adapt any release config files? You'd need to do a successful local dry-run of the release framework on the same Node version as the release workflow to confirm its still working before this PR can be merged. That's why these dependencies are not always on the latest versions. It doesn't hurt when they aren't, more important is that the release workflow works.

**Comment by cbaker6** [comment]
No, I'm not familiar with semantic-release nor do I use it, so I didn't go through the changelog or do a dry-run. I figured the CI already does the necessary testing to support an update since dependabot updates for semantic-release have been accepted in the past.

The reason I opened this PR is to ensure there isn't a mistake made by dependabot updating semantic-release without updating the respective peer dependencies which can cause issues down the line. I mention this issue here: https://github.com/parse-community/parse-server-fs-adapter/issues/45

If the repo is not ready to accept this PR, this can be closed.

**Comment by mtrezza** [comment]
Not sure what you mean by "not ready". Your PR is modifying a CD workflow, not a product feature. Part of such a change is ensuring that the new workflow works.

If you need assistance for how to run the dry-run, I'm here to help.

**Pull request closed without merging**
