### PR TITLE
Cannot change password when maxPasswordHistory is 1

### PR DESCRIPTION
**Pull request by Tolsee**
#4918

Change `this.config.passwordPolicy.maxPasswordHistory - 2` to equal 0 when 0 or -ve, same value when positive.

So, while loop will terminate.

### CODE REVIEW

**Comment by flovilmart** [comment]
Thanks for the PR, can you add a test please so we do not introduce unwanted regressions?

**Comment by Tolsee** [comment]
@paulovitin @flovilmart 
Is the same test but with the case of valid reset password will be right thing here?

@paulovitin pointed out the case covered here, but It seems that when the password is invalid then we will not rich the problem. 

Your help will be greatly appreciated 😀 
 
https://github.com/parse-community/parse-server/blob/master/spec/PasswordPolicy.spec.js#L1405-L1407

**Comment by flovilmart** [comment]
cc @Tolsee do you think you can add a test please?

**Comment by dplewis** [comment]
@acinader The issue here is that new users have a password history of 0 initially which causes an infinite loop. Failing test has been added

**Pull request merged**
