### PR TITLE
feat: Add `afterFind` trigger to authentication adapters

### LINKED ISSUE #8440: Add `afterFind` to auth adapter
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, to strip authData fields, it needs to be done in an afterFind trigger

### Feature / Enhancement Description

Give authAdapters the ability to customize find response

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

It's currently quite tedious to strip out authData

Closes: #8440

## Approach

Adds ability to change the authData that is returned from queries

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
This PR:

1. Gives an AuthAdapter the ability to validate any `options` that are passed to it in setup. This is mainly required for internal auth adapters
2. Gives an AuthAdapter the ability to determine what data should be returned to the client

**Comment by mtrezza** [comment]
Cool, is this ready for review?

**Comment by dblythy** [comment]
Yep!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.4](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Pull request merged**
