### PR TITLE
refactor: replace internal GraphQL array classes to object style

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: None

### Approach
Remove duplicated "find" logic, switch to a object style

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, is this ready for merge?

This PR is missing a corresponding issue, which is required for reasons that have been explained repeatedly. I can only guess what this PR is about. From the PR title it seems that this is a performance improvement, but the PR prefix is `refactor` which implies no perf improvement. Can you please clarify, write a PR description and open an issue next time?

**Review by davimacedo — DISMISSED** [review]
LGTM!

**Review by mtrezza — CHANGES_REQUESTED** [review]
Requires proper PR title which will become the changelog entry - what is this PR about, perf improvement or mere refactor?

**Comment by Moumouls** [comment]
Hi @mtrezza, after a check this PR is rather related to an internal refactor. There is no clear performance improvement.

**Comment by mtrezza** [comment]
Could you please adapt the PR title accordingly

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.8](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-server/releases/tag/5.3.0)

**Pull request merged**
