### PR TITLE
feat(LiveQuery): Support $and, $nor, $containedBy, $geoWithin

### PR DESCRIPTION
**Pull request by dplewis**
Also `$geoIntersects `

### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Adds missing operators. Matches LDS from the JS SDK [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/OfflineQuery.js#L120)

### TODOs before merging

- [x] Add test cases
- [x] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Comment by dplewis** [comment]
@mtrezza How does this look?

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by cbaker6** [comment]
@dplewis posting this here because I don't know if this is suppose to happen or an oversight in the original liveQuery server code...

For LiveQuery, I don't see events being sent for a simple query like, `GameScore.query("score" == 10)`, of course, >=, etc. work. It does let me subscribe, just never any events. Looking through the code, https://github.com/parse-community/parse-server/blob/d6b6dc239df785b6c1c555887ccb8bb601e62c8f/src/LiveQuery/QueryTools.js#L148 

I don't see `$eq` implemented, but I could also be looking in the wrong spot.

**Comment by dplewis** [comment]
@cbaker6 I believe this is what you are looking for. https://github.com/parse-community/parse-server/blob/1ede078154213d3426cc492612ce41bdb1eda43b/src/LiveQuery/QueryTools.js#L193

Can you write a failing test just in case?

**Comment by cbaker6** [comment]
I see, it looks like I created a bug on the ParseSwift SDK side by using `$eq` which isn't a constraint. Thanks for pointing me here!

**Comment by dplewis** [comment]
No problem! Let me know if you need anything else regarding LiveQueries

**Comment by cbaker6** [comment]
I’m assuming `$eq` was the old way sometime ago? https://github.com/parse-community/parse-server/blob/1ede078154213d3426cc492612ce41bdb1eda43b/src/GraphQL/transformers/query.js#L8-L10

This is probably why Parse-Swift didn’t give me issues with `==`. I switched to just send a dictionary with [key: value] for `==` and it now works with the regular query and livequery.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
