### PR TITLE
refactor: Upgrade ldapjs from 2.3.3 to 3.0.2

### PR DESCRIPTION
**Pull request by onurhanife**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8592 

## Approach
#8623 cloned, merged to alpha and conflicts are fixed

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
There seems to be a conflict again, after I've merged some of the open PRs. Could you please resolve them, so we can merge this? Thanks

**Comment by onurhanife** [comment]
@mtrezza i resolved conflicts but there some new tests that you wrote about `ignoreEmailVerification` and page routing tests related to emailVerifications are fails. FYI

**Comment by mtrezza** [comment]
Which tests are you referring to? They all seem to pass except for some flaky tests.

**Comment by mtrezza** [comment]
@onurhanife This PR also contains quite a few code style changes. Not sure where they come from, but could you please make sure they are not included in the PR? The PR should only contain the changes that are necessary for the fix.

**Comment by onurhanife** [comment]
@mtrezza My prettiers require config file option enabled, and I prefer using double quotes in my Prettier configurations. However, I'm not sure where these style changes are coming from. I also noticed that the .prettierrc file is not in JSON format, which might be why it's not working correctly. Is it intentionally like this, or I can fix it with this PR?

**Comment by mtrezza** [comment]
The code style changes I see in this PR make sense, but they shouldn't be in this PR. If easily possible, could you revert them and only keep the necessary changes? I believe it's just 1 code line that is required, and the package upgrade. It may be easier to just create a new PR?

**Comment by mtrezza** [comment]
It seems something went wrong here. I suggest to either revert all changes by just replacing the files, or open a new PR.

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/8947

**Comment by mtrezza** [comment]
@onurhanife Kindly see https://github.com/parse-community/parse-server/pull/8947; the PR was simple and required just 1 line of code, when removing the code style changes.

**Comment by onurhanife** [comment]
@mtrezza I was aware that we could handle it this simply, I just hadn't had the chance to focus on this side yet, but I see that you've resolved the issue in my place. Thank you.

**Pull request closed without merging**
