### PR TITLE
fix(package): update pg-promise to version 6.9.0

### PR DESCRIPTION
**Pull request by flovilmart**
Closes #4160

### CODE REVIEW

**Comment by flovilmart** [comment]
@vitaly-t all is awesome!

**Comment by vitaly-t** [comment]
I wonder though what was the hiccup...?

**Comment by flovilmart** [comment]
not sure, but it was failing against node 8.1.3 specifically, installed with nvm

**Comment by vitaly-t** [comment]
strange, as I did install Node.js 8.1.3 via nvm also, and re-ran all tests - no problem.

**Comment by vitaly-t** [comment]
Maybe the issue was Linux-specific? My machine is Windows 10 here.

**Comment by flovilmart** [comment]
Ah perhaps. Anyhow, we can move forward, we’ll see how it goes if any user reports an issue

**Pull request merged**
