### PR TITLE
Run prettier

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Runs prettier on Parse Server (there are a few affected files)

### CODE REVIEW

**Comment by dblythy** [comment]
Also, there are a couple of files which are changed using `npm run prettier` but changed back using `npm run lint-fix`. Which should be the priority?

**Comment by davimacedo** [comment]
I think we should choose and rely in one of them. @dplewis @mtrezza thoughts?

**Comment by mtrezza** [comment]
There are things that lint doesn't do, but prettier does and vice versa. Not, because one is better than the other but because each has a [slightly different](https://prettier.io/docs/en/comparison.html) although similar purpose.

I think we should decide the order in which they run - which will lead to different results - without expecting both to yield the same output.

**Comment by dblythy** [comment]
Okay, cool. Good to know the process for the future. That's what I expected. 

This PR is still the result of running:

`npm run prettier`
then
`npm run lint-fix`

On the master branch

**Comment by mtrezza** [comment]
I think that makes sense.

**Comment by davimacedo** [comment]
Yes. That makes sense. I believe it is actually already automated [here](https://github.com/parse-community/parse-server/blob/master/package.json#L148), right?

**Comment by dblythy** [comment]
I think it only affects files that are edited though. If you run prettier on the master and then lint-fix, the result is this PR

**Review by davimacedo — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]
LGTM!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
