### PR TITLE
Upgrade mongodb to 3.6.3

### PR DESCRIPTION
**Pull request by sunshineo**
https://github.com/parse-community/parse-server/issues/7048

https://jira.mongodb.org/browse/NODE-2784

Is test needed for this sort of change?

### CODE REVIEW

**Comment by mtrezza** [comment]
Can you look into the failing tests? There may be a breaking change due to the adapter upgrade.

Could you also add a failing test case that demonstrates the issue you experienced?

**Comment by dplewis** [comment]
There are 2 other PRs open for this same update. I’ve had success with fixing the tests, there is one flaky test that I am looking into.

**Comment by mtrezza** [comment]
Oh, a Snyk PR, that's why there was no issue for this.

Thanks for the PR @sunshineo, I think we can close it in favor of https://github.com/parse-community/parse-server/pull/7026.

**Comment by sunshineo** [comment]
Thank you!

**Pull request closed without merging**
