### PR TITLE
3.9.0

### PR DESCRIPTION
**Pull request by davimacedo**

### CODE REVIEW

**Comment by omairvaiyani** [comment]
What do you guys currently do when writing changelogs? I use [conventional changelogs](https://github.com/conventional-changelog/conventional-changelog) as part of the release script for our production apps

**Comment by TomWFox** [comment]
Its all done manually, which wasn't too bad until recently.

**Comment by omairvaiyani** [comment]
Using conventional commits can definitely make life much easier. We'll not need to enforce commit message structure for our contributors, but we just need to enforce the [structure](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) when merging the PRs. The changelog will automatically be generated using the commit message upon release.

**Comment by TomWFox** [comment]
Yep, as long as we use squash and merge commits that works perfectly. Thanks for the info!

**Pull request merged**
