### PR TITLE
Add lock file version check to CI

### LINKED ISSUE #7326: Add CI check for package-lock
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Current, the repo takes the user generated package-lock as is. If package-lock is created by user in local environment with npm 7, there may be issue with older npm versions.

See:

- https://github.com/parse-community/parse-server/pull/7079#issuecomment-816485747

### Suggestion

Add CI check that validates package-lock version.

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Ci does not check NPM lock file version; from NPM 7 onwards the version changed.

Related issue: closes #7326

### Approach
Adds lock file version check to CI.

### TODOs before merging
none

### CODE REVIEW

**Comment by mtrezza** [comment]
Check confirmed: fails if package-lock file version is 2, passes if version is 1.

**Comment by dplewis** [comment]
We should upload a v2 package-lock file and check for that. If a v1 is uploaded for some reason this check should fail.

v2 is backwards compatible with v1

**Comment by mtrezza** [comment]
v2 is compatible with npm >7
v1 is used with npm <7

**Comment by dplewis** [comment]
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile

> One change to take note of is the new lockfile format, which is backwards compatible with npm 6 users.

**Comment by mtrezza** [comment]
So locally generated v2 lock file with npm 7 should be interpretable by node 6?

I think we can only try this out :-)

**Comment by dplewis** [comment]
I think @Moumouls was worried about the rewriting not so much as the compatibility

> ensure that Parse Server lock is not changed/rewrited

**Comment by mtrezza** [comment]
Then I don't understand the issue. 

If a local `npm i` replaces the v1 lock file with v2, but v2 is backwards compatible with v1, it shouldn't matter and we wouldn't need any check for this.

**Comment by dplewis** [comment]
> We wouldn't need any check for this

Thats was my conclusion

**Comment by mtrezza** [comment]
@dplewis I edited my comment

**Comment by Moumouls** [comment]
@dplewis  @mtrezza  the issue came from some change on how npm seems to handle v2, some packages of parse-server seems to not work under lock v2 in CI env, that's the issue i encountered on my Auth PR.

Also i see in the CI log that some package raise some support warning during `npm ci` due to the v2 lock version.

Finally since NPM 7 was published in October 13th, 2020, it's too fresh i think and can break some developers installs.

**Comment by mtrezza** [comment]
@Moumouls Did you delete and recreate the lock file or just merge the diffs?

**Comment by Moumouls** [comment]
yes @mtrezza , full re generate (no merge operation). But on my side it works, here the CI fails because the Node version of the CI is 14, and node 14 is shipped with NPM 6, so the install fail. Also i don't know what really happen if you `npm i parse-server` that contain lock v2 under a project that use Node 14/Npm 6.

**Comment by mtrezza** [comment]
> here the CI fails because the Node version of the CI is 14, and node 14 is shipped with NPM 6

Shouldn't matter as v2 is supposed to be backwards compatible 🤔

**Comment by Moumouls** [comment]
Yes may be a bug, you are right i checked npm docs:

```
Note that the file format changed significantly in npm v7 to track information that would have otherwise required looking in node_modules or the npm registry. Lockfiles generated by npm v7 will contain lockfileVersion: 2.

No version provided: an "ancient" shrinkwrap file from a version of npm prior to npm v5.
1: The lockfile version used by npm v5 and v6.
2: The lockfile version used by npm v7, which is backwards compatible to v1 lockfiles.
3: The lockfile version used by npm v7, without backwards compatibility affordances. This is used for the hidden lockfile at node_modules/.package-lock.json, and will likely be used in a future version of npm, once support for npm v6 is no longer relevant.
```

https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

**Comment by Moumouls** [comment]
Also @mtrezza these last months we encountered many issue swith `mongodb-runner` package (here responsible of the issue on the lock v2), on my company we stopped to use it, and we just replaced it with a tiny package based on `mongodb-memory-server` that i can open source.

May be we can create a nex tiny repo under parse for this package under `mongodb-testing`

here the main file example:

```js
process.env.MONGOMS_VERSION = "4.4.2";
const http = require("http");
const { MongoMemoryReplSet } = require("mongodb-memory-server");

const hostname = "127.0.0.1";
const port = 27272;

const run = async () => {
  const replSet = new MongoMemoryReplSet({
    instanceOpts: [
      {
        port: 27017, // port number for the instance
      },
    ],
    replSet: { storageEngine: "wiredTiger", dbName: "parse" },
  });
  await replSet.waitUntilRunning();
  console.info("MongDB Running");
  const server = http.createServer(async (req, res) => {
    res.statusCode = 200;
    res.setHeader("Content-Type", "text/plain");
    res.end("ok");
  });
  server.listen(port, hostname, async () => {
    await replSet.waitUntilRunning();
  });
};

run();
```

package.json

```json
{
  "name": "mongodb-launcher",
  "version": "1.0.0",
  "main": "index.js",
  "author": "People Vox",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "mongodb-memory-server": "^6.9.3"
  }
}
```
 
 Simple 🙂

**Comment by mtrezza** [comment]
The package seems to be well maintained. I guess we's have to look at compatibility, especially with Docker (alpine) and what the resource differences are.

**Comment by dplewis** [comment]
@Moumouls I'm all down for using `mongodb-memory-server`. I think only parse and a few other projects use mongodb-runner and it isn't that well maintained.

**Comment by Moumouls** [comment]
yeah, @dplewis if you are ok, i do not have rights to create a new repo under parse community. Then i can push the beginning of this tiny package or open an issue on it to draft main objectives.

**Comment by mtrezza** [comment]
How about we add this as a PR to Parse Server first before creating a separate repo? This will likely take some refinement to work in the CI, may be easier in a PR.

**Comment by Moumouls** [comment]
No problem @mtrezza the 2 options seems good to me 👍

**Comment by mtrezza** [comment]
I cannot even build with npm 7 locally, after deleting package-lock and node_modules:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: parse-server@4.5.0
npm ERR! Found: graphql@15.5.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"15.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-relay@0.6.0
npm ERR! node_modules/graphql-relay
npm ERR!   graphql-relay@"0.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Updated all to latest version and still have this issue.
We actually have the same issue reported for some time already in Parse Dashboard: 
https://github.com/parse-community/parse-dashboard/issues/1633

@dplewis I think until we resolve this, we can set the requires package-lock to v1?

**Comment by dplewis** [comment]
> we can set the requires package-lock to v1

You will still get errors if somebody deletes the package-lock file.

**Comment by mtrezza** [comment]
You mean someone deletes the lock file without rebuilding it?

**Comment by dplewis** [comment]
I think we should stick to v1. I personally delete and regenerate the package-lock files when I close the Snyx PRs sometimes.

**Comment by mtrezza** [comment]
Uhm, that's what it currently does, it passes only for v1 (npm 6). So we can merge this?

**Review by dplewis — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
