### PR TITLE
Bump tests to Mongo 4.0.23

### PR DESCRIPTION
**Pull request by davimacedo**
### New Pull Request Checklist

- [ X ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: FILL_THIS_OUT

### TODOs before merging

- [ ] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Comment by davimacedo** [comment]
We also needed to bump node 15.9.0

**Review by mtrezza — APPROVED** [review]
I already created a [PR](https://github.com/parse-community/parse-server/pull/7186) that auto-creates a bump-PR for this, but I count't get the bump-BP be to created, due to permissions.will continue to look into this.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
