### PR TITLE
The REST API key was improperly inferred from environment

### PR DESCRIPTION
**Pull request by flovilmart**
Sorry about that, this only affects CLI users, like myself... Just shot myself in the foot...

### CODE REVIEW

**Comment by flovilmart** [comment]
It’s in `.bin/parse-server` you can pass environment variables and options.

**Comment by montymxb** [comment]
I'm surprised we didn't have a test that caught this :/. Can we add something in the future to prevent this, or something similar, from recurring?

**Comment by flovilmart** [comment]
Yeah, most probably, I could add a test that validates the definition Parse properly

**Comment by flovilmart** [comment]
@acinader for using the CLI, actually, you can try the bootstrap script, it generates everything for you.

at AmpMe, we have start our server with:

```
$ node node_modules/.bin/parse-server -- config/dev.js
```

then config/dev.js

```
const push = {
  'ios': [...],
  'android': {},
  'queueOptions': {
    messageQueueAdapter: 'parse-server-gcloud-pubsub',
    disableFanOut: true,
    disablePushWorker: false,
    channel: 'ampme-parse-push-dev',
  },
};

// hard coded for now
const redisHOST = process.env.REDIS_MASTER_SERVICE_HOST;
const redisPORT = process.env.REDIS_MASTER_SERVICE_PORT;
console.assert(typeof redisHOST !== 'undefined');
console.assert(typeof redisPORT !== 'undefined');
const redisURL = `redis://${redisHOST}:${redisPORT}`;

const RedisCacheAdapter = require('parse-server').RedisCacheAdapter;
const redisOptions = { url: redisURL };
const redisCache = new RedisCacheAdapter(redisOptions, 60000 * 30);

module.exports = {
  cloud: '/opt/parse-server/cloud/main',
  jsonLogs: true,
  logsFolder: null,
  scheduledPush: true,
  appName: '[DEV] AmpMe Parse Server',
  port: 1337,
  push,
  filesAdapter: {
    module: 'parse-server-gcs-adapter',
    options: {
      directAccess: true,
      bucket: 'ampme-dev-storage',
    },
  },
  auth: {
    soundcloud: require('./auth/soundcloud'),
  },
  /* for publishing */
  liveQuery: {
    classNames: [...],
    redisURL,
  },
  /* for the subscriptions */
  liveQueryServerOptions: {
    redisURL,
  },
  startLiveQueryServer: true,
  middleware: './config/datadog',
  schemaCacheTTL: 60000,
  enableSingleSchemaCache: true,
  cacheAdapter: redisCache,
  cacheMaxSize: 1000,
  cacheTTL: 60000 * 30, // 60s
};
```

The dev.js file is loaded by the CLI and parsed accordingly.

**Comment by acinader** [comment]
Thanks.

**Pull request merged**
