### PR TITLE
Suppress Test Logs

### PR DESCRIPTION
**Pull request by dplewis**
This will reduce some of the noise in the tests logs.

### CODE REVIEW

**Comment by dplewis** [comment]
@davimacedo Can you look into the GraphQL test logs? I'm not to familiar with it. We can probably add it to a separate PR.

**Comment by davimacedo** [comment]
This commit should fix for GraphQL

**Comment by dplewis** [comment]
Nice!

**Comment by dplewis** [comment]
@davimacedo How does this look?

**Pull request merged**
