### PR TITLE
refactor: minor changes to remove mongo deprecation warnings

### LINKED ISSUE #7623: Deprectation warning returnOriginal mongo
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Getting

```
collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.
```
### Steps to reproduce
Pull master branch and run trigger findOneAndUpdate on db adapter

### Actual Outcome
A lot of deprecation warnings

### Expected Outcome
No warning
### Environment
`5.0.0-alpha.1`

We need to replace `returnOriginal` with `returnDocument` as suggested here: https://jira.mongodb.org/browse/NODE-1812

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Close #7623, #7624

Related issue: #7623, #7624

### CODE REVIEW

**Comment by mtrezza** [comment]
Not a fix, since the issue is not a bug, see [contribution](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#pull-request) guide for how to use commit types.

Can you please adapt the change log entry?

**Comment by Moumouls** [comment]
done @mtrezza

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by rocxteady** [comment]
You said it was a bug here: https://github.com/parse-community/parse-server/issues/7345#issuecomment-819498764
But you said it is not a bug here in this pull request.

**Comment by mtrezza** [comment]
It's not a bug as it doesn't require a new release. We have no "refactor" label in GitHub issues, so it was classified as trivial bug, but it's not merged a bug but as a refactor, which indeed can cause confusion. Maybe we should add a refactor label for issues.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
