### PR TITLE
pg-promise usage refactoring

### PR DESCRIPTION
**Pull request by vitaly-t**
initial refactoring for `pg-promise` usage.

### CODE REVIEW

**Comment by dplewis** [comment]
@vitaly-t I'm about to push index improvement for PG.

**Comment by vitaly-t** [comment]
@dplewis don't worry about that, there's plenty of code that's overdue for refactoring there ;)

**Comment by vitaly-t** [comment]
Oh wait sec, do we still not support `async`, ouch, my bad,... will have to change those things back...

**Comment by vitaly-t** [comment]
ok, i'll better re-do the whole thing...

**Comment by flovilmart** [comment]
Yeah we’re still building targeting 6.11, i’d prefer we wait till we make 8.11 the min version to have native async await support

**Pull request closed without merging**
