### PR TITLE
Postgres: Properly initialize database on startup and debugger

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/parse-server/issues/7021

* Ensures schema exists on start up.
* Ensures initialization is performed first by removing parallel operation.
* Fixes any `relation "_SCHEMA" does not exist` flaky tests
* Fixed any `schema does not validate` messages
* Reduces the number of `CREATE TABLE IF NOT EXISTS "_SCHEMA"` calls
* Improves testing speeds since test cleanup is moved to afterEach only.
* Improves tests that delete database but doesn't initialize.
* Add `pg-monitor` for improved debugging.

### TODOs before merging

- [ ] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Review by vitaly-t — APPROVED** [review]
At least as far as pg-monitor goes, it looks fine :)

**Comment by dplewis** [comment]
@davimacedo How does this look?

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by GEverding** [comment]
Might be off topic but when is this expected to be released officially? Seeing this in my setup as well.

**Comment by mtrezza** [comment]
@GEverding See https://github.com/parse-community/parse-server/issues/7271#issuecomment-866860698.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
