### PR TITLE
Allow coordinate pairs in $geoWithin/$polygon query

### PR DESCRIPTION
**Pull request by madsb**
This pull requests allows for a polygon that consists of an array of basic coordinate pairs besides an array of `Parse.GeoPoint`s.

### CODE REVIEW

**Comment by dplewis** [comment]
Can you add support for PFPolygon?

**Comment by madsb** [comment]
@dplewis, I’m not sure I understand. Looks like the iOS SDK already supports withinPolygon queries?

**Comment by dplewis** [comment]
@madsb never mind as it would require change to all sdks

**Comment by madsb** [comment]
Ah, I see - you mean adding something like Parse.Polygon to the JS SDK? I briefly considered that but seemed like it would take a little more time than I had.

**Comment by dplewis** [comment]
Parse.Polygon is already in parse-server

**Comment by madsb** [comment]
@dplewis That's correct, but I was talking about the JS SDK.

Anyway, I think I've found a bug. When saving a Polygon object to the database, the coordinates are saved as [lat, lon] pairs. But mongo expects [lon, lat] which makes $geoIntersect queries fail.

**Comment by dplewis** [comment]
@madsb For that I'm just waiting for parse-server 2.6.0 to be released then I'll rerun the tests. It works locally.

**Comment by madsb** [comment]
The tests are succeeding with the test coordinates, but try running the `polygon save open path` with these real-life coordinates:

```
const coords = [[33.5746,-111.9250],[33.4769,-112.0002],[33.4761,-111.8391]];
const closed = [[33.5746,-111.9250],[33.4769,-112.0002],[33.4761,-111.8391],[33.5746,-111.9250]];
```

**Comment by madsb** [comment]
Alright, never mind... I was confused about the whole lat/lon lon/lat thing. GeoJSON is lon/lat, and thus I must also define lon/lat when saving my Polygon object. Pretty confusing when everything else in Parse is lat/lon 😬

**Comment by dplewis** [comment]
Yeah WGS84 is annoying. What about __type: Polygon to this PR?

**Comment by madsb** [comment]
Yeah, my epiphany above has kind of invalidated this pull request, so I'll close this and open a new one with `__type === 'Polygon'`.

**Comment by madsb** [comment]
@dplewis #4067

**Pull request closed without merging**
