### PR TITLE
refactor: Change response types of TOTP adapter to match existing adapters

### LINKED ISSUE #8660: Refactor TOTP adaper to return strings
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

As discussed in #8457, mixed return types for the TOTP adapter makes it incompatible with certain client SDKs

### Feature / Enhancement Description

Refactor adapter to return strings

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

The TOTP adapter has mixed return types, making it incompatible with strongly typed client SDKS.

There's also an additional issue with the TOTP adapter that is fixed in this PR as well.

Closes: #8660

## Approach

Changes the response of `enabled: true` to `status: "enabled"`

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by dblythy** [comment]
@cbaker6 let me know if this looks better

**Comment by cbaker6** [comment]
@dblythy the updates look good to me

**Comment by dblythy** [comment]
I’ve just realised I’ve missed one thing

**Comment by dblythy** [comment]
@cbaker6 I've also adapted the "additional auth data" when logging in,

Previous:

```js
{
  username: 'username',
  password: 'password',
  authData: {
   mfa: totp.generate()
  },
}
```

New:

```js
{
  username: 'username',
  password: 'password',
  authData: {
   mfa: {
     token: totp.generate()
   }
  },
}
```

Is this correct?

**Comment by mtrezza** [comment]
> Is this correct?

That depends on what `totp.generate()` returns. Could you give an example?

**Comment by mtrezza** [comment]
```
{
  username: 'username',
  password: 'password',
  authData: {
   mfa: {
     token: totp.generate()
   }
  },
}
```

would be a type structure of:

```
authData: object<string: object<string: string>>
```

It would be the same type structure that is in the REST API [example](https://docs.parseplatform.org/rest/guide/#signing-up-and-logging-in):

```
{
  "authData": {
    "twitter": {
      "id": "12345678",
      "screen_name": "ParseIt",
      "consumer_key": "SaMpLeId3X7eLjjLgWEw",
      "consumer_secret": "SaMpLew55QbMR0vTdtOACfPXa5UdO2THX1JrxZ9s3c",
      "auth_token": "12345678-SaMpLeTuo3m2avZxh5cjJmIrAfx4ZYyamdofM7IjU",
      "auth_token_secret": "SaMpLeEb13SpRzQ4DAIzutEkCE2LBIm2ZQDsP3WUU"
    }
  }
}
```

So that should be good I'd say. Is any of this a breaking change, or is this PR only affecting code on the pre-release branches?

**Comment by dblythy** [comment]
Only affects the alpha branch

**Comment by mtrezza** [comment]
So now both the request and response have a type structure of:

```
authData: object<string: object<string: string>>

```

Is that right?

**Comment by dblythy** [comment]
Correct! Which should allow for easier integration in strongly typed SDKs, such as the SwiftSDK

**Comment by mtrezza** [comment]
Sounds good, I'll re-run the CI until it passes

**Comment by mtrezza** [comment]
Is this ready for merge?

**Comment by dblythy** [comment]
@cbaker6 did you want to have one final review before we merge?

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)

**Comment by REPTILEHAUS** [comment]
> consumer_secret

@mtrezza I mentioned on the forum also but is it really fine to store any of the *_secret API keys on each user authData ?

**Pull request merged**
