### PR TITLE
refactor: Upgrade mongodb to 4.14.0

### PR DESCRIPTION
**Pull request by tomkretzschmar**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue
Closes: n/a

- Parse-server loses mongoDB connection in a k8s setup when mongoDB primaries are restarted.
- This is fixed in node-mongodb-native [v4.11.0](https://github.com/mongodb/node-mongodb-native/compare/v4.10.0...v4.11.0)

## Approach

- Upgrade mongodb driver to v4.14.0

### CODE REVIEW

**Comment by mtrezza** [comment]
There are quite a lot of changes in package lock. Which npm commands did you run? Seems like it contains more than only the mongodb upgrade?

**Comment by tomkretzschmar** [comment]
I ran `npm install mongodb@4.14` as `npm update mongodb` didn't result in any chances due to no version range being specified in the package.json

**Comment by mtrezza** [comment]
This looks all strange. Even the package version is not a semver syntax. Could you please revert everything (or start a new PR) and then just run `npm i -E mongodb@4.14.0`.

Btw the newest version is 15.x, in case you want to upgrade to that. But that would likely require you to also make some code changes.

**Comment by tomkretzschmar** [comment]
Did so, same changeset. 

Updated the description, 4.14 is enough for us currently.

**Comment by mtrezza** [comment]
Hard to believe that version `4.14` is the result of this. It's not semver conform.

**Comment by tomkretzschmar** [comment]
output of `npm i -E mongodb@4.14.0` 

```
 ~/repos/parse-server  upgrade-mongodb  npm i -E mongodb@4.14.0                    [10:57:25]

added 74 packages, removed 1 package, changed 1 package, and audited 1877 packages in 8s

124 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (1 low, 9 moderate, 18 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

reset, updated again and force pushed the branch.

**Comment by mtrezza** [comment]
Looks better, the version is now correct: `"mongodb": "4.14.0"`

**Comment by mtrezza** [comment]
So it seems that, even though the upgrade is likely not a breaking change, the tests need to be adapted for the upgrade.

**Comment by mtrezza** [comment]
Closing due to inactivity.

**Pull request closed without merging**
