### PR TITLE
fix: Parse Server option `maxLogFiles` doesn't recognize day duration literals such as `1d` to mean 1 day

### LINKED ISSUE #6426: There is a bug if maxLogFiles suffer with d
Hello guys,

I test my app with config :
--appId xxx --masterKey xxx --databaseURI mongodb://xxx  --maxLogFiles  20
It's right.

but,if I write this like :
--appId xxx --masterKey xxx --databaseURI mongodb://xxx  --maxLogFiles  20d
It's wrong.

undefined:1
20d
  ^
SyntaxError: Unexpected token d in JSON at position 2

I find the code in follow file.

./lib/Options/parsers.js

function objectParser(opt) {
  if (typeof opt == 'object') {
    return opt;
  }
  return JSON.parse(opt);
}

I hope can  fix it,Thank you.

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

The `maxLogFiles` option uses an objectParser which fails when entering a string.

Closes: https://github.com/parse-community/parse-server/issues/6426

## Approach

Add new Parser Type and Build Definition

### CODE REVIEW

**Comment by mtrezza** [comment]
Note: before merging this, merge https://github.com/parse-community/parse-server/pull/9205 so that it creates a release with test IDs.

**Review by mtrezza — APPROVED** [review]
Looks good

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.5](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)

**Pull request merged**
