### PR TITLE
Improve ci lint

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Lint is currently executed in an anti-pattern that poses a high risk of not being executed in case of a name change of an unrelated test.

Related issue: (none, due to simply meta fix)

### Approach
Moved lint to be a separate CI task, independent of other tests.

### TODOs before merging

(none)

### CODE REVIEW

**Comment by mtrezza** [comment]
Additionally, the "Lint" check should be marked as mandatory in the repo settings.

**Review by dplewis — APPROVED** [review]
LGTM! I'll close mine.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
