### PR TITLE
Fix max listener warning from livequery server

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
max event listener on our test and can occur for developers in their own tests

Related issue: FILL_THIS_OUT

### Approach
Clean event emitter

### TODOs before merging

- [x] Add test cases
- [ ] Add entry to changelog
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [x] Add new Parse Error codes to Parse JS SDK 
- [ ] ...

### CODE REVIEW

**Review by dplewis — APPROVED** [review]
Thanks for the PR. The warning has been removed from the build test logs.

**Comment by dplewis** [comment]
@Moumouls Speaking of clean builds, we should remove the console.logs from the test suite at some point

**Comment by Moumouls** [comment]
> @Moumouls Speaking of clean builds, we should remove the console.logs from the test suite at some point

the object not found log ?

**Comment by dplewis** [comment]
Yeah that one

**Comment by Moumouls** [comment]
@dplewis 

Do you have any idea which test it comes from?

**Comment by dplewis** [comment]
I don't unfortunately. Removing the console.log would remove it

**Comment by Moumouls** [comment]
> I don't unfortunately. Removing the console.log would remove it

Do you know a way to log the current test file with jasmine during `npm test` otherwise finding the source will be hard  😉

**Comment by dplewis** [comment]
> Do you know a way to log the current test file with jasmine

We did have jasmine-spec-reporter at one point but we removed it since it added a two minutes to the test speeds and the logs were really long.

`EnableExpressErrorHandler.spec.js` is where it happens

**Comment by Moumouls** [comment]
okay we are now ok @dplewis , it seems that the log come from express, the only way i found to hide this log is to spy console
@mtrezza we can merge this one now ? 😃

**Review by dplewis — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
