### PR TITLE
Support Distinct for special fields

### PR DESCRIPTION
**Pull request by dplewis**

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart I dismissed your review, can you approve and merge?

**Comment by LilMoke** [comment]
dplewis, can I perform a distinct query from an iOS app?  I did not see it in the doc and in the issues about distinct it looks like it may need to be done from a cloud function.  Can you give me a bit more info please?

Best

**Comment by dplewis** [comment]
Distinct requires Master Key so it can’t be used on the client side. Cloud code should be used in your case.

**Comment by LilMoke** [comment]
So do you have an example of how it would be used?  Cloud code is fine, my backend is Node.js.

Thanks for the info.


On Aug 21, 2019, at 10:45 AM, Diamond Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


Distinct requires Master Key so it can’t be used on the client side. Cloud code should be used in your case.

**Comment by dplewis** [comment]
You can check the JavaScript guide.

const query = new Parse.Query("User");
query.distinct("age")
  .then(function(results) {
    // results contains unique age
  })
  .catch(function(error) {
    // There was an error.
  });

**Comment by LilMoke** [comment]
Awesome, thank you!! You have been a big help!!


On Aug 21, 2019, at 12:48 PM, Diamond Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


You can check the JavaScript guide.

const query = new Parse.Query("User");
query.distinct("age")
.then(function(results) {
// results contains unique age
})
.catch(function(error) {
// There was an error.
});

**Pull request merged**
