### PR TITLE
feat: add support for Node 17 and 18

### LINKED ISSUE #7708: Add Node 17 compatibility
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Parse Server does not have a CI job with Node 17.

### Feature / Enhancement Description
Add Node 17 CI job (similar to the currently existing Node 14 CI job) and make it pass.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: #7708 

This PR is a continuation of https://github.com/parse-community/parse-server/pull/7710, thanks to @marvinroger.

### TODOs before merging

- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
There are still 2 tests failing:

```
1) ParseGraphQLServer Auto API Schema Files Mutations Create should return File object
  - FetchError: request to http://localhost:13377/graphql failed, reason: socket hang up

2) ParseGraphQLServer Auto API Schema Data Types should support files
  - Failed: request to http://localhost:13377/graphql failed, reason: socket hang up
```

**Comment by Moumouls** [comment]
@mtrezza  the source was node-fetch 3.X uses ESM, and it seems to fail in the file upload case. It's not a parse-server error. 

This is patched with https://github.com/parse-community/parse-server/pull/7967/commits/89f29051d8a870f308c651b76834cb7e84cf83aa

On the graphql yoga PR, the failing tests are working on Node 17/18

**Comment by mtrezza** [comment]
Alright, I'll take a look.

**Comment by mtrezza** [comment]
This was actually already patched some time ago in https://github.com/parse-community/parse-server/pull/7782

**Comment by mtrezza** [comment]
I don't think moving backwards in versions is a solution; maybe move from node-fetch to another library to fix this? `ParseGraphQLServer.spec.js` is the only file using `node-fetch` it seems.

**Comment by Moumouls** [comment]
yes @mtrezza  node-fetch is used to test multi-part upload on the graphql server. I tried to use another lib (like cross undici fetch), but other tests start to fail since it seems not fully compatible with apollo/client. node-fetch 3 from my knowledge is fully ESM, and it seems to not work properly with Jasmine.

We are safe to stick with node-fetch 2.6. At this time since it works and only impacts the test suite, on my side I'll not dedicate more time to this issue 🙂

**Comment by mtrezza** [comment]
> We are safe to stick with node-fetch 2.6

I would say quite the opposite. We'll just disable the GraphQL upload tests for now. We'll open an issue that these tests are disabled to keep track of that. Another instance that shows that GraphQL should have been implemented as an optional add-on in Parse Server and not integrated into the core code, see https://github.com/parse-community/parse-server/issues/7979.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.8](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-server/releases/tag/5.3.0)

**Pull request merged**
