### PR TITLE
fix: errors in GraphQL do not show the original error but a general `Unexpected Error`

### LINKED ISSUE #8044: Masked errors on graphql API since Yoga
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Error are masked by Yoga GraphQL server.

### Steps to reproduce
Throw an error into a custom resolver or custom query

### Actual Outcome
Original error converted to "Unexpected Error"

### Expected Outcome
To return the original error to the client.

### Environment

Server
- Parse Server version: `5.3.0-alpha.16`
- Operating system: `Macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `5.X`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `_`
- SDK version: `_`

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: #8044

### Approach
Disable error masking on Yoga

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by Moumouls** [comment]
@mtrezza any feedback on this one ?

It's important to get this one merged asap, since the switch to Yoga, all GQL errors are now masked. This bug could break error feedback on gql custom API and also error handling on client apps.

**Comment by mtrezza** [comment]
Switch to yoga is only in alpha, so there's no rush to merge this. Ideally we should merge this before making a beta release.

**Review by mtrezza — APPROVED** [review]
Looks good code-wise, but requires a more descriptive PR title.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-server/releases/tag/5.3.0)

**Pull request merged**
