### PR TITLE
refactor: Upgrade pg-promise from 11.5.0 to 11.5.4

### LINKED ISSUE #8901: pg-promise and node-postgres are out-of-date
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The dependencies pg-promise and node-postges are not up-to-date.

### Feature / Enhancement Description

Update to the latest versions.

### Example Use Case

N/A

### Alternatives / Workarounds

Force updating packages in dedicated projects.

### 3rd Party References

N/A

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

pg-promise is  not up-to-date and the node-postgres driver pg-promise depends on is out-of-date.

Closes: #8901 

## Approach

Update pg-promise to 11.5.4 along with related dependencies.

## Tasks

- [x] Ensure CI passes

### CODE REVIEW

**Comment by cbaker6** [comment]
Ready for review...

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.19)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
