### PR TITLE
feat: Update ldap

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8592

## Tasks

- [x] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by dblythy** [comment]
It seems that this update isn't compatible with Node 14

**Comment by mtrezza** [comment]
Thanks, well merge the PR in ~6~ 4 month then, when we prepare the Parse Server 7 release that drops Node 14 support.

**Comment by suathh** [comment]
Hey, @dblythy , we plan to release this update in version 7, but there is currently a conflict with this PR. Can you please take a look to resolve that?

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/8947

**Pull request closed without merging**
