### PR TITLE
ci: Fix docker image pushing to Docker Hub

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Related issue: #7547 

### Approach

Use GitHub Actions to push to Docker hub during merges of PRs and releases. Merges to the master branch push the latest image to `latest` on Docker Hub and releases push the latest release with the same tag name. You can see the tags this creates using my research repo: https://hub.docker.com/repository/docker/netreconlab/parse-dashboard

This builds images for multiple architectures as oppose to just Intel. Builds for all of same architectures as it’s dependency image, [node:lts-alpine](https://registry.hub.docker.com/layers/node/library/node/lts-alpine/images/sha256-63266a0ed3c7c090e70d8bc21af85586024dd13f22a7fa30cfbac5c343836aa3?context=explore) except for `linux/ppc64le` and `linux/s390x` as those both currently fail.

A side-effect is it creates another tag on docker-hub called `master`, which I guess could be useful if something else is pushed after `latest`

### TODOs before merging

- [x] Add environment variables mentioned in https://github.com/parse-community/parse-dashboard/pull/1781
- [x] Add entry to changelog

### CODE REVIEW

**Comment by cbaker6** [comment]
If you want to add docker images for missing versions on docker hub (4.5.2 - 4.10.3), cherry pick this commit and in `` change `latest=true` to `latest=false`

**Comment by mtrezza** [comment]
@dplewis Do you have the docker hub credentials?

**Comment by cbaker6** [comment]
Corrected a spelling error that's been around for awhile: https://github.com/parse-community/parse-server/blob/5ab974dcd47906efb41edb6c709c4e078cabaa7f/src/LiveQuery/ParseWebSocketServer.js#L14

**Review by mtrezza — APPROVED** [review]

**Comment by cbaker6** [comment]
It looks like the multi-platform images worked! https://hub.docker.com/r/parseplatform/parse-server/tags?page=1&ordering=last_updated

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
