### PR TITLE
improve test code

### PR DESCRIPTION
**Pull request by sunshineo**
1. proper name to describe what the test does
2. remove creation of extra Parse server instance
3. remove the strange file of rest routes for testing
4. use async await

Only the first test in ParseAPI.spec.js was changed, other changes in the file due to eslint
Only removed line 150 in helper.js, other changes in the file due to eslint

### CODE REVIEW

**Comment by sunshineo** [comment]
The test failure on travis has nothing to do with my change. All tests passed locally

**Comment by davimacedo** [comment]
I'm not sure if we should remove it yet. @dplewis @acinader thoughts?

**Comment by sunshineo** [comment]
@davimacedo Sounds like there are some stories?

**Comment by dplewis** [comment]
Does it actually create an extra parse server instance? Looks like it would only be created when you call the `rest_create_app` endpoint (only used in the tests you changed).

**Comment by acinader** [comment]
I don't have an opinion.

It would be helpful in the future to break a change like this into two commits: 1. to apply current lint rules 2. the change itself.

**Comment by sunshineo** [comment]
@acinader that is a good idea, I can try that later this weekend

**Comment by dplewis** [comment]
Superced by https://github.com/parse-community/parse-server/pull/7121

@sunshineo Thanks for finding this. I spend hours on tests just to find this.

**Pull request closed without merging**
