### PR TITLE
Remove duplicate CHANGELOG for `Parse.Cloud.sendEmail`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

I accidentally entered sendEmail twice in the CHANGELOG.

Related issue: -

### CODE REVIEW

**Comment by mtrezza** [comment]
Would you mind also ordering the entries the in recent change log?
I already did that, but we have no guideline regarding this yet.


I think this order makes most sense:
- New
- Improve
- Fix

We should also only use these 3 labels for consistency.

**Comment by dblythy** [comment]
> Would you mind also ordering the entries in change log master section?

Easy, should we perhaps group them so it's more intuitive for new contributors?

Such as:

**New:**
-`Parse.Cloud.sendEmail` thanks to xx
-
-

**Improve**
-
-
-

**Fix**:
-
-

**Comment by mtrezza** [comment]
Nice! Thanks!

**Review by mtrezza — APPROVED** [review]

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
