### PR TITLE
refactor: upgrade @graphql-yoga/node from 2.6.0 to 2.6.1

### PR DESCRIPTION
**Pull request by dplewis**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade @graphql-yoga/node from 2.6.0 to 2.6.1.</h3>

merge advice
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **3 versions** ahead of your current version.
- The recommended version was released **22 days ago**, on 2022-05-23.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>@graphql-yoga/node</b></summary>
    <ul>
      <li>
        <b>2.6.1</b> - 2022-05-23
      </li>
      <li>
        <b>2.6.1-canary-bfb3b22.0</b> - 2022-05-23
      </li>
      <li>
        <b>2.6.1-canary-65224d9.0</b> - 2022-05-23
      </li>
      <li>
        <b>2.6.0</b> - 2022-05-12
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/releases">@graphql-yoga/node GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>@graphql-yoga/node</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/b6d5c46f2ef09980a4ccdd01f3e369afd206f9ff">b6d5c46</a> chore(release): update monorepo packages versions (#1228)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/e1b031d00e5f99a41af7dca60a7807f8293244fc">e1b031d</a> chore(deps): update dependency bob-tsm to v1 (#1221)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/0224bf9932cebde9c021d27ff9aa54bed820cc0f">0224bf9</a> fix: prevent status, headers and orginalError being exposed as extension fields (#1226)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/efae9d9fb216c41075ca28c7ffceadedbf6c1e54">efae9d9</a> fix(deps): update dependency @ pulumi/pulumi to v3.33.1 (#1224)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/5f9b323a54e8996b3d08479e5185b542065f8ecc">5f9b323</a> chore(deps): update all non-major dependencies (#1223)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/35bec62a02c92fa0c580c794c4f28959e99169ac">35bec62</a> fix(deps): update dependency @ pulumi/azure-native to v1.64.1 (#1222)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/e407e2b4ba131a92d344cafb379187d6cbb600c1">e407e2b</a> chore(ci): avoid falsy negatives make @ ardatan happy</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/b7a357bd1c3201c4fe4b6ed344f2da397bb293da">b7a357b</a> Update algolia-lockfile.json</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/32021a38ce0370b5de14fd6b7db2afa94a8bf0a7">32021a3</a> Fixes spelling mistakes in tutorial (#1218)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/e0902594308112ea40bd0da23792494925344f96">e090259</a> chore(deps): update all non-major dependencies (#1219)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/4e540b304df8c78f473c0412faeefbec93d5e846">4e540b3</a> chore(deps): update all non-major dependencies (#1216)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/1fa18fb9a64060d72f3ad819098bbeac73465235">1fa18fb</a> apply &#x60;@ typescript-eslint/no-unused-vars&#x60; rule fixes (#1212)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/50ba6fa4513fa6ee5e0e27b90ccf1b472ff76e86">50ba6fa</a> apply &#x60;react/jsx-curly-brace-presence&#x60; rule fixes (#1209)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/22c9730d13f86b76e3c9eae10a9f1ef00b219121">22c9730</a> apply &#x60;prefer-const&#x60; rule fixes (#1211)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/9120907bec16d1da1ce429b560d8ef3dfcac80f5">9120907</a> apply &#x60;unicorn/no-lonely-if&#x60; rule fixes (#1210)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/291eac99f3cc6a4c178c5e7cd87a8d1f5896117b">291eac9</a> apply &#x60;object-shorthand&#x60; rule fixes (#1208)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/838aba59394eaf1661d9ad918fe1a84a1e00b200">838aba5</a> apply &#x60;no-else-return&#x60; rule fixes (#1207)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/fced041a6a61ee6114ee6f902ab378e791793b2d">fced041</a> docs: fix envelop plugins link (#1205)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/dd6467c12df0be262399b637b2a464b556a58607">dd6467c</a> chore(deps): update dependency puppeteer to v14.1.0 (#1204)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/b4cfcc90a2a8ce33b434a147b6ba1da30613c8e9">b4cfcc9</a> chore(deps): update dependency @ types/react-dom to v17.0.17 (#1201)</li>
      <li><a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/commit/3ac55dc61544d203606a90fcc5214faa38f6ebf3">3ac55dc</a> Try out a new issue report template format (#1197)</li>
    </ul>

   <a href="https://snyk.io/redirect/github/dotansimha/graphql-yoga/compare/b377635c3a8bf3da0c5e6537e7295d8d19c28271...b6d5c46f2ef09980a4ccdd01f3e369afd206f9ff">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/acinader/project/21343059-02d9-4182-87d7-718a44b181ef/settings/integration?pkg&#x3D;@graphql-yoga/node&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by mtrezza** [comment]
Interesting that a patch version upgrade causes tests to fail. Either yoga didn't follow semver, or our tests are too strict.

**Comment by Moumouls** [comment]
@mtrezza I sent a message to the Guild, they will investigate asap I think.

The failing test is related to an addition that I asked about max file upload size to keep same features as the old graphql-upload package. May be something is not correctlu covered on their side and our test suite has catched the error. I added this test during the Yoga gql switch ☺️

**Comment by n1ru4l** [comment]
Hey there, we decided that the status code 500 is incorrect as the user is responsible for sending a file that exceeds the limit. Thus 400 makes a lot more sense. We treated this change as a bug fix.

**Comment by Moumouls** [comment]
thanks @n1ru4l  i'll take a look to update the test

**Comment by mtrezza** [comment]
@n1ru4l Changing the error code is a breaking change; does that mean Yoga doesn't follow semver?

**Comment by n1ru4l** [comment]
Hey @mtrezza, Yoga follows semantic versioning. Sometimes it is hard to define what is considered a breaking change. From our perspective, the file upload limit was undocumented and treated as unstable. As we are adding tests for the feature we realized that we implemented it not according to the reference specification. https://github.com/jaydenseric/graphql-upload/blob/b1cdd2a913c5394b5ff5f89b28d79b949b0bdde5/processRequest.js#L175 Apparently we also messed up again as the status code should be 413. 😭
We treated this as a bug fix as we did not see wide adoption. Is this a deep concern for the users that are already using parse-server file uploads? If it is a big issue we can discuss reverting it and postponing this fix (or breaking change) for the next major version.
And shoutouts to your test suite, the coverage is really impressive!

**Comment by mtrezza** [comment]
In semver any breaking change (of an exposed API) requires a major increment, regardless of adoption rate. I'm asking for us to know whether we have to be careful in the future when upgrading Yoga if it follows a "romantic" interpretation of semver.

**Comment by n1ru4l** [comment]
> Yoga if it follows a "romantic" interpretation of semver

Do you treat something like adding a property to an object as a breaking change? If someone uses `Object.entries` on that object or maps over a TypeScript type that could also be considered a breaking change. It is really hard to define a breaking change to the latest detail and there is no document that defines it clearly. What guidelines are you following to define what is and is not a breaking change?

We aim to follow strict semantic versioning and will take your concern into account regarding future "romantic breaking" changes.

**Comment by mtrezza** [comment]
> If someone uses Object.entries on that object or maps over a TypeScript type that could also be considered a breaking change. 

In projects where a high level of stability is required, these aspects are usually defined. You could say "the order / number of properties may change". I don't think we are at this level however when talking about a HTTP response code. If the response code is part of the public API, then strictly following semver means it's a breaking change.

**Comment by Moumouls** [comment]
Hi @mtrezza , @n1ru4l, I think that a breaking change was maybe introduced. 

But this is why I added a test during my development on yoga since I know that the size limit feature was introduced in yoga for Parse Server to meet our requirements for the migration.

Btw, @mtrezza @n1ru4l, anyone open to send the really quick PR to fix the status code ? ☺️

**Comment by mtrezza** [comment]
Closing due to conflicts; waiting for snyk to open a new PR.

**Pull request closed without merging**
