### PR TITLE
docs: jsdoc clean theme

### PR DESCRIPTION
**Pull request by okobsamoht**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues/8017).

### Issue Description

Modernize API doc template
change the jsdoc theme form the @parse/minami to clean-jsdoc-theme

### TODOs before merging

- [x] Check graphical identity

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
I don't think this was correctly installed. There are no changes to package-lock.

**Comment by okobsamoht** [comment]
oh! sorry. i forgot commiting the package-lock.json as i installed everything via yarn.
i'll add it...

**Comment by Moumouls** [comment]
HI @okobsamoht , i think you need to restore the package lock from alpha branch.
Also you have changed the lockfile version to v2.

To easily avoid a change to v2, use `nvm` and switch to Node 14 then run `npm i`

@mtrezza what do you think about switching to lock v2 in a separate PR since it's now the default version since Node 16/Npm 8 ?

**Comment by mtrezza** [comment]
> @mtrezza what do you think about switching to lock v2 in a separate PR since it's now the default version since Node 16/Npm 8 ?

As long as we're supporting a Node version that uses v1 natively, we stick with v1 (despite backwards-compatibility).

**Review by okobsamoht — COMMENTED** [review]
restored package-lock file from current parse-server/alpha

**Comment by mtrezza** [comment]
@okobsamoht Isn't there a related open issue for this PR? I can't find the ref in the PR description.

**Review by mtrezza — COMMENTED** [review]
Isn't there a related open issue for this PR? I can't find the ref in the PR description.

I also don't believe this is the full PR because I remember in the issue I've mentioned a customization in the current template. That's why we need the issue referenced in the PR.

**Comment by Moumouls** [comment]
thanks @okobsamoht  for the package lock restoration. Is it possible to add some screenshot of the new jsdoc theme here ?
It could helps to understand the before and after 👍

**Comment by okobsamoht** [comment]
hi @Moumouls 
bien sûr.

\[removed duplicate lengthy comment, please see screenshots already posted in the [issue](https://github.com/parse-community/parse-server/issues/8017#issuecomment-1144017081)]

**Comment by okobsamoht** [comment]
> Isn't there a related open issue for this PR? I can't find the ref in the PR description.
> 
> I also don't believe this is the full PR because I remember in the issue I've mentioned a customization in the current template. That's why we need the issue referenced in the PR.

here is the issure: https://github.com/parse-community/parse-server/issues/8017

i'll try the customization in the current theme

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/8519

**Pull request closed without merging**
