### PR TITLE
refactor: lru-cache maxAge to ttl

### PR DESCRIPTION
**Pull request by Moumouls**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Close: https://github.com/parse-community/parse-server/pull/7985

Related issue: [FILL_THIS_OUT](https://github.com/parse-community/parse-server/pull/7985)

### Approach
maxAge to ttl

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by dblythy — APPROVED** [review]
LGTM

**Review by mtrezza — APPROVED** [review]
Looks good, waiting for CI to pass.

**Comment by Moumouls** [comment]
@mtrezza  what you think about increasing CI max time to 20min it seems that's too short for mongo 5.X

**Comment by mtrezza** [comment]
We should rather look into why installing takes so long, otherwise we just keep spending resources. It's likely a dependency that's using an insecure protocol. Opened https://github.com/parse-community/parse-server/issues/8041 to fix this.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-server/releases/tag/5.3.0)

**Pull request merged**
