### PR TITLE
feat: Reduce Docker image size by improving stages

### LINKED ISSUE #8360: Docker image doesn't conform to best practices
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The Dockerfile currently doesn't conform to the [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) or [alpine recommendations](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md). This results in a larger than necessary compressed/decompressed image.

### Feature / Enhancement Description

The current compressed parse-server image size(~93MB) can be as close as possible to the lts-alpine image size (~50MB) by following best practices for constructing a Dockerfile. I've built a [docker image of parse-server:6.0.0-alpha.17](https://hub.docker.com/layers/netreconlab/parse-server/docker/images/sha256-8bdd7ac3fb5c945976ecbbd617a1f6801adf0c373b5221e86924b26841e2d0fb?context=repo) with the changes in this PR and it resulted in a **68MB** compressed image compared to the [parse-community version](https://hub.docker.com/layers/parseplatform/parse-server/6.0.0-alpha.17/images/sha256-3a2898ce84439aa56b6b91467141c5d56a69925620a50777fcc6dc744cdeb431?context=explore) of **93MB; 27% smaller**.

### Example Use Case

Create an image from this image.

### Alternatives / Workarounds

Use bloated image as is.

### 3rd Party References

Noted in limitation links.

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

The Dockerfile currently doesn't conform to the [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) or [alpine recommendations](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md). This results in a larger than necessary compressed/decompressed image.

The current compressed parse-server image size(~93MB) can be as close as possible to the lts-alpine image size (~50MB) by following best practices for constructing a Dockerfile. I've built a [docker image of parse-server:6.0.0-alpha.17](https://hub.docker.com/layers/netreconlab/parse-server/docker/images/sha256-8bdd7ac3fb5c945976ecbbd617a1f6801adf0c373b5221e86924b26841e2d0fb?context=repo) with the changes in this PR and it resulted in a **68MB** compressed image compared to the [parse-community version](https://hub.docker.com/layers/parseplatform/parse-server/6.0.0-alpha.17/images/sha256-3a2898ce84439aa56b6b91467141c5d56a69925620a50777fcc6dc744cdeb431?context=explore) of **93MB; 27% smaller**.

Closes: #8360

### Approach

Follow the best practices linked above to properly build the image in stages. This results in a smaller image (I've observed >120MB smaller decompressed parse-server image on my system) and a faster build that better leverages cache for rebuilding when changes are made. 

For example, when installing packages, [alpine docs](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache) and [docker docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds)(uses `git` in example code like parse-server) state to use `--no-cache`.

In addition, the build stages better matches the [parse-dashboard Dockerfile](https://github.com/parse-community/parse-dashboard/blob/alpha/Dockerfile) which is a lot closer to the best practices.

Lastly, the current image uses `--production` where it should use `--omit=dev` resulting in additional warnings being thrown in the docker build. This is discussed on [stackoverflow](https://stackoverflow.com/a/9276112/4639041).

#### Breaking
This will break developer images who depend on `git` already being installed in the parse-server image. This is because of line below was added to the `release` stage in commit https://github.com/parse-community/parse-server/commit/f1619e428e30149acc5453e804027f85395b45a6 and shouldn’t be there: https://github.com/parse-community/parse-server/blob/d19acf1c1a594566409c152f513d670167aabdc8/Dockerfile#L30-L31. The [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers) states:

> Where possible, use [multi-stage builds](https://docs.docker.com/build/building/multi-stage/), and only copy the artifacts you need into the final image. This allows you to include tools and debug information in your intermediate build stages without increasing the size of the final image.

The line above was probably added because the image was already `installing` in the `release` stage while it should only install in the `build` stage. The [docker docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#dont-install-unnecessary-packages) also states:

> Don’t install unnecessary packages
> To reduce complexity, dependencies, file sizes, and build times, avoid installing extra or unnecessary packages just because they might be “nice to have.” For example, you don’t need to include a text editor in a database image.

Meaning apps like `git` should never be installed on the released image of parse-server. Others can/should install if needed. If developers really need `git`, they should install it directly when creating their respective Dockerfile:

```yml
FROM parseplatform/parse-server:latest

USER root
RUN apk --no-cache add git
```

### TODOs before merging

- [x] Verify new image works
- [x] Verify new image is smaller than the current

### CODE REVIEW

**Comment by cbaker6** [comment]
This PR is ready for review

**Comment by cbaker6** [comment]
@dblythy can you look this over when you get some free time. Let me know if the changes needs further explanation or improvements

**Comment by cbaker6** [comment]
@dplewis you may want to look at this PR as well as it removes a change you made in a previous commit. I explain in the description why the code you added is removed and results in a breaking change for those who depend on the docker image.

**Comment by dblythy** [comment]
This is an exciting improvement - but unfortunately I’m not overly familiar with docker so I can’t provide much value with a review

**Comment by cbaker6** [comment]
The improvements are even larger when using the revisions of the Dockerfile in this PR for 5.4.0. The current compressed parse-server image size(~115MB). Remember the lts-alpine image size (~50MB). I've built a [docker image of parse-server:5.4.0](https://hub.docker.com/layers/netreconlab/parse-server/release/images/sha256-6a9a9d64815365d31bd225abbf6d8de64eb141b29ca77c9e5ca9e6e5c455309f?context=repo) with the changes in this PR and it resulted in a **64MB** compressed image compared to the [parse-community version](https://hub.docker.com/layers/parseplatform/parse-server/5.4.0/images/sha256-be06d7ca4e87afa674f9056dfd8b6de0d4a9c014c0fd8244cfc1862443f1fe44?context=explore) of **115MB; 44% smaller** (you can compare the docker layers in the links to see why). So the current Dockerfile has significant amount of bloat due to its current construction.

**Comment by mtrezza** [comment]
Suggested breaking change note in changelog:

> The Docker image does not contain the git dependency anymore; if you have been using git as a transitive dependency it now needs to be explicitly installed in your Docker file, for example with `RUN apk --no-cache add git`

**Comment by cbaker6** [comment]
The breaking change comment works for me

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.24](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.24)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
