### PR TITLE
Granular CLP pointer permissions 

### PR DESCRIPTION
**Pull request by BufferUnderflower**
Tracking issue #6351
Previously requested with #4251, #4045

```js
// PUT http://localhost:1337/schemas/:className
{
  "classLevelPermissions":
  {
    "get"/"find"/"count"/"update"/"delete"/"addField": { 
      "*": true, // Public access (set by default) 
      [objectId]: true, // by id of `_User`
      "role:admin": true, // by role (`role:${role_name}`)
      "requiresAuthentication": true, // only authenticated users
      "pointerFields": ["field_name", ...] // fields of type Pointer<_User> or Pointer<_User>[]
    },
    "readUserFields":["field_name",...], // same as 'pointerFields' for get+find+count
    "writeUserFields":["field_name",...] // same as 'pointerFields' for update+delete+addField
    ...
  }
}
```
Pointer permissions for:
- `create` has no effect
- `addField` accounted only on updating object, ignored when creating

### When set for an operation:
```js
{
  "classLevelPermissions":{
    [operation]: {
      pointerFields: [‘field’]
      // default * Public removed
      // no other rules set
    }
  }
}
```

|Operation | user not pointed by field | user is pointed by field |
| - | - | - | 
|get |	101: Object not found	| ok |
|find	| Limited results |	ok |
|count |	Limited count |	ok |
|create |	Permission denied	| Permission denied |
|update |	101: Object not found |	ok |
|delete	| 101: Object not found	| ok |
|addField|	Permission denied | ok |

### CODE REVIEW

**Comment by davimacedo** [comment]
> Pointer permissions for:
> 
> * `create` has no effect
> * `addField` accounted only on updating object, ignored when creating

Could you explain why? It is related to [this](https://github.com/parse-community/parse-server/issues/6359) recent issue.

**Comment by BufferUnderflower** [comment]
> Could you explain why? It is related to [this](https://github.com/parse-community/parse-server/issues/6359) recent issue.

I've replied in that issue,  in brief: 

> `create` has no effect

There is no object on server before it is created. And obviously no field of that object with `_User`s to be allowed.

If we allow create by field (pointer permission) examining just the incoming object from POST body - I believe this adds zero security, but more importantly it would then allow anyone to create an object, just by putting himself into a field.

If you want to enforce a rule that some field should contain only the person who creates it - this has nothing to do with class level permissions. Create operation can be allowed using CLP of any other type (role, user pointer, requiresAuthentication) but not using a Pointer Permission (column name).

> addField accounted only on updating object, ignored when creating

As of now (without this PR) there can't be a separate addField pointer permission ( now it is part of writeUserField group in contrary to non-pointer perms that already allow granularity).

My PR adds ability to set pointer permission per operation.

Since addField is not a separate REST operation, but rather a side effect of create/update request
I thought it would be logical to also enforce the same for addField. No object => no column yet (to decide whether a field can be added during the create operation).

But when updating - there is already an object so it's possible to permit/deny based on pointer permission column.

**Comment by sunshineo** [comment]
This is great work! Thank you! Is there a change in the parse-dashboard project needed?

**Comment by difelice** [comment]
> This is great work! Thank you! Is there a change in the parse-dashboard project needed?

Yes, it's needed. I left a comment [here](https://github.com/parse-community/parse-dashboard/issues/1552). Thanks.

**Comment by difelice** [comment]
From [this](https://github.com/parse-community/parse-server/pull/6352#issue-363915731) comment:
```js
[objectId]: true, // by id of `_User`
```

How does that work? Thanks.

**Pull request merged**
