### PR TITLE
PG: Add dates to group aggregate

### PR DESCRIPTION
**Pull request by dplewis**
Closes https://github.com/parse-community/parse-server/issues/4546

Let me know if more tests are needed. 

I didn't really know how to write a test case for createdAt / updatedAt.

Also, I don't think `it_only_db('mongo')` works anymore.

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart I just realized that Postgres doesn't store dates as UTC like mongo. Is that proper functionality?

**Comment by flovilmart** [comment]
ALL dates should be UTC (that’s the expected behavior). If it isn’t, then... that’s quite problematic :/

**Comment by dplewis** [comment]
For instance the objects I just created on postgres look like `2018-02-07 20:58:31.512-06`. That `-06` is Central Time

**Comment by flovilmart** [comment]
ouch yeah all dates should be UTC, but becaut they have the TZ info, not all is lost :)

**Comment by dplewis** [comment]
@flovilmart should we convert them to UTC or leave them be?

**Comment by dplewis** [comment]
@flovilmart The PG date storage aside how does this look?

**Comment by dplewis** [comment]
@flovilmart Thanks. What about the node vulnerability?

**Pull request merged**
