### PR TITLE
feat: Upgrade to Parse JavaScript SDK 4

### LINKED ISSUE #8330: Upgrade to Parse JS SDK 4
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

As Parse JS SDK 4 is in preparation, and it's a breaking change, it should be released with Parse Server 5.

### Feature / Enhancement Description

Upgrade Parse Server dependency to Parse JS SDK 4; this requires a stable release of Parse JS SDK 4.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Parse JS 4 has some breaking changes, this PR adds the necessary changes.

Closes: #8330

### Approach

Refactor unit tests

### TODOs before merging

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
Note that this PR should not be merged until the JS SDK version 4 is fully released

**Comment by mtrezza** [comment]
That was quick! I'll change this to draft until Parse JS SDK 4 is released.

**Review by mtrezza — COMMENTED** [review]
Looks all fine to me; we'll wait until Parse JS SDK 4 release.

**Comment by mtrezza** [comment]
I created https://github.com/parse-community/Parse-SDK-JS/issues/1637 because the tests for the Parse JS SDK muss pass before we can make a stable release.

Procedure:
1. Fix failing tests in https://github.com/parse-community/Parse-SDK-JS/issues/1637
2. Release Parse JS SDK 4
3. Change dependency in this PR to Parse JS SDK 4
4. Merge this PR

**Comment by mtrezza** [comment]
@dblythy Parse JS SDK 4 has been released; could you update this PR to see whether CI passes?

**Comment by mtrezza** [comment]
@dblythy I've upgraded to Parse JS SDK 4 stable version and resolved the conflicts. Assuming that tests pass, is there anything to add to this PR?

Regarding changelog entry; since Parse JS SDK 4 is a major version increment, is Parse JS SDK <4 is still compatible with Parse Server 6 or do we have to add a note to the changelog that versions <4 are incompatible?

**Comment by dblythy** [comment]
Thanks for doing this!!

Parse Server 6 should still be compatible with previous versions of the SDK

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.29](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.29)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Pull request merged**
