### PR TITLE
feat: add node 16 support; remove node 15 support

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Node 15 reached its EOL; Node 16 is the current version

Related issue: #n/a

### Approach
- remove node 15 from ci
- add node 16 to ci
- use node 16 as default

This appears to not be merely a CI change, but to require some minor changes in parse server / dependencies. Hence this PR will likely be a `feat` commit.

### TODOs before merging

- [x] Add entry to changelog
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by funkenstrahlen** [comment]
👍

**Comment by mtrezza** [comment]
Yes, this has become stale because of other CI changes that have been prioritized. If anyone wants to pick this up in the meantime, please feel free.

**Comment by marvinroger** [comment]
This PR can now be closed 😉

**Comment by mtrezza** [comment]
Closing in favor of https://github.com/parse-community/parse-server/pull/7707

**Pull request closed without merging**
