### PR TITLE
Improve validating user performance

### PR DESCRIPTION
**Pull request by dplewis**
`$ne` queries don't properly use indexes and can be exponentially slower as the database grows.

Test can be found https://github.com/parse-community/parse-server/blob/master/spec/ParseAPI.spec.js

### CODE REVIEW

**Comment by acinader** [comment]
How did this come to your attention?  How did you know that it is inefficient and doesn't use the index?  That seems like a pretty remarkable failure on the part of mongo.

On the actual code change, an alternate construct, not saying its better, but just what comes to my mind would be:
```js
.then((users) => {
    if (users.length > 0
       && users.filter(u => u.id !== this.objectId()).length > 0) {	           
           throw new Parse.Error(Parse.Error.EMAIL_TAKEN);
...
```

**Comment by dplewis** [comment]
Its well known optimization problem. https://docs.mongodb.com/manual/core/query-optimization/#read-operations-query-selectivity.

**Comment by acinader** [comment]
did you run `explain` on both queries?  Are we sure that it matters in this particular case?

If email has a unique index on it, which I think it will by default, does this really do anything at all?

**Comment by dplewis** [comment]
This PR uses indexes more effectively. I only have about 2000 users so difference is very small.

**Comment by dplewis** [comment]
I ran `explain` on it and it looks like they both use indexes. But this fix is a smaller query.

I need to study up more on indexes.

 db.getCollection("_User").find({ username: "" }).explain();

```
{
  "queryPlanner" : {
    "plannerVersion" : 1,
    "namespace" : "db._User",
    "indexFilterSet" : false,
    "parsedQuery" : {
      "username" : {
        "$eq" : ""
      }
    },
    "winningPlan" : {
      "stage" : "FETCH",
      "inputStage" : {
        "stage" : "IXSCAN",
        "keyPattern" : {
          "username" : 1
        },
        "indexName" : "username_1",
        "isMultiKey" : false,
        "isUnique" : true,
        "isSparse" : true,
        "isPartial" : false,
        "indexVersion" : 2,
        "direction" : "forward",
        "indexBounds" : {
          "username" : [
            "[\"\", \"\"]"
            ]
        }
      }
    },
    "rejectedPlans" : [ ]
  }
}
```

db.getCollection("_User").find({ username: "", _id: { $ne: "" }  }).explain();

```
{
  "queryPlanner" : {
    "plannerVersion" : 1,
    "namespace" : "db._User",
    "indexFilterSet" : false,
    "parsedQuery" : {
      "$and" : [
        {
          "username" : {
            "$eq" : ""
          }
        },
        {
          "$nor" : [
            {
              "_id" : {
                "$eq" : ""
              }
            }
          ]
        }
      ]
    },
    "winningPlan" : {
      "stage" : "FETCH",
      "filter" : {
        "$nor" : [
          {
            "_id" : {
              "$eq" : ""
            }
          }
        ]
      },
      "inputStage" : {
        "stage" : "IXSCAN",
        "keyPattern" : {
          "username" : 1
        },
        "indexName" : "username_1",
        "isMultiKey" : false,
        "isUnique" : true,
        "isSparse" : true,
        "isPartial" : false,
        "indexVersion" : 2,
        "direction" : "forward",
        "indexBounds" : {
          "username" : [
            "[\"\", \"\"]"
            ]
        }
      }
    },
    "rejectedPlans" : [ ]
  }
}
```

**Comment by acinader** [comment]
According to your query plan, in both cases, the query will start by fetching records using the username key and using the username index.

There can never be more than one result.

Then the $ne filter is applied.

The size of the db shouldn't matter, cause the $ne will only ever be applied to the results of the username fetch.

**Comment by dplewis** [comment]
@acinader That makes sense. Thanks for explaining it to me.

**Pull request closed without merging**
