### PR TITLE
Add support for expiration interval in Push

### PR DESCRIPTION
**Pull request by marvelm**
## Overview
- Support the `expiration_interval` parameter in the Push controller
- [Relevant doc](http://docs.parseplatform.org/rest/guide/#setting-an-expiration-date)
- [Related PR on parse-dashboard](https://github.com/parse-community/parse-dashboard/pull/773)

### CODE REVIEW

**Comment by flovilmart** [comment]
@marvelm thanks for the PR, according to the coverage report it seems that 2 paths that seem critical are not properly covered by the tests [here](https://codecov.io/gh/parse-community/parse-server/compare/b703ec8a79a9866bbe2a2e934a15d2fe442f8df8...2f16f34f95adf0e41d2ac690063e25de4198af40/src/src/Controllers/PushController.js#L27) and [here](https://codecov.io/gh/parse-community/parse-server/compare/b703ec8a79a9866bbe2a2e934a15d2fe442f8df8...2f16f34f95adf0e41d2ac690063e25de4198af40/src/src/Controllers/PushController.js#L49) 

Otherwise the feature look great!

**Comment by marvelm** [comment]
@flovilmart I've fixed the coverage issue.

**Comment by flovilmart** [comment]
100% diff hit, I like it! @montymxb what do you think ?

**Comment by montymxb** [comment]
@flovilmart looks like a nice addition 👍

**Pull request merged**
