### PR TITLE
add tests for JS SDK nearsphere convenience methods

### PR DESCRIPTION
**Pull request by mtrezza**
Adding tests for JS SDK nearsphere convenience methods in https://github.com/parse-community/Parse-SDK-JS/pull/582

### CODE REVIEW

**Comment by mtrezza** [comment]
This will fail until parse-community/Parse-SDK-JS#582 is merged.

**Comment by dplewis** [comment]
Should we close this?

**Comment by flovilmart** [comment]
Looks like it, i’ll let @mtrezza do it .)

**Comment by mtrezza** [comment]
Done

**Pull request closed without merging**
