### PR TITLE
Enable direct access by default

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Picking up the experimental feature for direct access to Parse Server within Cloud Code.

- The goal is fix related issues and enable it by default.
- The feature has been used by some in production systems for some time, seemingly without of any major issues.

Direct access has been merged as feature flagged here:
https://github.com/parse-community/parse-server/pull/2316

Related issue: #6637

### TODOs before merging

- [x] Add test cases
- [ ] Add entry to changelog
- [x] Add deprecation definition
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions), remove experimental reference

### CODE REVIEW

**Comment by dplewis** [comment]
Its been a while since I looked into this. If I remember correctly the reason why the tests are failing is because of [this](https://github.com/parse-community/parse-server/blob/fd0b535159877fa9bc74fb645169f56814c67c60/src/RestWrite.js#L934) the installationId is `cloud` meaning you won't get back a sessionToken. The check is [here](https://github.com/parse-community/parse-server/blob/fd0b535159877fa9bc74fb645169f56814c67c60/src/RestWrite.js#L934).

You should be able to fix the tests by setting an installationId not set to cloud.

**Comment by mtrezza** [comment]
Thanks for the hint! I'll look into this.

**Comment by dplewis** [comment]
@mtrezza I added a PR https://github.com/parse-community/parse-server/pull/6903 I don't know if it would help with the test cases here.

**Comment by MobileVet** [comment]
@dplewis @mtrezza It appears to me that the only place `directAccess` is referenced in the server code is `ParseServer.js:188` when it sets up a custom REST controller.  As a result, I am having a little trouble understanding exactly what this does.

My guess / hope is that instead of firing an HTTP request for a query made in **Cloud Code**, it uses the mongo connection to make the request 'directly.'  Is that what this option does?

For example, I am hoping that if one had a **Cloud Function** with 3 queries contained in a `Promise.all([])`, they would utilize the mongo connection pool (assuming it was larger than 3) and make 3 parallel direct queries versus making 3 queries back to the server endpoint using the REST API.

Is that a correct understanding?
Thanks in advance.

**Comment by mtrezza** [comment]
@MobileVet Your understanding is correct.

**Comment by MobileVet** [comment]
> @MobileVet Your understanding is correct.

Wow... this changes everything, lol!  I have been using Parse for a long time, but have only recently been delving into optimizations and performance issues.  While I understood the REST API was used conceptually, the implications of such knowledge weren't apparent until I was reviewing our Sentry logs the other day.

> I abandoned the PR because I was removing the option to use direct access entirely, but I am not sure anymore direct access should be the only option. It may be detrimental to load distribution within an target group of server instances. So maybe enable it by default but leave it as an option to disable it.

At first blush, I can't imagine how this could be slower in our use case.  We try to group our queries where ever possible and it is annoying to think they are taking up numerous instances to resolve.  Granted, that allows the calling instance to maybe handle some other request while it is asynchronously waiting... but that still feels like more overhead.  I suppose if one of those queries is long it could stall the instance and thereby starve other callers... but... hmm.  Lots to consider.

**Comment by dplewis** [comment]
@mtrezza Can you fix the conflict and update from master? A few improvements have been made for directAccess. I want to see how many test fail now.

**Comment by mtrezza** [comment]
> Is the only known issue the failing tests due to a session token problem?

I can't give an answer for which purposes the feature is currently fit. I can say however that the feature seems to be used by some developers in production already.

**Comment by mtrezza** [comment]
@dplewis Unchanged I’d say. IIRC the issue was the test set-up itself that needs to be adapted for direct access. I’ll give you branch access.

**Comment by MobileVet** [comment]
> I abandoned the PR because I was removing the option to use direct access entirely, but I am not sure anymore direct access should be the only option. It may be detrimental to load distribution within an target group of server instances. So maybe enable it by default but leave it as an option to disable it.

We are definitely going to give this a shot so I hope that the feature isn't removed entirely.  It will be really interesting to see the results in our system.  We currently handle ~75k sessions  a day which isn't huge, but also nothing to sneeze at.Thanks for all of your work with it.

**Comment by dplewis** [comment]
So `directAccess` is for bypassing the HTTP layer when using Parse JS SDK on the same node runtime as the server. Mostly for cloud code but you can use it anywhere as long as it is the same runtime.

DirectAccess: false
Runtime Request -> RestController -> HTTP -> Middleware -> Router -> 

DirectAccess: true
Runtime Request -> DirectAccessRestController -> Router ->

To make the tests pass in this case, we would have to add missing components from the RestController and the Middleware to the DirectAccessRestController. 

As a visual, imagine turning directAccess: true on your server, copy the entire test suite into a cloud code function and run it.

**Comment by dplewis** [comment]
@mtrezza How does this look to you? I also fix a bug.

```
_CoreManager.default.getRESTController(...).handleError is not a function
```

**Comment by dplewis** [comment]
@mtrezza If you are interested in seeing my original solution
 
https://gist.github.com/dplewis/3e911af29a667a88b9f92fa007e735e2

**Comment by mtrezza** [comment]
What do you think about keeping the option but default it to `true`, in case someone prefers to distribute the load through a load balancer?

**Comment by dplewis** [comment]
I like that idea. If you did that originally all the tests would have passed by setting directAccess: false lol

**Comment by mtrezza** [comment]
My intention was to run all test with direct access `true` to make sure everything still works. Now that we keep it optional, do you think it is necessary to run all the tests twice, once with `true` and once with `false`?

**Comment by dplewis** [comment]
I would like to see the tests passing as well. That gist I posted only had 23 tests fail. Those failing test produced results that weren’t expected.

**Comment by dplewis** [comment]
@mtrezza The reason for this PR is to make directAccess turned on by default. I think that has been accomplished.

For the tests, looking at how user management is handled server side. Its stateless where you have to pass in sessionToken and useMasterKey options. If you want to pass the tests with directAccess enabled we would have to add state management for user on the server side to ParseServerRESTController which isn't what we want to do.

**Comment by mtrezza** [comment]
If we make direct access enabled by default, we are also moving the feature out of experimental state. Hence my question regarding the tests. Are we confident enough yet that this feature is fit?

**Comment by dplewis** [comment]
Its a 4 year old feature and I assume it is widely used since its the first recommendation when searching "how to make parse faster". I've kept it on for years and only found one bug myself, I'm confident based on my own experience. The main purpose of turning it on is so new users of parse will have it out of the box without having to search for it.

Let me see if I can find more bugs from those failing tests earlier in production.

**Comment by mtrezza** [comment]
I have also seen deployments where it was used for quite a while, but I was never sure whether it just worked for them, based on the specific application. If the tests pass and given it's availability for years I guess it should be good to move it out of experimental. A quick issue search also didn't reveal anything.

**Review by davimacedo — APPROVED** [review]
It looks good to me. I believe we should just list it as a breaking change in the changelogs.

**Comment by mtrezza** [comment]
Looking at the current file changes, it seems that `directAccess` is disabled for the tests? If that is the case, shouldn't the tests run with `directAccess` enabled if it becomes the default?

**Comment by dplewis** [comment]
It's impossible to run directAccess against tests because directAccess is stateless. We have [ParseServerRESTController.spec.js](https://github.com/parse-community/parse-server/blob/master/spec/ParseServerRESTController.spec.js) specifically for directAccess.

**Comment by mtrezza** [comment]
Got it, thanks, fine with me then.

**Review by dplewis — APPROVED** [review]

**Comment by MobileVet** [comment]
Kudos again to everyone for their work on this.  Personally I would be hesitant to make this the default behavior as one doesn't know what environment people are using Parse in and thus the full impact.  We actually got bit on the [case insensitive index update](https://github.com/parse-community/parse-server/releases/tag/4.0.0) a while back and thus I am sympathetic to significant underlying changes like this.  However, if you do go down that path, marking it as a 'breaking change' and outlining the issue clearly is definitely the way to do it.

**Comment by MobileVet** [comment]
In the interim, we did a little testing on a 'mostly production' setup earlier today and I thought I would share our results.  They focus on a particularly simple API endpoint for us that includes 3 mongo queries in a `Promise.all([])` block.  Everything was at our 'production' level except for the Mongodb instance and the amount of traffic.

**Comment by mtrezza** [comment]
Good point, before merging this we should
- add the Breaking Change change log entry
- remove any reference to directAccess being an experimental feature

**Comment by MobileVet** [comment]
@dplewis @mtrezza Wanted to let you know we tried `DIRECT_ACCESS` in production and it looked to be leaking memory.
### Setup
- Heroku Performance L
- Mongodb M40 db host
- 35 Throng workers (Node clustering)
- 2% Sentry logging
- Mongo 3.6.21
- Parse Server 4.5.0
- PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS = 1

### Results
- Memory climbed until it started swapping heavily and things went sideways
- Prior to that, the duration variance for calls did appear lower than without this feature turned on, but it was hard to tell and number of samples was lower than we would like for our analysis.
- Our typical memory footprint starts at about 4GB, quickly grows to 6 and then levels off around ~7.5GB

DIRECT_ACCESS Memory Leak

**Comment by mtrezza** [comment]
Thanks for the update @MobileVet. Can you verify a memory leak in a more controlled environment, with a load test?

**Comment by MobileVet** [comment]
> Thanks for the update @MobileVet. Can you verify a memory leak in a more controlled environment, with a load test?

Will give it a shot in the next day or so.

**Comment by mtrezza** [comment]
@MobileVet Do you have an update on this?

**Comment by MobileVet** [comment]
> @MobileVet Do you have an update on this?

Apologies @mtrezza I couldn't get to it last week.  We did allocate team resources this week and @rdhelms is looking at it right now.  Should definitely have something by mid week.

**Comment by MobileVet** [comment]
@mtrezza @dplewis We are digging into this and having some trouble getting a solid picture of it.  Do you have a recommended memory analysis setup?  Do you just use Node Profiler?  Any other tips?

Regarding our findings so far, regardless of the presence of `Promise.all` blocks w/ multiple mongo queries... if `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1` and you continually make requests to a particular cloud function on the server, the memory will rise indefinitely.  Once you cease making calls, it will drop back, but not all the way to where it started.  If you wait between calls... the rise is much more managed by the garbage collection.

Alternatively, with `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=0` the memory will increase a bit and stabilize.  Once the calls are completed, it will fall back to the original steady state from which it started.

**Comment by MobileVet** [comment]
@mtrezza @dplewis Ok, there is definitely a memory leak using `DIRECT_ACCESS`.  If you create a default clean install of Parse and make a dead simple Cloud function that queries the `User` table and you hit that call over and over, the heap will grow.

Here is our setup:

- `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS`=1
- Testing using >2000 sequential calls
- Using `@airbnb/node-memwatch`
### memwatch setup:
```
    // index.ts line 127
    app.listen(config.PORT, displayEnvironment)
    memwatch.on('stats', (stats) => {
        console.log(stats['used_heap_size' as 'max'])   // eslint-disable-line no-console
    })
```

### Cloud function
```
Parse.Cloud.define('testFunction', async () => {
    const query = new Parse.Query(Parse.User).limit(1)
    await query.find({ useMasterKey: true })
    return true
}
```

### Calling script
```
const axios = require('axios')
const maxTests = 100000
let testNum = 0
const runTest = () => {
  const headers = {
    'X-Parse-Application-Id': 'memorytestapp',
    'X-Parse-REST-API-Key': 'setec-astronomy',
    'X-Parse-Session-Token': 'r:9I3z3NcYGVeWB0xm0cgjUYCxanm3wIfM',
  }
  console.log('Starting test #' + testNum)
  return axios({
    method: 'POST',
    url: 'http://localhost:5000/parse/functions/testFunction',
    headers,
  }).then(response => {
    console.log('Finished test #' + testNum)
    if (testNum < maxTests) {
      testNum++
      runTest()
    }
  })
}
runTest()
```

### Results
Here are the `heap_size` results in graph form.
`DIRECT_ACCESS=0`
DIRECT_ACCESS=0

`DIRECT_ACCESS=1`
DIRECT_ACCESS=1

**Comment by mtrezza** [comment]
@MobileVet Thanks for investigating and sharing this in such detail.

There have been similar reports shared about decreasing server performance over time that may be related to this:
- https://github.com/parse-community/parse-server/issues/7036
- https://github.com/parse-community/parse-server/issues/6405

I will change this PR back to draft mode until we get insight into this.

**Comment by mtrezza** [comment]
@MobileVet Could you run the test longer, and maybe also measure the response time change over time?

I did some quite extensive similar load testing with app profiling for many different queries. The performance eventually stabilized. The decreasing performance and eventual stabilization could have to do with the NodeJS heap allocation or garbage collection algorithm.

**Comment by rdhelms** [comment]
Hi @mtrezza - per your request, we called our cloud function repeatedly for an hour (we waited until each response was received before firing the next request, so the server was only ever handling one request at a time). We measured both the `used_heap_size` in the server and the response time from the client's perspective.

Here's the function:
image

Here's an hour's worth of `used_heap_size` measurements, in bytes
image

And here's a sample of the response times during the hour, in milliseconds:
image

As you can tell, the response times stayed relatively constant, which I would expect since we were only making one request at a time, and we were nowhere near reaching our physical memory limit.

Interestingly, the memory usage did eventually flatten out...I'm not totally sure what to make of that. However, even with the flattening out, we still had about 40 minutes of increasing memory, going from ~75 MB up to almost 500 MB. Even if it did eventually "stabilize,"  the increase is still way too huge for us to currently turn `directAccess` on.

**Comment by dplewis** [comment]
@rdhelms @MobileVet Can you try this branch and see if there are any improvements?
https://github.com/parse-community/parse-server/tree/improve-schema-cache

**Comment by rdhelms** [comment]
@dplewis Wow, so this only after running for a few minutes, but all I did was update our package.json dependency:
```
"parse-server": "parse-community/parse-server#improve-schema-cache",
```

And these are the initial results (with `directAccess` still on):
image

So...looking way better at the moment. I'll do a comparison with `directAccess` turned back off again, and then I'll run a longer test using the new branch with `directAccess` on again.

**Comment by mtrezza** [comment]
@dplewis Good hint. That is the branch where we introduce the DB watch hooks instead of pulling the schema per request?

**Comment by rdhelms** [comment]
These charts all represent `used_heap_size` measurements during 2000 sequential calls to the cloud function mentioned [above](https://github.com/parse-community/parse-server/pull/6636#issuecomment-778358936)

#### `master` branch with direct access OFF
image

#### `master` branch with direct access ON
image

#### `improve-schema-cache` branch with direct access OFF
image

#### `improve-schema-cache` branch with direct access ON
image

**Comment by dplewis** [comment]
@rdhelms Thanks for running a performance test on it. This information is really helpful. Feel free to keep using that branch, it should improve your queries and saves speeds also. If you want to follow the conversation regarding that branch check [here](https://github.com/parse-community/parse-server/pull/6743)

@mtrezza I'll try to get that branch released shortly. Your improvements on the flaky tests should help.

**Comment by rdhelms** [comment]
I went ahead and did a longer (~45 mins) test of locally hitting one of our actual cloud code functions that we use in production. This is with the new `improve-schema-cache` branch, and with directAccess ON:
image

Definitely seems way better than before!

**Comment by mtrezza** [comment]
@rdhelms Thanks also from my side for these tests. I hope this finally solves the mystery of the decreasing server performance reports.

@dplewis Let me know when if you need a hand with getting the branch ready for merge.

**Comment by MobileVet** [comment]
> @rdhelms Thanks also from my side for these tests. I hope this finally solves the mystery of the decreasing server performance reports. Just for future readers, regarding the [flattening out](https://github.com/parse-community/parse-server/pull/6636#issuecomment-778358936) of the heap curve, this looks much like the V8 heap size reached its limit, which is ~500MB by default, depending on the Node version and the memory allocated to the process.
> 
> @dplewis Let me know if you need a hand with getting the branch ready for merge.

@dplewis @mtrezza We would be happy to do whatever we could to help push this over the line as well.  Using the Mongo connection pool efficiently instead of making REST calls to ourself cuts our system level request per second in half AND greatly decreases the variance in our response time.  Definitely looking forward to using `DIRECT_ACCESS`.

**Comment by dplewis** [comment]
@mtrezza Now that https://github.com/parse-community/parse-server/pull/7214 has been merged. What is the status of this?

**Comment by mtrezza** [comment]
This PR can be closed now. @MobileVet do you think you could repeat your test with https://github.com/parse-community/parse-server/pull/7214? It should have fixed the issue.

**Comment by mtrezza** [comment]
@dplewis I intended to do a rebase on current master, but since there have been some changes in #7214 I don't want to mess anything up. You wrote #7214 and made recents commits in this PR, would you mind doing the rebase just to be sure?

**Comment by mtrezza** [comment]
To gradually shift to [phased deprecation](https://github.com/parse-community/parse-server/issues/7198) as part of the larger shift to [release cycles](https://github.com/parse-community/parse-server/issues/7271), we could start here by keeping `directAccess: false` by default and add a deprecation warning, that this will be enabled by default in a future version. The next major release will then set this to `true` by default.

**Comment by davimacedo** [comment]
It is an experimental feature for a while now but I am not sure that changing it to true by default would be a breaking change, since I understand that all tests are passing, right?

**Comment by mtrezza** [comment]
I suspect it is potentially breaking in certain architectures because it does not route requests via http but internally.

For example, if a cloud function makes `Parse.Query` calls, with `directAccess: false` the queries may be routed via a load balancer and distributed across a group of server instances. But with `directAccess: true` all queries are executed on the same server instance. This can cause significant issues due to uneven load distribution and influence performance metrics.

There is a use case for `directAccess: false`, so I would also recommend against removing the option in the future. I think the default however should be `directAccess: true`.

**Comment by dplewis** [comment]
@mtrezza can you update the changelog with a your breaking change suggestions?

Most users will have one instance of the server. If their is a load balancer it’s it distributed before the calls hit the server so directAccess: true wouldn’t matter no?

**Comment by mtrezza** [comment]
> If their is a load balancer it’s is distributed before the calls hit the server so directAccess: true wouldn’t matter no?

Not sure I fully understand the question, but whether or not Cloud Code calls are distributed via the load balancer depends on the `localServerUrl` I think, because currently (without this PR) the calls use the `localServerUrl` to invoke the calls. If a developer explicitly wants to distribute these call currently, they may have set a URL as `localServerUrl` for routing the calls to the load balancer for distribution. If they now set `directAccess: true`, this process is short-circuited and distribution won't happen anymore. A wordy explanation, let me know if I should clarify.

**Comment by dplewis** [comment]
Thank you for the explaination. I was confusion myself.

**Comment by mtrezza** [comment]
> @mtrezza can you update the changelog with a your breaking change suggestions?

@dplewis How do you feel about trying out a phased deprecation for this one? That would mean keeping `directAccess: false` as default and adding a deprecation warning that we'll change the default in a future version. I would add the implications I described above to the Parse Server options doc for the `directAccess` parameter. Then, in the future version, we actually add the breaking change to the CHANGELOG, and if we also follow semver, that version would be a major version increment.

**Comment by dplewis** [comment]
Go for it. Hopefully this will bring awareness to this feature and we can get more feedback.

**Comment by mtrezza** [comment]
Is that somewhat understandable?

image

**Comment by dplewis** [comment]
That is perfect!

**Comment by mtrezza** [comment]
Note, I'm working on adding the deprecation warning here, so this is still in DRAFT.

**Comment by mtrezza** [comment]
Once https://github.com/parse-community/parse-server/issues/7302 is merged, the following deprecation definition needs to be added:

```
{ optionKey: 'directAccess', changeNewDefault: 'true' }
```

Then this should be ready for merge.

**Comment by mtrezza** [comment]
After adding the deprecation definition, Parse Server logs the following warning if `directAccess` is not explicitly set:

> DeprecationWarning: The Parse Server option 'directAccess' default will change to 'true' in a future version.

This is the first attempt of apply the [deprecation policy](https://github.com/parse-community/parse-server/pull/7199) by using the [deprecation mechanism](https://github.com/parse-community/parse-server/issues/7302) to notify developers that `directAccess` will be enabled by default in a future version. Looking ahead, that breaking change would be introduced in `6.0.0` (2022) after displaying the deprecation warning throughout `5.#.#` (rest of 2021).

**Comment by mtrezza** [comment]
@davimacedo could you take a look at this failing test?

It fails at line:
https://github.com/parse-community/parse-server/blob/95637933038948c77ec0aa92be0b6a32e5bc9040/spec/ParseServer.spec.js#L110

with

```
1) Server Url Checks does not have unhandled promise rejection in the case of load error
3762
  - Expected 'warn: DeprecationWarning: The Parse Server option 'directAccess' default will change to 'true' in a future version.
3763
  ' to be undefined.
```

The commit says:
>  Add test to check inexistence of unhandled promise rejection on server fail

I think it intended to fix https://github.com/parse-community/parse-server/pull/5573#issuecomment-491068469.

Do you think we can change the line above to be more specific?
```
expect(stdout).not.toContain('UnhandledPromiseRejectionWarning');
```

**Comment by davimacedo** [comment]
@mtrezza there is a long time it was merged and it is hard to remember but I agree with your change. It looks good to me.

**Comment by mtrezza** [comment]
Thanks, and all seem to pass now, this is ready for review.

**Comment by mtrezza** [comment]
@dplewis, it seems we are closely hitting the 15 mins CI timeout. You've just set it to 15 from 30, should I set it to 20 or is there another remedy you have in mind?

**Comment by mtrezza** [comment]
If no further objections, I will merge this later today, since this has already gone through multiple reviews and is stopping [other PRs](https://github.com/parse-community/parse-server/pull/7319) from getting merged.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
