### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by steven-supersolid**
Updates to fix security warnings. Have not performed any integration testing yet

### CODE REVIEW

**Comment by flovilmart** [comment]
@steven-supersolid weird, travis don't want to build this one :/

**Comment by steven-supersolid** [comment]
I wonder if the update for parse-server-simple-mailgun-adapter is breaking it?

NPM lists the repo as https://github.com/ParsePlatform/parse-server-simple-mailgun-adapter
This redirects to https://github.com/parse-community/parse-server-simple-mailgun-adapter
but I can't see any commits for 1.0.1 there, package still says 1.0.0. That said, I managed to update locally and run the tests (I don't get 100% pass rate locally but can try on a faster machine, adjust the timeout)

**Comment by flovilmart** [comment]
@steven-supersolid travis marked the requests 'Abuse' not sure why. and you're right I forgot to push the simple-mailgun-adapter code :/

**Comment by steven-supersolid** [comment]
Is the abuse this? https://github.com/travis-ci/travis-ci/issues/8141

**Pull request merged**
