### PR TITLE
fix: Rate limiting can fail when using Parse Server option `rateLimit.redisUrl` with clusters

### LINKED ISSUE #8631: Rate Limit with `redisURL` can fail if socket is already opened
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When using a RedisURL in rateLimit, the error "socket is already opened" seems to occur when used when clustered.

### Steps to reproduce

Create a Parse Server with clusters and a rate limit

### Environment

Server
- Parse Server version: `alpha`

Database
- System (MongoDB or Postgres): `mongo`

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Rate Limit with redisURL can fail if client is already opened.

Closes: #8631

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Comment by dblythy** [comment]
Testing in production to confirm this PR fixes the issue

**Comment by mtrezza** [comment]
What's the verdict after testing this out in production?

**Review by mtrezza — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Pull request merged**
