### PR TITLE
Keycloak auth adapter

### PR DESCRIPTION
**Pull request by rhuanbarreto**
Implemented a keycloak authentication adapter. I'm using it already for more than 6 months normally as a custom module. Keycloak runs connecting to 2 LDAP servers and provide a centralized ID management system with roles and groups mapping to LDAP groups.

### CODE REVIEW

**Comment by rhuanbarreto** [comment]
I also left a PR in the docs repository for the documentation.

**Comment by rhuanbarreto** [comment]
@dplewis @flovilmart @davimacedo Can you merge?

**Comment by dplewis** [comment]
@rhuanbarreto Sorry for the late reply. Can you add test cases? Everything looks good just want to make sure we have coverage.

**Comment by rhuanbarreto** [comment]
The test cases are bound to have a keycloak running. Should I add something like this in the test suite?

**Comment by davimacedo** [comment]
You can try to mock it. Or maybe use a "test endpoint". I am not sure they have one. You can refer to these tests: https://github.com/parse-community/parse-server/blob/master/spec/AuthenticationAdapters.spec.js

**Comment by rhuanbarreto** [comment]
I made the change to increase coverage and on Travis the errors are not related to my code changes.

Can you please check @davimacedo @dplewis ?

**Comment by davimacedo** [comment]
Could you please add more tests? Something like [these ones](https://github.com/parse-community/parse-server/blob/0aceeca25a663236a2741f8103cfc4ad9af5865a/spec/AuthenticationAdapters.spec.js#L594).

**Comment by rhuanbarreto** [comment]
Sorry. I don't have time anymore for adding these tests. If it's not enough, you can close the PR.

**Comment by dplewis** [comment]
@rhuanbarreto I added a few tests cases. Can you review this?

**Comment by rhuanbarreto** [comment]
Tests are fine! You can merge.

**Comment by rhuanbarreto** [comment]
@davimacedo @dplewis are you able to merge?

**Pull request merged**
