### PR TITLE
GraphQL: Handle required fields from Parse Schema

### PR DESCRIPTION
**Pull request by Moumouls**
A little improvement for better front DX

### CODE REVIEW

**Comment by Moumouls** [comment]
Seems we have a `Postgres` extension fail

**Comment by Moumouls** [comment]
Build Fail for 1 test suite: https://travis-ci.org/parse-community/parse-server/builds/622692292?utm_medium=notification&utm_source=github_status

**Comment by dplewis** [comment]
@Moumouls I'll fix it in another PR. You should be good for now.

**Comment by Moumouls** [comment]
I'll push again on this branch, i missed to add required field on output fields...

**Comment by davimacedo** [comment]
Maybe it would be better to send a new pr with the output.

**Pull request merged**
