### PR TITLE
feat: Switch from Yoga v2 to Apollo V4 merge

### LINKED ISSUE #8728: Switch from Yoga v2 to Apollo V4
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Yoga V4 is currently not suitable for prod. I encountered issues on upload feature, and types issues in a monorepo.

### Feature / Enhancement Description

Use the last version of Apollo Server. It could also help in the futur to get some extra features for developers using apollo client.

### Example Use Case

More details on the linked PR

### Alternatives / Workarounds

None

### 3rd Party References

https://www.apollographql.com/

### PR DESCRIPTION
**Pull request by onurhanife**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8728 

## Approach
#8727 cloned, merged into alpha and conflicts resolved

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
Could you again resolve the conflicts please?

**Review by mtrezza — CHANGES_REQUESTED** [review]
This PR contains unrelated code style changes, please revert these. Are they applied automatically by your IDE, or is that our pre-commit hook?

**Comment by onurhanife** [comment]
@mtrezza Did you also solved the issue or was there a mistake? Seems like you refers to different PR

**Comment by mtrezza** [comment]
Apologies, I mixed up the browser tabs. This PR is still open.

**Comment by onurhanife** [comment]
@mtrezza Hi, the code style changes are coming from parse-server's pre-commit hook.

**Comment by mtrezza** [comment]
Could you just disable the hook in your local repo please, to make this easier.

**Comment by onurhanife** [comment]
Closing via #8959

**Pull request closed without merging**
