### PR TITLE
Fix date in LiveQuery event trigger

### LINKED ISSUE #7082: afterLiveQueryEvent hook returns empty date object
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Date object is empty in afterLiveQueryEvent hook.

### Steps to reproduce
Created hook
```JavaScript
Parse.Cloud.afterLiveQueryEvent('Spendings', async function(request) {
  const category = await getCategory(request.object.get('category'));
  const store = await getStore(request.object.get('store'));

  console.log('===> request.object', JSON.stringify(request.object));

  request.object.set('category', category);
  request.object.set('store', store);
});
```

### Actual Outcome
log that I received. date is empty
===> request.object {"date":{},"amount":444,"createdAt":"2020-12-18T13:21:49.770Z","category":{"__type":"Pointer","className":"Categories","objectId":"SREwh7FEwF"},"parent":{"__type":"Pointer","className":"ParentCategory","objectId":"yomXRG8Hcj"},"updatedAt":"2020-12-18T13:21:49.770Z","objectId":"3MdGVC5NuY"}

### Expected Outcome
expected date object

### Failing Test Case / Pull Request

- [ ] 🧐 I submitted a PR with a failing test case.
- [ ] 🤩 I submitted a PR with a fix and a test case.

###  Environment

Server
- Parse Server version: 4.5.0
- Operating system: OSX 11.0.1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local
- NodeJs: v14.0.0

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 4.2.11
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): MongoDB Atlas

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): Flutter SDK
- SDK version: 2.0.1

### Logs

```
info: beforeSave triggered for Spendings for user undefined:
  Input: {"amount":444,"date":{"__type":"Date","iso":"2020-12-18T13:21:40.088Z"},"category":{"__type":"Pointer","className":"Categories","objectId":"SREwh7FEwF"},"parent":{"__type":"Pointer","className":"ParentCategory","objectId":"yomXRG8Hcj"}}
  Result: {"object":{"date":{"__type":"Date","iso":"2020-12-18T13:21:40.088Z"},"amount":444,"category":{"__type":"Pointer","className":"Categories","objectId":"SREwh7FEwF"},"parent":{"__type":"Pointer","className":"ParentCategory","objectId":"yomXRG8Hcj"}}} {"className":"Spendings","triggerType":"beforeSave"}
info: afterSave triggered for Spendings for user undefined:
  Input: {"date":{"__type":"Date","iso":"2020-12-18T13:21:40.088Z"},"amount":444,"createdAt":"2020-12-18T13:21:49.770Z","category":{"__type":"Pointer","className":"Categories","objectId":"SREwh7FEwF"},"parent":{"__type":"Pointer","className":"ParentCategory","objectId":"yomXRG8Hcj"},"updatedAt":"2020-12-18T13:21:49.770Z","objectId":"3MdGVC5NuY"} {"className":"Spendings","triggerType":"afterSave"}
===> request.object {"date":{},"amount":444,"createdAt":"2020-12-18T13:21:49.770Z","category":{"__type":"Pointer","className":"Categories","objectId":"SREwh7FEwF"},"parent":{"__type":"Pointer","className":"ParentCategory","objectId":"yomXRG8Hcj"},"updatedAt":"2020-12-18T13:21:49.770Z","objectId":"3MdGVC5NuY"}
```

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Property of type `Date` is `undefined` in LiveQuery afterEvent trigger.

Related issue: closes #7082

### Approach
Unknown, only added failing test case.

### TODOs before merging

- [ ] Add test cases
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by dblythy** [comment]
I'm not sure with the current Parse JS SDK can use `fromJSON` to save data:

```
it('from json save data', async (done) => {
    const json = {
      className : 'TestObject',
      date: new Date(),
      array: [],
      object: {},
      string: ''
    }
    const obj = Parse.Object.fromJSON(json);
    expect(obj.get('date')).toBeDefined()
    expect(obj.get('date')).toBeInstanceOf(Date);
    expect(obj.get('array')).toBeDefined()
    expect(obj.get('array')).toBeInstanceOf(Array);
    expect(obj.get('object')).toBeDefined()
    expect(obj.get('object')).toBeInstanceOf(Object);
    expect(obj.get('string')).toBeDefined()
    expect(obj.get('string')).toBeInstanceOf(String);
    await obj.save();
    await obj.fetch();
    expect(obj.get('date')).toBeDefined()
    expect(obj.get('date')).toBeInstanceOf(Date);
    expect(obj.get('array')).toBeDefined()
    expect(obj.get('array')).toBeInstanceOf(Array);
    expect(obj.get('object')).toBeDefined()
    expect(obj.get('object')).toBeInstanceOf(Object);
    expect(obj.get('string')).toBeDefined()
    expect(obj.get('string')).toBeInstanceOf(String);
    done();
  });
```

[Related to this PR](https://github.com/parse-community/Parse-SDK-JS/pull/1295)

**Comment by dblythy** [comment]
Should be fixed by using the JS SDK master and:

```
const object = Parse.Object.fromJSON(json, false, true);
```

**Comment by dplewis** [comment]
@dblythy I'll do a JS SDK release this weekend.

**Comment by dplewis** [comment]
Can you rebase from master? The JS SDK has been updated.

**Comment by dplewis** [comment]
@mtrezza The SDK has been merged. Can you update from master?

**Comment by mtrezza** [comment]
Still fails, because of [issue 1](https://github.com/parse-community/parse-server/issues/7082#issuecomment-776810187).

**Comment by dblythy** [comment]
If you rewrite your test using the third parameter of `fromJSON` (dirty - whether keys should be saved), the test will pass:

```
it('afterEvent should work with date', async done => {
    await reconfigureServer({
      liveQuery: {
        classNames: ['TestObject'],
      },
      startLiveQueryServer: true,
    });
    Parse.Cloud.afterLiveQueryEvent('TestObject', request => {
      const date = request.object.get('date');
      expect(date).toBeDefined();
      expect(date).toBeInstanceOf(Date);
      done();
    });
  
    const query = new Parse.Query(TestObject);
    await query.subscribe();
  
    let object = new TestObject();
    object.set('date', new Date());
    const json = object.toJSON();
    json.className = 'TestObject';
    json.__type = 'Object';
    object = Parse.Object.fromJSON(json, false, true); // this is the key line
    await object.save();
  });
```

**Comment by mtrezza** [comment]
I wasn't even aware that parameter exists, which surfaces yet another issue: TypeScript, still says:
`fromJSON(json: any, override?: boolean): T;` 

The test passes only with:
```
json.className = 'TestObject';
json.__type = 'Object';
```
but that is not something we should have in a test, because it is actually a workaround for [another issue](https://github.com/parse-community/parse-server/issues/7082#issuecomment-776810187).

To make the test pass, the JSON could be created manually:
```
const json = 
  {
    date: {
      __type: "Date",
      iso: "2021-02-25T12:45:08.875Z",
    },
    className: "TestObject",
    __type: "Object",
  };
```
but that is also not something we should keep in a test, because it shortcuts a part of the test.

My suggestion is to fix the [other issue](https://github.com/parse-community/parse-server/issues/7082#issuecomment-776810187) first, to make this test pass in its entirety.

What do you suggest?

**Comment by dblythy** [comment]
It is a new parameter recently released with V3 of the JS SDK, so that fromJSON can save data. Without it, no keys are set to `dirty`, so no data will be saved. This is as `fromJSON` was previously not to be used with saving data.

I _think_ this one will be fixed, but i'm not sure how to test. The issue happened when the decoder was passed a raw date instead of an Object with __type date. The object decoder had no provision to return the date, so instead it returned an empty object. This was happening at the `fromJSON` before the `afterLiveQueryEvent` trigger.

[See more here](https://github.com/parse-community/Parse-SDK-JS/pull/1293)

**Comment by mtrezza** [comment]
> ## ⚠️ Important change for merging PRs from Parse Server 5.0 onwards!
  >
  > We are planning to release the first beta version of Parse Server 5.0 in October 2021.
  >
  > If a PR contains a breaking change and is not merged before the _beta_ release of Parse Server 5.0, it cannot be merged until the end of 2022. Instead it has to follow the [Deprecation Policy](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#deprecation-policy) and phase-in breaking changes to be merged during the course of 2022.
  >
  > One of the most voiced community feedbacks was the demand for predictability in breaking changes to make it easy to upgrade Parse Server. We have made a first step towards this by introducing the Deprecation Policy in February 2021 that assists to phase-in breaking changes, giving developers time to adapt. We will follow-up with the introduction of [Release Automation](https://github.com/parse-community/parse-server/issues/7271) and a branch model that will allow breaking changes only with a new major release, scheduled for the beginning of each calendar year.
  >
  > We understand that some PRs are a long time in the making and we very much appreciate your contribution. We want to make it easy for PRs that contain a breaking change and were created _before_ the introduction of the Deprecation Policy. These PRs can be merged with a breaking change without being phased-in before the beta release of Parse Server 5.0. We are making this exception because we appreciate that this is a time of transition that requires additional effort from contributors to adapt. We encourage everyone to prepare their PRs until the end of September and account for review time and possible adaptions.
  > 
  > If a PR contains a breaking change and should be merged before the beta release, please mention @parse-community/server-maintenance and we will coordinate with you to merge the PR.
  >
  > *Thanks for your contribution and support during this transition to Parse Server release automation!*

**Comment by dblythy** [comment]
Closed via https://github.com/parse-community/Parse-SDK-JS/pull/1293

**Pull request closed without merging**
