### PR TITLE
docs: Generate API documentation for release branch

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Master branch has been removed in favor of a release branch. Currently there is no permanent link to the documentation for the latest api. There are release version specific links but those can get stale as new releases are publish.

## Approach

Adds support for links that match the latest release. Fixes broken image link in documentation.

Before: 
https://parseplatform.org/parse-server/api/master/ParseServerOptions.html

After:
https://parseplatform.org/parse-server/api/release/ParseServerOptions.html

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [x] Add new Parse Error codes to Parse JS SDK

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]

**Comment by mtrezza** [comment]
We do not seem to have a docs dry-run? That would help to review change like this.

**Comment by dplewis** [comment]
You can just copy `release_docs.sh` and run the following to see the output. This change is nearly identical to the JS SDK

```bash
$ GITHUB_ACTIONS=true SOURCE_TAG=test ./release_docs.sh
```

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Pull request merged**
