### PR TITLE
ci: add retries for flaky Postgres tests

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Postgres can be flaky - adds 3 retries to postgres tests

Related issue: n/a

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! Is this ready for merge?

**Comment by dblythy** [comment]
Yep!

**Comment by mtrezza** [comment]
This is effectively covering the flakiness of the Postgres tests - practical but this will also make it unlikely that someone will fix the actual flakiness. So I'm actually not sure whether this is beneficial?

**Comment by dblythy** [comment]
Good point actually, if a test is added that is flaky, we will never know with this method

https://github.com/parse-community/parse-server/issues/7180

**Pull request closed without merging**
