### PR TITLE
Get ParseConfig parameters with Master Key

### PR DESCRIPTION
**Pull request by mtrezza**
Adds a property to Parse Config parameter to make it only retrievable with master key.

### CODE REVIEW

**Comment by mtrezza** [comment]
This feature requires https://github.com/parse-community/parse-dashboard/pull/1233.

**Comment by dplewis** [comment]
This feature already exists

https://github.com/parse-community/parse-server/blob/master/src/Routers/GlobalConfigRouter.js#L45

**Comment by mtrezza** [comment]
The feature you are referring to restricts PUTs to the master key. The new feature allows for individual config parameters to be GETtable only with master key.

**Comment by mtrezza** [comment]
@dplewis Any idea why the test is passing for mongodb but fails for postgres?

**Comment by dplewis** [comment]
I have an idea why, let me pull this down and see.

**Comment by dplewis** [comment]
You have to add the masterKeyOnly field to the [SchemaController](https://github.com/parse-community/parse-server/blob/0fa315fc5bf2a481b542db59b3dc3c6e46fa56c2/src/Controllers/SchemaController.js#L131)

**Comment by mtrezza** [comment]
@dplewis Thanks, what are the implications when I add that field to the schema controller?  That field is not always present, for example when upgrading from an existing parse server installation.

**Comment by dplewis** [comment]
Its automatically gets updated when the server starts. [schemaUpgrade](https://github.com/parse-community/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L1045)

**Pull request merged**
