### PR TITLE
fix: Nested date is incorrectly decoded as empty object `{}` when fetching a Parse Object

### LINKED ISSUE #8445: Nested Objects can't retrieve dates
### New Issue Checklist
- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).

### Issue Description
Can save nested objects, can't retrieve dates.

### Steps to reproduce
const test = new Parse.Object("Test");
test.set("objectTypeColumnName", { date: new Date(), otherValue: true });
await test.save();

const testRes = new Parse.Query("Test").first();
console.log(testRes.get("objectTypeColumnName"));

Expected 
{
    date: 2023-02-25T04:44:46.848Z,
    otherValue: true
}

Actual 
{
   date: {},
   otherValue: true
}

- Parse Server version: `6.0.0`
- Operating system: `MacOS 13.2.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.1`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `4.0.1`

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Parse Server can write dates to Mongo, but can't fetch them

Closes: #8445

## Approach

Correctly decode dates

## Tasks

- [x] Add tests

### CODE REVIEW

**Review by mtrezza — COMMENTED** [review]
@magnacartatron could you try out this branch and confirm that the issue is fixed?

**Comment by magnacartatron** [comment]
Hi there, yup works a treat please merge this change in.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Pull request merged**
