### PR TITLE
chore(ci): Remove prettier quoted argument to fix issue on Windows

### PR DESCRIPTION
**Pull request by sadortun**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Windows doesn't like single quotes around prettier arguments.

```
> prettier --write '{src,spec}/{**/*,*}.js'
[error] No files matching the pattern were found: "'{src,spec}/{**/*,*}.js'".
```

Related issue: https://github.com/parse-community/parse-server/pull/7419#issuecomment-855927094

### CODE REVIEW

**Comment by mtrezza** [comment]
Do we need any quotes at all? In your comment you wrote that removing the quotes fixed the issue for windows. If it also works for Unix we can just remove then.

**Comment by sadortun** [comment]
@mtrezza Ahah, yes, reading back my old comments 😆 

✅ Fixed

**Comment by dblythy** [comment]
This likely applies to the example repo too

**Comment by mtrezza** [comment]
Well spotted, could someone open a PR there?

**Comment by mtrezza** [comment]
I have tested `npm run prettier` without brackets on unix and it works fine.

**Review by mtrezza — APPROVED** [review]
I have tested `npm run prettier` without brackets on unix and it works fine.

Thanks for the fix!

**Comment by mtrezza** [comment]
I think we need a changelog entry nonetheless?

**Comment by mtrezza** [comment]
I just notice that it says "This branch is out-of-date with the base branch". Can you rebase?

**Comment by sadortun** [comment]
@mtrezza Updated

**Comment by mtrezza** [comment]
Merged - thanks for this PR!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
