### PR TITLE
feat: support `postgresql` protocol in database URI

### LINKED ISSUE #7687: Database connection string with postgresql protocol assumes MongoDB
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Developers using PostgreSQL can only use a URI with the prefix "postgres:" when "postgresql:" is also commonly used.

### Steps to reproduce

1) Set env var PARSE_SERVER_DATABASE_URI to a URI string starting with "postgresql://..."
2) There will be a "MongoParseError" as it fallsback to MongoDB.

### Actual Outcome

"MongoParseError: Invalid connection string"

### Expected Outcome

Should validate as a PostgreSQL URI.

### Environment

Node v17.0.1

Server
- Parse Server version: 5.0.0-beta.1
- Operating system: macOS 12.0.1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): Postgres
- Database version: Postgres 14.0.0
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): n/a
- SDK version: n/a

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Developers using PostgreSQL can only use a URI with the prefix "postgres:" when "postgresql:" is also commonly used. Close #7687.

Related issue: #7687 

### Approach

Add support for `postgresql://`.

### TODOs before merging

- [x] Add tests
- [x] Fixed some of the flakiness in the Postgres testcases that caused connection time outs. This is due tests needed the server reconfigured before they began and previous test not cleaning up it's connection (PostgresInitOptions.spec.js)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by cbaker6** [comment]
@mtrezza this is ready for review

**Review by mtrezza — COMMENTED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)

**Pull request merged**
