### PR TITLE
Back merge 3.4.2 master

### PR DESCRIPTION
**Pull request by acinader**
fixes: #5678

Bring the changelog and version numbers from 3.4.2 into master.

### CODE REVIEW

**Comment by funkenstrahlen** [comment]
@acinader I just tried to update to `3.4.2.` but npm can not find the package. Is this caused by this? 

```
       Installing node modules (package.json)
       npm ERR! code ETARGET
       npm ERR! notarget No matching version found for parse-server@~3.4.2
```

**Comment by acinader** [comment]
@funkenstrahlen travis is till working on it...

https://travis-ci.org/parse-community/parse-server/jobs/545334785

**Comment by funkenstrahlen** [comment]
@acinader Ok thank you! I will just try again later :)

**Comment by acinader** [comment]
and it'll be 3.4.3 cause 3.4.2 just failed and I know why :(.

**Comment by funkenstrahlen** [comment]
Never mind. Thanks for your great work! :)

**Pull request closed without merging**
