### PR TITLE
fixing enableExpressErrorHandler logic

### PR DESCRIPTION
**Pull request by hybeats**
fixing this issue
https://github.com/parse-community/parse-server/issues/6422

### CODE REVIEW

**Comment by dplewis** [comment]
Thanks for contributing. Can you add a test case?

**Comment by dplewis** [comment]
@hybeats Looking over it again this looks good. There are existing tests for this

https://github.com/parse-community/parse-server/pull/4697/files#diff-5fed17ed228f1b7c0c8dd44628cd8191

You add test cases here

**Comment by dplewis** [comment]
@hybeats I fixed the test, @davimacedo Let me know if more tests are needed.

**Comment by johanarnor** [comment]
Hi @davimacedo @dplewis! I stumbled upon this PR since we're currently adopting Sentry error reporting for our backend. To use their [errorHandler](https://docs.sentry.io/platforms/node/guides/express/) middleware we're required to set `enableExpressErrorHandler` to true. However, after this PR was merged this also mean that the default Parse error handler is basically disabled.

I checked the history and found the PR that introduced this feature from the beginning (https://github.com/parse-community/parse-server/pull/4697). The original intention seems to have been quite different. Instead of replacing the default Parse error handler it just used `next` to let the error flow through subsequent middlewares, which would be optimal our use-case with Sentry.

So by merging this fix it also seems to have broken the intended behaviour. A better way might have been to introduce a `overrideParseErrorHandler` config or similar, instead of changing the existing behaviour. I'm not here to complain (I really appreciate the work you do!), first I'm just curious to see if agree with my analysis or if I've missed some vital part.

A workaround is of course to copy the logic from the Parse error handler and use that as a middleware in our own application, but that's not optimal.

**Comment by davimacedo** [comment]
Hi @johanarnor . Thanks for bringing this back up. The idea of having a config option to switch/customize the behavior sounds reasonable to me. Would you mind to create a new issue for discussion?

**Comment by johanarnor** [comment]
> Hi @johanarnor . Thanks for bringing this back up. The idea of having a config option to switch/customize the behavior sounds reasonable to me. Would you mind to create a new issue for discussion?

Yep, it's done. See 👆

**Pull request merged**
