### PR TITLE
feat: Allow `Parse.Session.current` on expired session token instead of throwing error

### LINKED ISSUE #8726: Retrieve Session Expiration details during Login
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

When logging in to Parse backend from react-native, we do not get expiration date or expires after or any equivalent information

### Feature / Enhancement Description

Include Expiration details of the session token when retrieving the said session after login.

### Example Use Case

Consider if the session token is set to 1 hour in the Parse Backend instead of the default 1 year and the user needs to refresh the token before expiration if he needs to continue using the session after said time. When the user logs in from a mobile app (my use case: react-native) and retrieves the current session, along with the current session token, we do not get the expiration details of the said token.

In the client application, if we know the expiration date of the session, we can prompt the user to refresh the token or re-login to get a fresh session token to continue using the app.

### Alternatives / Workarounds

In the current implementation, Parse.Session.current() throws an error with Session Expired message instead of letting us validate with getting the current session and check if it is valid.
Developers can place the logic of re-login into catch statement checking error code 209.

### 3rd Party References

Any OAuth supports token refresh and expires after (in seconds) along with retrieving actual token

### PR DESCRIPTION
**Pull request by dplewis**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

In the current implementation, Parse.Session.current() throws an error with Session Expired message instead of letting us validate with getting the current session and check if it is valid.

Developers can place the logic of re-login into catch statement checking error code 209.

Closes: https://github.com/parse-community/parse-server/issues/8726

## Approach

This PR bypasses the sessionToken check for `/session/me` endpoint. 

- [x] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
A PR can only be linked to an issue in the same repository. Can I move the JS SDK issue to this repository?

**Comment by dplewis** [comment]
Go for it

**Comment by mtrezza** [comment]
> In the current implementation, Parse.Session.current() throws an error with Session Expired message instead of letting us validate with getting the current session and check if it is valid.

Could this PR be a breaking change?

**Comment by dplewis** [comment]
> Could this PR be a breaking change?

It could be, if developers checked for both expiresAt and error this should be good. If they checked for only session token expires error and not the expiresAt date this would be breaking for them since the error is no longer thrown.

**Comment by mtrezza** [comment]
In that case we can either introduce a temporary Parse Server option and deprecate it, or merge this PR in November for release with Parse Server 7, which may be easier.

**Comment by dplewis** [comment]
Waiting for the next release is better.

**Review by mtrezza — APPROVED** [review]
Looks good, waiting for merge in Nov for next major release.

**Comment by mtrezza** [comment]
Suggested breaking change text:

> `Parse.Session.current()` no longer throws an error if the session token is expired, but instead returns the session token with its expiration date to allow checking its validity.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Pull request merged**
