### PR TITLE
feat: add support for Postgres 15

### LINKED ISSUE #8216: Add official support for Postgres 15
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

[Postgres 15](https://www.postgresql.org/about/news/postgresql-15-rc-2-released-2521/) is set to release 10/13/22.

### Feature / Enhancement Description

It should be added to the CI to test compatibility.

### Example Use Case

Developer wants to use Postgres 15 with Parse.

### Alternatives / Workarounds

Use older versions of Postgres.

### 3rd Party References

N/A

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Postgres 15 is set to release on 10/13/22. It's currently not part of the CI. Close #8216

Related issue: #8216 

### Approach

Add the release candidate of Postgres 15 for now to check possible issues with tests. This PR will be marked as a draft until Postgres 15 is released and all issues are addressed.

### TODOs before merging

- [x] Someone with access to the repo settings will need to update the branch requirements
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
I've changed the PR title, as this would add support for Postgres 15, so it will be a `feat` commit.

**Comment by cbaker6** [comment]
@parse-community/server this is ready for review. You will need to change the branch requirements in settings

**Review by mtrezza — APPROVED** [review]
Looks good! Added Postgres 15 check as required to CI.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.29](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.29)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Pull request merged**
