### PR TITLE
Prevent Stalebot from closing PRs

### PR DESCRIPTION
**Pull request by dplewis**
Configure stalebot to only close issues

Also fixes labels

### CODE REVIEW

**Comment by acinader** [comment]
Off the cuff, I feel like if we haven't worked on a pr or an issue for 50+ days, it's ok to close it?  Do we ever come back to an old stale issue or pr and work it?

**Comment by acinader** [comment]
playing devil's advocate, the fact that #5228 got marked stale is not bad cause it forces you to re-evaluate it, right?

**Comment by dplewis** [comment]
That is true but it forced me to dig around to find it.

**Comment by dplewis** [comment]
> Do we ever come back to an old stale issue or pr and work it?

I usually give the authors a chance to fix the issues. After a while I clean them up.

**Comment by acinader** [comment]
your call.

**Pull request merged**
