### PR TITLE
Allow set user mapped from JWT directly on request

### PR DESCRIPTION
**Pull request by sunshineo**
A not ideal workaround for people really need it
https://github.com/parse-community/parse-server/issues/6390#issuecomment-584457088

### CODE REVIEW

**Comment by davimacedo** [comment]
Could you please add some tests cases? @dplewis what do you think about it?

**Comment by sunshineo** [comment]
About tests, I had a look at https://github.com/parse-community/parse-server/blob/master/spec/Middlewares.spec.js . It seems to me that a lot of the existing code branch and logic are not covered. I cannot find a good test example that I can copy paste then modify for the code I just added.

**Comment by davimacedo** [comment]
I think you could inspire the tests in the session token tests of the following file: https://github.com/parse-community/parse-server/blob/fd0b535159877fa9bc74fb645169f56814c67c60/spec/ParseUser.spec.js

**Comment by sunshineo** [comment]
Thank you @davimacedo . I see the tests in that file mimic a request to test. For example with sessionToken in the headers to get proper access. But I'm not sure how should I write this test. If I have the JWT token on the header it won't work because the step of map from JWT to a Parse user is done by the user themselves before they set the user onto the request. It's a middleware before the Parse middleware. I considered if the mapping should be part of Parse but as I said in the original issue, I'm not sure https://github.com/parse-community/parse-server/issues/6390#issuecomment-584457088

> This workaround still requires user to wrap Parse server in express and map the JWT to a Parse server themselves before pass it down to Parse middleware. But is this the final stop? Should Parse take over the JWT decoding and user mapping? I can see that introduce a ton of configurations to support all the different decoding usecases? And I'm not even sure if the user mapping is possible without code. I'd like to hear your thoughts.

**Comment by davimacedo** [comment]
Maybe it can be part of Parse Server. Do you want to suggest how it could be included? Anyways, in the case of the tests, you can create an express app and add the middleware then Parse (just like you are doing in your application) in the beginning of your test case.

**Comment by sunshineo** [comment]
@davimacedo  and @dplewis , I've added a test

**Comment by dplewis** [comment]
@acinader Thoughts?

**Comment by davimacedo** [comment]
I think we are good with this coverage and we can merge.

**Comment by sunshineo** [comment]
Thank you @davimacedo ! Could someone please merge it?

**Pull request merged**
