### PR TITLE
Fix node security link

### LINKED ISSUE #796: Please log into this app again to reconnect your Facebook account
When logging in with Facebook, ParseFacebookUtilsV4 and Parse Server, I receive the message
"Please log into this app again to reconnect your Facebook account", and then the app crashes on the line that gets the facebook results as an NSDictionary, is there anything that could be causing an issue

Parse Server is on the latest version
facebookAppIds and fileKey is set correctly and working

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Node security link is outdated, npm does no longer triage vulnerabilities.
Related issue: closes https://github.com/parse-community/docs/issues/796

### Approach
Link removed.

### TODOs before merge:

- [x] decide on whether to [add a form](https://github.com/parse-community/docs/issues/796#issuecomment-748062541) for vulnerability report --> yes
- [ ] add `report.parseplatform.org` DNS entry, see https://github.com/parse-community/docs/issues/796#issuecomment-764901381

### CODE REVIEW

**Review by Moumouls — APPROVED** [review]
LGTM

**Review by davimacedo — APPROVED** [review]

**Comment by mtrezza** [comment]
Changed to draft due to ongoing discussion about [form](https://github.com/parse-community/docs/issues/796#issuecomment-748062541).

**Comment by mtrezza** [comment]
TODO before merge:
- [ ] Add report.parseplatform.org DNS entry, see https://github.com/parse-community/docs/issues/796#issuecomment-764901381

**Review by TomWFox — APPROVED** [review]
LGTM 👍

@davimacedo could you add the DNS record for this?

**Comment by davimacedo** [comment]
Do you want me to create a DNS record from report.parseplatform.org to https://form.jotform.com/210205133587044, right? I am not sure if that's possible though. A CNAME from report.parseplatform.org to form.jotform.com is possible for sure, but you need also to check with form.jotform.com if you need to setup something in their side. I can also create a permanent redirect from https://report.parseplatform.org to https://form.jotform.com/210205133587044.

**Comment by davimacedo** [comment]
Done. Could you please check it out?

**Comment by mtrezza** [comment]
Works fine! I think we can merge this one?

**Comment by davimacedo** [comment]
Yes. I think we can.

**Comment by mtrezza** [comment]
I think someone should try out the form actually, whether it sends an email, I don't have access to the email account community@...

**Comment by TomWFox** [comment]
Just tested, email received

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
