### PR TITLE
fix: node engine range has no upper limit to exclude incompatible node versions

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Parse Server is currently incompatible with node >=16, but the node engine range in package.json does not reflect this. 

Related issue: https://github.com/parse-community/parse-server/issues/7686
Port of https://github.com/parse-community/parse-server/pull/7692

### Approach
Add upper range <16. 

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.3](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.3)

**Comment by sadortun** [comment]
Hi @mtrezza,

Not sure if its wanted, but there is some miscmatch between PR description

> Parse Server is currently incompatible with node >=17,

and code

`"node": ">=12.20.0 <16"`

Should it be :
```patch
-"node": ">=12.20.0 <16"
+"node": ">=12.20.0 <17"
```

Especially since v16 is LTS and out since last April

image

**Comment by mtrezza** [comment]
That's a typo in the description. Node 16 compatibility has been merged into `alpha` as https://github.com/parse-community/parse-server/pull/7707, but not into `beta`. Hence, Parse Server 5.0 will not officially be Node 16 compatible. Presumably, the 5.1.0 release will be Node 16 compatible.

I'm not sure whether we can port #7707 into beta. It does not seem to be a breaking change, which should make it possible, but it also contains some major version increments in graphql dependencies, which may imply a braking change in the graphql API, which would speak against a port.

We are obviously a bit late on this, but the last couple of months focused on the larger effort of preparing the Parse Server 5 release, so Node.js compatibility is a bit behind. Good news is that we also have Node 17 compatibility already in the works in https://github.com/parse-community/parse-server/issues/7708, so Parse 5.1.0 should support Node 16 and 17.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
