### PR TITLE
Facebook signup error206

### LINKED ISSUE #6511: Error 206 cannot modify user for new Facebook user
Hello

I am getting error 206 after new Facebook user is saved and reason seems to be nil sessionToken. 
I am facing this for Apple sign in also randomly. This is probably getting fixed by https://github.com/parse-community/parse-server/pull/6416. Don't know whether Facebook issue will also be fixed.

I have one old account created on Heroku Parse server which works fine ie i am able to save attributes after login.

I was running server v3.9.0. tried upgrading till 4.0.2 but still failing.

I am updating PFUser object post login locally in iOS client using Swift. Not using cloud code for this. 

Also failing on back4app v3.9.0. Sign in with Apple also failing on back4app but works randomly.

Works on local setup consistently. Local server installed using bootstrap.sh script.

I have seen some issued dated 2016 fixing this error but server code seems to have changed lot so cannot view the same code referred in https://github.com/parse-community/parse-server/pull/952

### Steps to reproduce

on iOS, Try login using a facebook account that is not yet created on Parse.
Running iOS 13.3.1
 
### Expected Results

After successful login, should be able to save other attributes in PFUser.current() object

### Actual Outcome

The login is successful but saving any attributes fails with error 206 "cannot modify user xxxxx"
Fails on back4app also. v3.9.0
Both Apple and Facebook new user registration and update work fine in local environment. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0 to 4.0.2 (Local 3.10.0)
  - Operating System:    heroku-18 (Local MacOS 10.15.3)
  - Hardware:             heroku-18 (Local MacOS 10.15.3)
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Both as mentioned above

- **Database**
  - MongoDB version: Heroku 3.6.12 (Local 4.2.3)
  - Storage engine:  mLab
  - Hardware:        mLab
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): both

### Logs/Trace

`Mar 15 02:51:40 yovl app/web.1 error: Parse error: Cannot modify user kc30Xbk1wA. {"code":206,"stack":"Error: Cannot modify user kc30Xbk1wA.\n    at RestWrite.runDatabaseOperation (/app/node_modules/parse-server/lib/RestWrite.js:1170:11)\n    at /app/node_modules/parse-server/lib/RestWrite.js:127:17\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
`

### PR DESCRIPTION
**Pull request by ashish-naik**
## Issue
https://github.com/parse-community/parse-server/issues/6511

Closes: #6511

## Approach
Added test case for Facebook signup and login. 
Calling from iOS Objective-C SDK, saving new PFUser created from Facebook signup fails with error 206.
Was first reported in PS version 5.x.x and observed in v6.2.1 also.

## Tasks

- [x ] Add tests

### CODE REVIEW

**Comment by mtrezza** [comment]
Could you rebase this PR on the alpha branch? The only commit in this PR should be your test case.

**Comment by ashish-naik** [comment]
> Could you rebase this PR on the alpha branch? The only commit in this PR should be your test case.

isn't this already showing under alpha branch? Do i need to do anything different?

image

**Comment by mtrezza** [comment]
I suggest you take a look at this [blog article](https://blog.parseplatform.org/learn/tutorial/community/nodejs/2021/02/14/How-to-start-contributing-to-Parse-Server.html) that is especially directed towards first time contributors on how to open a PR. Just make sure to use `alpha` branch as base branch, not `master` as described in the blog, that needs to be corrected. There is also a more technical [Contribution Guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md).

**Comment by ashish-naik** [comment]
This was not created properly so Closing and  creating separate PR.

**Pull request closed without merging**
