### PR TITLE
Sign in with Apple Auth Provider

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/parse-server/issues/5632

Should work out of the box for linking users.
```
{
  "apple_signin": {
    "id_token": "jwt token for user", // used for validation
    "access_token": "an authorized access token for the user", // currently does nothing but maybe in the future
  }
}
```

There is an optional `client_id` that you can pass in to Server Auth Configuration for extra validation.
```
{
  auth: {
   apple-signin: {
     client_id: "", // optional, use the Service ID from apple.
  }
}
```

There is a guide and code for setting getting your `id_token` https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

Apple's documentation is incomplete and incorrect in places 
https://developer.apple.com/sign-in-with-apple/get-started/ 

Shoutout to @Techofficer for doing most of the heaving lifting.
https://github.com/Techofficer/node-apple-signin

### CODE REVIEW

**Comment by TomWFox** [comment]
@dplewis Thanks a lot for taking the lead on this, I’ve been spending the past couple hours setting it up in my app so I’m looking forward to testing this out!

**Comment by dplewis** [comment]
@TomWFox I post links above for configuration. Let me know if it works

**Comment by leapingcoyote** [comment]
We are getting this message, any idea what are we missing? Do you have some step by step setup and usage instructions. I feel we are missing a step. @TomWFox did it work for you?

```
{
    "message": "This authentication method is unsupported.",
    "code": 252
}
```

**Comment by dplewis** [comment]
@leapingcoyote This isn’t released yet, are you using the master branch to test?

**Comment by leapingcoyote** [comment]
@dplewis yes we are using the master branch to test

**Comment by dplewis** [comment]
Thanks for reporting. I’ll look into it

**Comment by dplewis** [comment]
@leapingcoyote I published a fix for this https://github.com/parse-community/parse-server/pull/5755

**Comment by tealshift** [comment]
@dplewis Hi, I'd like to ask about this update you added here. Is this update necessary for Apple Sign-In to work for an iOS client and save `authData` to MongoDB, or will we be okay using an older version of Parse Server?

**Comment by dplewis** [comment]
@tealshift You have to update to the latest version. If you don’t want to update. You can copy this and create your own module.

**Pull request merged**
