### PR TITLE
refactor: Upgrade pg-promise from 11.5.5 to 11.7.8

### LINKED ISSUE #9140: pg-promise and node-postgres are out-of-date
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The dependencies pg-promise and node-postges are not up-to-date.

### Feature / Enhancement Description

Update to the latest versions.

### Example Use Case

N/A

### Alternatives / Workarounds

Force updating packages in dedicated projects.

### 3rd Party References

N/A

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

pg-promise and related dependencies are out-of-date.

Closes: #9140 

## Approach

Update pg-promise

## Tasks

- [x] Ensure CI passes

### CODE REVIEW

**Comment by cbaker6** [comment]
@mtrezza this is ready for review

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Pull request merged**
