### PR TITLE
Remove S3 File Adapter

### PR DESCRIPTION
**Pull request by mtrezza**
This removes the S3 Files Adapter from the Parse Server repo.

Instead, the adapter has to be installed separately as dependency `@parse/s3-files-adapter`.
This is to not make Parse Server dependent on the update of an optional adapter.
The same has already been done some time ago with GCS Files Adapter.

Incident for this change:
- The S3 files adapter was reported to have a vulnerability, therefore also Parse Server was reported to have that vulnerability. That is factually incorrect for deployments that do not use the adapter.

### CODE REVIEW

**Comment by dplewis** [comment]
Just want to point out that the docker build is broken

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
Pulling cache layers for index.docker.io/parseplatform/parse-server:latest...
Done!
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'19.03.8', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2020-03-11T01:24:30.000000000+00:00', u'ApiVersion': u'1.40', u'MinAPIVersion': u'1.12', u'GitCommit': u'afacb8b7f0', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.12.17'}}, {u'Version': u'1.2.13', u'Name': u'containerd', u'Details': {u'GitCommit': u'7ad184331fa3e55e52b890ea95e65ba581ae3429'}}, {u'Version': u'1.0.0-rc10', u'Name': u'runc', u'Details': {u'GitCommit': u'dc9208a3303feef5b3839f4323d9beb36df0a9dd'}}, {u'Version': u'0.18.0', u'Name': u'docker-init', u'Details': {u'GitCommit': u'fec3683'}}]
Arch: amd64
BuildTime: 2020-03-11T01:24:30.000000000+00:00
ApiVersion: 1.40
Platform: {u'Name': u'Docker Engine - Community'}
Version: 19.03.8
MinAPIVersion: 1.12
GitCommit: afacb8b7f0
Os: linux
GoVersion: go1.12.17
Starting build of index.docker.io/parseplatform/parse-server:latest...
Step 1/22 : FROM node:lts-alpine as build
---> 645c08831ecc
Step 2/22 : RUN apk update; apk add git;
---> Running in bc002f625f2f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
v3.11.10-8-gf8ac3999ba [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.10-2-gc655f5d2f5 [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 11274 distinct packages available
(1/6) Installing ca-certificates (20191127-r2)
(2/6) Installing nghttp2-libs (1.40.0-r1)
(3/6) Installing libcurl (7.67.0-r3)
(4/6) Installing expat (2.2.9-r1)
(5/6) Installing pcre2 (10.34-r1)
(6/6) Installing git (2.24.4-r0)
Executing busybox-1.31.1-r10.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 23 MiB in 22 packages
Removing intermediate container bc002f625f2f
---> e3d351ac090d
Step 3/22 : WORKDIR /tmp
---> Running in 3f8bbba68f56
Removing intermediate container 3f8bbba68f56
---> b052cf9a8a1d
Step 4/22 : COPY package*.json ./
---> 5cb2da3f79c8
Step 5/22 : RUN npm ci
---> Running in 0f3c176d9412
[91mnpm[0m
[91m ERR! code ENOENT
[0m
[91mnpm ERR! [0m
[91msyscall open
[0m
[91mnpm ERR! path /tmp/node_modules/mock-mail-adapter/package.json
[0m
[91mnpm ERR! [0m
[91merrno -2
[0m
[91mnpm ERR! enoent[0m
[91m ENOENT: no such file or directory, open '/tmp/node_modules/mock-mail-adapter/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! [0m
[91menoent
[0m
[91m
[0m
[91mnpm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-04-08T22_53_48_782Z-debug.log
[0m
Removing intermediate container 0f3c176d9412
The command '/bin/sh -c npm ci' returned a non-zero code: 254
```

**Review by dplewis — APPROVED** [review]
LGTM!

**Comment by mtrezza** [comment]
@dplewis Docker build it broken?

**Comment by dplewis** [comment]
The latest build / branch is broken. Caused by https://github.com/parse-community/parse-server/pull/7321 and this PR may cause another similar error.

**Comment by mtrezza** [comment]
That's because of the local dependency I guess, I already thought that was too easy...

```
"mock-mail-adapter": "file:spec/support/MockMailAdapter",
"mock-files-adapter": "file:spec/support/MockFilesAdapter",
```

Any idea how to fix this for docker?

**Comment by mtrezza** [comment]
@dplewis I changed the path in this PR, could you see if that works for docker?

**Comment by dplewis** [comment]
@davimacedo I haven't used docker in while. Can you give it a try?

**Comment by mtrezza** [comment]
I'll try.
Yes docker building should be a CI check I guess.

**Comment by mtrezza** [comment]
I added a docker build check to the CI in https://github.com/parse-community/parse-server/pull/7332

**Review by dplewis — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)

**Pull request merged**
