### PR TITLE
feat: Add support for PostGIS 3.5

### LINKED ISSUE #9355: Upgrade CI to test against Postgis 3.5
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

A new [version of Postgis](https://postgis.net/2024/09/PostGIS-3.5.0/) was recently released

### Feature / Enhancement Description

Support latest version

### Example Use Case

N/A

### Alternatives / Workarounds

Test against older versions

### PR DESCRIPTION
**Pull request by cbaker6**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

A new version of Postgis was recently released. Currently not testing against.

Closes: #9355 

## Tasks

- [ ] Ensure test suite passes

### CODE REVIEW

**Comment by dplewis** [comment]
@cbaker6 should the scripts be updated? Would the extensions always install the latest?

**Comment by cbaker6** [comment]
> @cbaker6 should the scripts be updated? Would the extensions always install the latest?

The scripts here? https://github.com/parse-community/parse-server/tree/alpha/scripts They should always install the latest extensions available on the respective container (extensions were installed on the image via `apt-get`), so we should be good there.

**Comment by cbaker6** [comment]
@mtrezza this is ready for review

**Review by mtrezza — APPROVED** [review]
Looks good, waiting for CI to pass...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.4.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.4.0-alpha.3)

**Pull request merged**
