### PR TITLE
3.7.0 version bump + changelog

### PR DESCRIPTION
**Pull request by TomWFox**
This is a huge release!

giphy

Thanks to all those who contributed to this one!! 💪 👏  - @dplewis @douglasmuraoka @davimacedo @brunoMaurice @omairvaiyani

### CODE REVIEW

**Comment by TomWFox** [comment]
@dplewis shall I merge this or would you like me to hold off?

**Comment by TomWFox** [comment]
@dplewis just noticed that the docker build has been failing for the past few greenkeeper commits...

Screenshot 2019-07-28 at 20 48 46

**Comment by dplewis** [comment]
@TomWFox The docker build is fixed. I'm going to do a JS-SDK release first.

**Comment by TomWFox** [comment]
Nice 👍

**Comment by davimacedo** [comment]
The new version of JS-SDK was just merged. I think we can release the new Parse Server version, right?

**Comment by dplewis** [comment]
@davimacedo @TomWFox You can guys release it

**Pull request merged**
