### PR TITLE
Properly handle return values in beforeSave

### PR DESCRIPTION
**Pull request by blastoy**
Closes: https://github.com/parse-community/parse-server/issues/5227

a possible bug found where beforeSave does not apply changes to request
object if the beforeSave hook ends with 'true' and promises returned

### CODE REVIEW

**Comment by flovilmart** [comment]
Awesome! Thanks! Tell me, would you be tempted to attempt a fix?

**Comment by blastoy** [comment]
I leveled up and I just got a quest!

Sure, I’ll give it a try :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flovilmart** [comment]
Thanks @blastoy!

**Comment by blastoy** [comment]
OK, I've narrowed down the problem to this particular area:

https://github.com/parse-community/parse-server/blob/a4b592a3556cc8cc635fa5e230d41f137e222278/src/triggers.js#L255-L266

When the beforeSave hook returns true, the first if statement will resolve the response (which is true).

When the beforeSave hook does not return anything, the first if statement is skipped and instead the second if statement executes, later on resolving an object.

What is the purpose of the first if statement? If I comment that out, beforeSave works perfectly,

**Comment by blastoy** [comment]
My solution to the bug was to add some code right after the beforeSave trigger finishes that ignores whatever the hook returned. Figured if beforeSave works when the hook returns nothing, then making sure returns are ignored would work. Let me know what you guys think!

**Comment by dplewis** [comment]
You have some failing tests. Please check Travis.

**Comment by dplewis** [comment]
@blastoy Ping?

**Comment by blastoy** [comment]
Hey @dplewis, sorry was away for the holidays. The failing test cases are failing for me regardless of whether I run the tests on a completely clean version of the master branch. I’m not too sure what is causing this. That’s where I left off before the break.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
@blastoy Sorry for the late reply. Without looking into it, since you did change the functionality of the beforeSave, some of the beforeSave tests are failing. Update those tests to match your changes.

**Comment by dplewis** [comment]
@acinader I fixed the PR to address the original issue. It was discovered that returning in beforeSave was unnecessary and could lead to the hook not working. I can update the docs to address this.

**Comment by acinader** [comment]
this doesn't make sense to me.

1. you shouldn't have to use async/await
2. you should be able to return a promise and if it fails the save is aborted.

**Comment by dplewis** [comment]
> you should be able to return a promise and if it fails the save is aborted.

This works fine the issue is if the promise succeeds.

This works
```
Parse.Cloud.beforeSave('Insurance', function(req) {
  req.object.set('field', 'foo');
  return req.object;
});
```

This works
```
Parse.Cloud.beforeSave('Insurance', function(req) {
  req.object.set('field', 'foo');
  return new Promise(resolve => {
    resolve(req.object);
});
```

This fails
```
Parse.Cloud.beforeSave('Insurance', function(req) {
  req.object.set('field', 'foo');
  return new Promise(resolve => {
    resolve('almost anything but req.object');
});
```

**Comment by acinader** [comment]
the failing case is legal though.  and in the case where you're calling a function that may reject or may resolve, then what?  

I suspect that @blastoy had it right with "That response in the then is just a raw Boolean true, response.object being undefined. No fieldsChangedByTrigger will be found so its [sic] like no changes were done to the object"

If I've got it right, there are two options to solve:

1. document that the return object must be a promise that resolves to the object to save (which would be a breaking change from 2.x)

2. fix the logic to not fail if trigger resolves with any value which I think is consistent with 2.x and would be desireable.

**Comment by dplewis** [comment]
> fix the logic to not fail if trigger resolves with any value which I think is consistent with 2.x and would be desireable.

@acinader I went this route let me know if more tests are needed

**Comment by dplewis** [comment]
Good catch on that test!

@blastoy Thanks for the PR!

**Pull request merged**
