### PR TITLE
Microsoft Graph Authentication

### PR DESCRIPTION
**Pull request by alann-maulana**
Add authentication using Microsoft according [Microsoft Graph REST API v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)

### CODE REVIEW

**Comment by davimacedo** [comment]
@alann-maulana thanks for tackling this. Could you please add some test cases?

**Comment by alann-maulana** [comment]
@davimacedo ok, I'll try it

**Comment by davimacedo** [comment]
The CI is failing both for the lint and for the tests. Can you please take a look [here](https://travis-ci.org/parse-community/parse-server/builds/586114715?utm_source=github_status&utm_medium=notification) and fix it?

**Comment by alann-maulana** [comment]
@davimacedo fixed it (I think) but still there is an error 😐

**Comment by davimacedo** [comment]
@alann-maulana yes... this test is still failing:
Failures:
1) Microsoft Auth should fail to validate Microsoft Graph auth with bad token
  Message:
    Unhandled promise rejection: ParseError: 101 Microsoft Graph auth is invalid for this user.
  Stack:
    error properties: Object({ code: 101 })
    Error: Microsoft Graph auth is invalid for this user.
        at request.then.response (/home/travis/build/parse-community/parse-server/lib/Adapters/Auth/microsoft.js:3:431)
        at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by alann-maulana** [comment]
Yup, now the error goes to [Parse.Push](https://travis-ci.org/parse-community/parse-server/jobs/586891319#L1588)

```
1) Parse.Push does not get stuck with _PushStatus 'running' on 1 installation added
  Message:
    Expected 'running' to equal 'succeeded'.
  Stack:
    Error: Expected 'running' to equal 'succeeded'.
        at <Jasmine>
        at reconfigureServer.then.then.then.then.then.results (/home/travis/build/parse-community/parse-server/spec/Parse.Push.spec.js:402:38)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

never touch them btw 😅

**Pull request merged**
