### PR TITLE
Fix 5651

### PR DESCRIPTION
**Pull request by davimacedo**
Fix https://github.com/parse-community/parse-server/issues/5651

### CODE REVIEW

**Comment by dplewis** [comment]
The issue comes from https://github.com/parse-community/parse-server/blob/master/src/Controllers/DatabaseController.js#L1551

`updateSchemaWithIndexes` should be called in `performInitialization` and `performIntialization should be called after all the promises are resolved.

**Comment by davimacedo** [comment]
Do you see any potential problem related to them running in parallel besides the flaky tests? Otherwise we can just fix the tests.

**Comment by dplewis** [comment]
Not many people use the indexes API (as it needs some work) but having them at startup would be great.

**Comment by davimacedo** [comment]
I understand it is already running at startup, right?

**Comment by dplewis** [comment]
One potential problem would be for new clean databases, (similar to how tests cases are handled).

**Pull request merged**
