### PR TITLE
Sends pushes only when a deviceToken is set

### PR DESCRIPTION
**Pull request by felipemobile**
This is intended to solve a bug where some push notifications stuck in sending state

### CODE REVIEW

**Comment by TylerBrock** [comment]
Thanks, seems like it will fix the issue.

**Comment by felipemobile** [comment]
@TylerBrock Do you have any ideas why these test are failing?

1) Parse.Push should allow master key to query _PushStatus
  - Expected '{"deviceType":"ios","deviceToken":{"$exists":true}}' to equal '{"deviceType":"ios"}'.

2) PushController properly creates _PushStatus
  - Expected '{"deviceToken":{"$exists":true}}' to equal '{}'.

**Comment by flovilmart** [comment]
I'll work on this fix this Pm.

**Comment by felipemobile** [comment]
@flovilmart Please, let me know if you need any help.

**Comment by myusuf3** [comment]
Did this fix the parse `SENDING` issue?

**Comment by myusuf3** [comment]
Also what version was this released in?

**Comment by felipemobile** [comment]
@myusuf3 https://github.com/parse-community/parse-server/commit/03b6449fe1610e87108fca4632e843de9b697b4f

**Pull request closed without merging**
